### PR TITLE
AWS changed their error interface; fix compile breakage.

### PR DESCRIPTION
**Pull request by jefferai**

### CODE REVIEW

**Comment by jefferai** [comment]
Travis is out-of-date.

See https://github.com/awslabs/aws-sdk-go/commit/be94f7ca9b5c925574d65a152242415cadeb8dc1

**Comment by sethvargo** [comment]
Hi @jefferai 

Thank you for the PR. We use godep for this project, so I do not think upstream dependency changes affect us /cc @armon

**Comment by jefferai** [comment]
@sethvargo @armon First off -- you don't use godep everywhere. Check your build script. "make dev" does a "go get ./..." which won't always trigger this but can, especially on a first time dev build.

Second, you will hit this anyways, unless via godep you never, ever update this library. So you might as well get this sorted now.

**Comment by armon** [comment]
Such are the infinite joys of breaking upstreams.

**Pull request merged**
