### PR TITLE
Make web_ui complient with Go's embed rules

### PR DESCRIPTION
**Pull request by heppu**
If directory is embeded using Go's embed package it should be present in git repository to avoid failures/erros messages in Go commands. For empty directory this can be done using common .gitkeep pattern.

### CODE REVIEW

**Review by ccapurso — APPROVED** [review]
Looks good, thank you for contributing this fix!

**Comment by ccapurso** [comment]
Hi @heppu, I have approved the PR but merging is currently blocked by CircleCI. It looks like it might have hung which has happened in the past. This can usually be resolved by re-triggering CI via an empty commit. Would you be able to push an empty commit in an attempt to move this forward?

**Comment by heppu** [comment]
Done

**Comment by ccapurso** [comment]
Hi, @heppu. Unfortunately it seems that the issue might not be with CircleCI but instead that GitHub has not even triggered the jobs. I have opened a new PR, https://github.com/hashicorp/vault/pull/14246, which has your original commit cherry-picked from your remote. With that said, I'm going to close this PR and merge the new one. Thanks again for the contribution!

**Pull request closed without merging**
