### PR TITLE
Update to latest GRPC to make ent integ tests more reliable.

### PR DESCRIPTION
**Pull request by ncabatoff**
I believe https://github.com/grpc/grpc-go/pull/2818 is the cause of some of our intermittent test failures.  The symptoms don't match exactly but they're close, and with this patch applied (along with my other fix) I wasn't able to provoke the "no handler for route" integ test failures.  Note that this is apparently a fix for a 1.20 regression.

### CODE REVIEW

**Comment by jefferai** [comment]
I think sdk uses grpc too, in which case the better approach would be to update sdk, then update vault main against new sdk. This should force vault main to use sdk's declared version.

**Comment by ncabatoff** [comment]
Done, not sure why api got updated too.

**Comment by ncabatoff** [comment]
Could you have another look please @jefferai?

**Comment by jefferai** [comment]
Please update sdk first with the new version, then have Vault pull in the latest sdk.

**Comment by ncabatoff** [comment]
> Please update sdk first with the new version, then have Vault pull in the latest sdk.

I had already done so.  I've pulled in the latest changes from master, then tried doing the above a second time, but it was a no-op.

**Comment by jefferai** [comment]
You have to update SDK, then push a commit with that up to the repo, then update the main repo against the new SDK.

**Comment by ncabatoff** [comment]
Ah, that makes sense, I was just doing `go get ./sdk`.

**Comment by jefferai** [comment]
Looks like you didn't `go mod tidy` for at least `sdk`. How did you get SDK in here -- what commit is that referring to, considering this PR also has the changes in `sdk/go.mod`?

**Comment by ncabatoff** [comment]
First commit in this branch was me doing it wrong, i.e.

```
cd sdk
go get google.golang.org/grpc@v1.22.0
cd ..
go get ./sdk
```

Second commit was merge of master.

Third commit was result of

```
go get github.com/hashicorp/vault/sdk@update-grpc
```

Since I'm now confused and wanted a fresh start I created a new branch and will close this PR and work with that one instead (#7179).

**Pull request closed without merging**
