### PR TITLE
Docs: add note about enterprise replication installations section to upgrade guide

### PR DESCRIPTION
**Pull request by brianshumate**
A bit of information about upgrading in performance replication scenarios

### CODE REVIEW

**Comment by jefferai** [comment]
I think this is also true for DR replication, not just performance. It should probably be more of a replication guide than a performance replication guide.

Also I would prefer if the reminder about checking version-specific upgrade notes was up top instead of down bottom. In fact, IMHO that's the part that should be bolded, not the first bullet point :-)

**Comment by jefferai** [comment]
@brianshumate just a ping, are you going to circle back to this at some point?

**Comment by brianshumate** [comment]
Hey @jefferai, I updated this based on your feedback. I think eventually, a full guide would be nice to have, but this is helpful for now.

**Comment by jefferai** [comment]
Thanks! 👍

**Pull request merged**
