### PR TITLE
Udate to Go 1.16.5

### PR DESCRIPTION
**Pull request by vishalnayak**

### CODE REVIEW

**Comment by ncabatoff** [comment]
I see other 1.16.2 references in the tree, e.g. pkgs.yml, packages-oss.yml.

**Comment by vishalnayak** [comment]
I suspected something was amiss when `make packages` didn't result in a diff. I'll look as to why.

**Comment by ncabatoff** [comment]
Can you also do go_test.yml?  Sorry I forgot to mention that one in my last comment.

**Comment by vishalnayak** [comment]
I was wondering why .circleci/config.yml was not fully updated with 1.16.2. Updating `go_test.yml` and then running `make ci-config` did it!

**Review by ncabatoff — APPROVED** [review]

**Pull request merged**
