### PR TITLE
Adding migrate parameter for the unseal operation

### PR DESCRIPTION
**Pull request by dtrts**
This will allow the openapi generator to include all the body parameters

https://developer.hashicorp.com/vault/api-docs/system/unseal

Follows on from finding this parameter missing in the hashicorp/vault-client-go repository

https://github.com/hashicorp/vault-client-go/issues/253

### CODE REVIEW

**Review by sgmiller — CHANGES_REQUESTED** [review]
Could you remove the version availability statement?  Our docs are versioned so this will appear based on where it is in our release branches

**Comment by dtrts** [comment]
@sgmiller - Done.

I copied the doc line from [website/content/api-docs/system/unseal.mdx](https://github.com/hashicorp/vault/blob/7943a9e0948c42d88d256be7421edaf68bec2c46/website/content/api-docs/system/unseal.mdx#L35), i assume I don't have to make a similar change there?

**Comment by sgmiller** [comment]
Ah, I see.  Yeah, that shouldn't have it either, but not your fault.  I'll take that one on.

**Review by sgmiller — APPROVED** [review]

**Review by averche — APPROVED** [review]

**Comment by stevendpclark** [comment]
@dtrts thanks for the contribution.

**Pull request merged**
