### PR TITLE
Change grpc's max sent/recv size to a very large value.

### PR DESCRIPTION
**Pull request by jefferai**
We can restrict initial size at the HTTP layer so no need to restrict
here.

### CODE REVIEW

**Comment by briankassouf** [comment]
Should we so the same at plugin boundaries?

**Comment by jefferai** [comment]
Interesting idea. Sure. Would that be in go-plugin or here?

**Comment by jefferai** [comment]
@briankassouf Do all plugin connections (backend, database) now use the grpc broker? If so we could add a method onto that to set dial options.

**Comment by briankassouf** [comment]
@jefferai database plugins do not use the broker, backend plugins do.

**Pull request merged**
