### PR TITLE
Add basic autocompletion

### PR DESCRIPTION
**Pull request by briankassouf**

### CODE REVIEW

**Comment by brianshumate** [comment]
👋 I accidentally duplicated some of this effort today, but here's the initial docs section I'd written for `docs/commands/index` in hopes that they provide a good starting point:

## Autocompletion

The `vault` command features opt-in subcommand autocompletion that you can
enable for your shell with `consul -autocomplete-install`. After doing so,
you can invoke a new shell and use the feature.

For example, assume a tab is typed at the end of each prompt line:

```
$ vault au
audit-disable  audit-enable  audit-list  auth  auth-disable  auth-enable

$ vault s
seal  server  ssh  status  step-down
```

**Comment by jefferai** [comment]
@brianshumate Probably should be `vault -autocomplete-install` :-D

**Comment by brianshumate** [comment]
Corrected! 😉

**Comment by briankassouf** [comment]
@brianshumate Thanks! Added that to the docs section

**Pull request merged**
