### PR TITLE
Update SDK to 1.12.1

### PR DESCRIPTION
**Pull request by mpalmi**

### CODE REVIEW

**Comment by stevendpclark** [comment]
Was this supposed to be updated to 1.12.1? The 1.12.0 bump was already done by: https://github.com/hashicorp/vault/pull/17487

**Comment by mpalmi** [comment]
> Was this supposed to be updated to 1.12.1? The 1.12.0 bump was already done by: #17487

Yes, thank you!

**Review by stevendpclark — APPROVED** [review]
👍

**Review by anwittin — APPROVED** [review]
looks good

**Pull request merged**
