### PR TITLE
remove mount_accessor from the docs

### PR DESCRIPTION
**Pull request by raskchanky**
We removed this from the code but failed to update the docs.

### CODE REVIEW

**Review by hghaf099 — APPROVED** [review]
Thanks for taking care of this! I totally forgot about the docs.

**Comment by raskchanky** [comment]
Somehow the MFA docs as a whole [don't exist](https://github.com/hashicorp/vault/tree/release/1.10.x/website/content/api-docs/secret/identity) on the release/1.10.x branch. Compare that link with [main](https://github.com/hashicorp/vault/tree/main/website/content/api-docs/secret/identity) and note the lack of the `mfa` directory on the 1.10 branch. This explains why the automated backport of this PR failed. Given our versioned documentation though, it seems like the MFA docs should be present on the 1.10 branch, no? Unless I don't understand how the versioned docs work (which very well may be the case). I'm confused.

cc @BRKalow @ncabatoff @hghaf099 @mladlow

**Comment by mladlow** [comment]
It's possible they were never backported to the branch when the docs were created? @raskchanky or @hghaf099 any way you could do a diff of `stable-website` and `release/1.10.x`? There should be diffs in almost all circumstances I think.

**Comment by raskchanky** [comment]
@mladlow The diff between `release/1.10.x` and `stable-website` for just the `website` directory is non-trivial.

CleanShot 2022-04-06 at 11 03 28

**Comment by mladlow** [comment]
@raskchanky Yeah, I expect there's lots of stuff that needs to be on the 1.10 release branch - could you open a PR with the diffs and tag @kalafut @ldilalla-HC @peaceofthepai and myself and we'll figure out how to delegate review?

cc @thiskevinwang @BRKalow - any chance of updates on getting rid of stable website? We're having to do a bunch of extra legwork on this while we have this duplication.

**Comment by thiskevinwang** [comment]
@mladlow I should be able to start on this tomorrow
cc @BRKalow

**Comment by raskchanky** [comment]
@mladlow @thiskevinwang `release/1.10.x` should be up to date with new docs now https://github.com/hashicorp/vault/pull/14996

**Pull request merged**
