### PR TITLE
Added Vault version information to the 'status' command

### LINKED ISSUE #1668: Report version info in `vault status`
Related to #1647, can we get this information into the API, and report it with the output of `vault status`?

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #1668 

Did not add the version in the `unseal` command's output.

### CODE REVIEW

**Comment by LLBennett** [comment]
LGTM!

**Comment by jefferai** [comment]
LGTM. I realized looking at this that the cluster bits are also not plumbed through -- can you add those few lines too and merge the result?

**Comment by jefferai** [comment]
@LLBennett can you add the cluster bits when you get a chance?

**Comment by LLBennett** [comment]
@jefferai, Sure thing!

**Pull request merged**
