### PR TITLE
Add aws metadata to identity alias

### PR DESCRIPTION
**Pull request by maths22**
This allows for writing identity token templates that include these attributes
(And including these attributes in path templates)

### CODE REVIEW

**Comment by tyrannosaurus-becks** [comment]
Hi @maths22 , thanks for working on this!

Before we dig into this PR further, would you be willing to elaborate more on the identity token templates you're referring to? Maybe just a brief example of the templates that would be populated, and how this PR would achieve that?

Thanks!

**Comment by maths22** [comment]
@tyrannosaurus-becks Sorry for the delay; didn't see this until now.  These templates: https://www.vaultproject.io/docs/secrets/identity/index.html#token-contents-and-templates

For using vault identity tokens for service-service auth, it would be useful to encode information about the IAM principal in the token, so then the application can gate access based on e.g. the ec2 instance profile that was used to generated the JWT.

**Comment by maths22** [comment]
@tyrannosaurus-becks Thank you for the review.  I will write tests shortly, however, I'm not quite sure what you mean by a "positive and negative" test in this context.  Mostly I'm not sure what a negative text would look like.  Thanks!

**Comment by tyrannosaurus-becks** [comment]
@maths22 ah yes, I can do a better explanation! :-) I just mean, adding a test where each field _is_ provided and _isn't_ provided, then checking to see if the expected behavior happened. 

Or, if there's a pre-existing test that retrieves those auths, it would also be fine to just check that each field appears as expected.

**Comment by maths22** [comment]
Assuming it passes CI (the tests pass locally), I've added some tests for the IAM case.  I didn't add anything for the ec2 case because there aren't any unit tests that currently test the ec2 auth at all, so I didn't have anything to work from, and I don't understand the surrounding code well enough to write tests for that whole set of code from scratch.  Hopefully that is sufficient (all the key/value pairs are also included in the token metadata, so we know we aren't including any new values, and I have tested it manually locally and verified that the expected data appears with both login methods.

**Comment by tyrannosaurus-becks** [comment]
@maths22 please be advised that we will need to move this to being behind a flag. See the linked PR above to follow along so you can update your config when it's time.

**Pull request merged**
