### PR TITLE
Use MAP_POPULATE for our bbolt mmaps

### PR DESCRIPTION
**Pull request by ncabatoff**
... assuming the files fit in memory.  This should improve startup times when freelist sync is disabled.

### CODE REVIEW

**Comment by ncabatoff** [comment]
I have only tested this to the extent of verifying via strace that MAP_POPULATE is used on linux.

**Comment by raskchanky** [comment]
@ncabatoff Is it worth adding an env var to this to allow users to explicitly opt out of `MAP_POPULATE` completely?

**Comment by ncabatoff** [comment]
> @ncabatoff Is it worth adding an env var to this to allow users to explicitly opt out of `MAP_POPULATE` completely?

Good thinking, I'll add that.

**Comment by ncabatoff** [comment]
Added the suggested env var override.  Did some more serious testing on a Linux machine: besides just looking at strace to see that the option is used/not used based on env var, I actually gave it a 300MB vault.db that had seen lots of activity and had a big freelist.  With MAP_POPULATE, it took 2-6s to open the DB; without, 12-47s.  The machine was doing nothing else, I have no idea why it was so variable, but I did many runs, dropping caches in between.

To test the memory check, I used `truncate -s` to grow the vault.db file to bigger than my RAM.  When I looked at the strace output, I saw that vault.db was opened without MAP_POPULATE, where raft.db (still small) did use MAP_POPULATE.

**Pull request merged**
