### PR TITLE
changelog: fix spelling mistake

### PR DESCRIPTION
**Pull request by jweissig**
Replace consult-template with consul-template.

### CODE REVIEW

**Comment by lucymhdavies** [comment]
Simple change, no issues with that. Alas, I do not personally have authority to merge the PR.

**Comment by mladlow** [comment]
We will indeed overwrite this when we update the changelog for GA, however it's also too late to have the change reflected in the auto-generated stuff. I'm going to milestone the PR and come back to it when we have the real changelog up.

**Comment by mladlow** [comment]
Alternatively we could merge it now and we'll have to fix it again next week?

**Comment by jweissig** [comment]
Honestly, whatever works on your end. I just noticed it and wanted to flag it.

**Pull request merged**
