### PR TITLE
Add support for PROXY protocol v2 in TCP listener

### PR DESCRIPTION
**Pull request by remilapeyre**
I did not find tests for this so I added one trying to cover different
configurations to make sure I did not break something. As far as I know,
the behavior should be exactly the same as before except for one thing
when proxy_protocol_behavior is set to "deny_unauthorized", unauthorized
requests were previously silently reject because of https://github.com/armon/go-proxyproto/blob/7e956b284f0a/protocol.go#L81-L84
but it will now be logged.

Also fixes https://github.com/hashicorp/vault/issues/9462 by adding
support for `PROXY UNKNOWN` for PROXY protocol v1.

Closes https://github.com/hashicorp/vault/issues/3807

### CODE REVIEW

**Comment by hsimon-hashicorp** [comment]
Hi @remilapeyre - please don't forget a changelog entry. :)

**Comment by hghaf099** [comment]
@remilapeyre Thank you for submitting this PR. We would like to review and possibly merge it. Would you please rebase with main and resolve the conflicts?

**Comment by hsimon-hashicorp** [comment]
Hi @remilapeyre - we're super excited to get this reviewed, so could you take a look at the merge conflicts and we can move forward? Thanks! :)

**Comment by remilapeyre** [comment]
> Hi @remilapeyre - we're super excited to get this reviewed, so could you take a look at the merge conflicts and we can move forward? Thanks! :)

Hi @hsimon-hashicorp, all should be good now :)

**Pull request merged**
