### PR TITLE
Store a last renewal time in the token entry and return it upon lookup

### LINKED ISSUE #889: Ability to calculate expected expiration time when doing renews (last_renewed_time)
Hi,

At present, provided you do not do any token renewals, you are able to work out when a token is officially scheduled to expire by adding the `data.creation_time` and `data.ttl` fields together. I.e. given the following data returned from a token `lookup-self` call:
```
{
  "lease_id": "",
  "renewable": false,
  "lease_duration": 0,
  "data": {
    "creation_time": 1451339531,
    "display_name": "my-test-token",
    "id": "00dc06c0-blah-blah-c316ff4de29e",
    "meta": {
      "somekey": "somevalue"
    },
    "num_uses": 0,
    "orphan": false,
    "path": "auth/token/create",
    "policies": [
      "my-policy",
      "default"
    ],
    "ttl": 60
  },
  "warnings": null,
  "auth": null
}
```

this token should expire at unix time: 1451339531 + 60

However, if you renew your token, it appears that none of this information is made available to you when you do a lookup-self. Is there some other way to get this information? If not is it possible to add a `last_renewed_time` entry or something similar into the `data` section of the returned data? This would make this possible, as well as return info which I think might be genuinely useful to know in general circumstances too.

Thanks
Nicki

### PR DESCRIPTION
**Pull request by jefferai**
of the token.

Fixes #889

### CODE REVIEW

**Comment by nickithewatt** [comment]
@jefferai awesome tks!

**Comment by armon** [comment]
@jefferai Can we instead handle this in the expiration manager? That way we have a renew time for both tokens and leases, and we can do a single write to Consul instead of now doing 2 writes (lease + token).

**Comment by jefferai** [comment]
@armon Sure -- so are you thinking that we make this a property of a lease, and when we are doing a token `lookup/lookup-self`, we query the expiration manager from the token store to fetch this value?

**Comment by armon** [comment]
LGTM

**Pull request merged**
