### PR TITLE
Backport 1.7.x: Raft peer removal bug

### PR DESCRIPTION
**Pull request by zofskeez**

### CODE REVIEW

**Comment by mladlow** [comment]
@zofskeez are we looking to get this and its other backports merged soon so they go into a release?

**Comment by zofskeez** [comment]
> @zofskeez are we looking to get this and its other backports merged soon so they go into a release?

@mladlow Chelsea had concerns approving these backport PR's since a new dependency was added. I will loop up with her when she is back to confirm how to proceed.

**Comment by mladlow** [comment]
@zofskeez or @chelshaw is this still planned for 1.7? If we're worried about the dependency updates we could decide to not backport it to 1.7, I think, and just close this PR?

**Review by hashishaw — APPROVED** [review]
🚀

**Comment by mladlow** [comment]
Great! Always good to get this stuff in. I'm going to assign it the 1.7.10 milestone though, because we have the SHAs set for 1.7.9, 1.8.8, and 1.9.3.

**Comment by zofskeez** [comment]
Ok thanks! Sorry it took so long to get the issue sorted out.

**Pull request merged**
