### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by plcharbonneau**
I think that was a typo

### CODE REVIEW

**Comment by pmmukh** [comment]
@plcharbonneau the change looks good to me, but the CLA does need to be signed in order for us to merge this. Also, could you please rebase this off main ?

**Comment by hsimon-hashicorp** [comment]
Hi there! If you could, please take a peek at the CLA, and sign it if you're able. If your organization has signed a CLA, make sure the organization is publicly visible on your GitHub profile. Thanks!

**Review by taoism4504 — APPROVED** [review]
LG

**Comment by hsimon-hashicorp** [comment]
Hi @plcharbonneau! As confusing as it was when I had a PR to merge, I also had to sign the CLA. If you could do that, and then resolve the conflict, we can get this merged. Thanks!

**Comment by aphorise** [comment]
Closing as issue seems to be resolved already in [that documentation area of the site](https://www.vaultproject.io/docs/platform/k8s/csi#features):
Screenshot 2022-08-16 at 23 18 45

**Pull request closed without merging**
