### PR TITLE
aws-ec2 auth: Return the role period in seconds

### LINKED ISSUE #2373: aws-ec2 backend: period display issue
With vault v0.6.5, creating a role with `period=72h` or `period=259200` shows as `259200000000000` in vault cli.

Steps:

1) Create a role with a period of 72 hours:
```
vault write auth/aws-ec2/role/nomad-server \
bound_iam_instance_profile_arn="arn:aws:iam::XXXX:instance-profile/YYYY" \
period=259200 \
policies="default,nomad-server"
```

2) Read the role back (using any of the -format options):
```
vault read auth/aws-ec2/role/nomad-server
Key                           	Value
---                           	-----
allow_instance_migration      	false
bound_account_id              	
bound_ami_id                  	
bound_iam_instance_profile_arn	arn:aws:iam::XXXX:instance-profile/YYYY
bound_iam_role_arn            	
disallow_reauthentication     	false
max_ttl                       	0
period                        	259200000000000
policies                      	[default nomad-server]
role_tag                      	
ttl                           	0

```

For `period=3600`:
```
Key                           	Value
---                           	-----
allow_instance_migration      	false
bound_account_id              	
bound_ami_id                  	
bound_iam_instance_profile_arn	arn:aws:iam::XXXX:instance-profile/YYYY
bound_iam_role_arn            	
disallow_reauthentication     	false
max_ttl                       	0
period                        	3600000000000
policies                      	[default nomad-server]
role_tag                      	
ttl                           	0
```

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #2373

### CODE REVIEW

**Comment by vishalnayak** [comment]
That test works because I am comparing it with the value of `time.Duration(10)` which is technically not representing seconds anymore. Since the goal was simply to check the returned value, it did the job.

**Comment by jefferai** [comment]
There's actually a deeper "problem" there. `.Seconds` returns a `float64` so technically what's in the interface is a float64. Can you change the original code to int64() the values after the division by time.Seconds, and then just compare to 10 (or int64(10)) rather than time.Duration(10)? Overall it's much more correct even if this works, and we should ensure what goes across the API never has a decimal.

**Comment by jefferai** [comment]
("Problem" as in it's not really a big problem, but...let's fix :-) )

**Comment by vishalnayak** [comment]
`.Seconds()` is not used at all and hence the interface will be `time.Duration` which is divided by `time.Second` which is also `time.Duration`. The API as-is will *not* return a decimal. I might be missing something, but I don't see any problem :-), both in the code and the test.

**Comment by vishalnayak** [comment]
Also, IIRC we don't use `.Seconds()` to not make end users parse the `Go` syntax of `30s` and just the number without unit is easier to parse by API consuming systems which are not implemented in `Go`.

**Comment by jefferai** [comment]
.Seconds doesn't make users parse go time strings; that's reading into a duration and then formatting. Either way, what goes across the JSON API the way you're doing it is an int, fine, but I still really dislike the comparison to duration the way you're doing it. Anyone who knows the duration type is going to read that as 30 nanoseconds. It's unintuitive. Please just either make that proper 30 seconds, or change the return value to cast to an int64 and then compare against that.

**Comment by vishalnayak** [comment]
Sounds good and I agree that its unintuitive. Will change that to int64. 👍

**Pull request merged**
