### PR TITLE
make proto

### PR DESCRIPTION
**Pull request by raskchanky**
I realize we just merged a PR like this here https://github.com/hashicorp/vault/pull/17106

My ENT PR https://github.com/hashicorp/vault-enterprise/pull/2945
is also failing with the diff-oss check on proto files.

Is there a way of making sure we're all using the same version of protoc?

### CODE REVIEW

**Comment by raskchanky** [comment]
I'm using libprotoc 3.21.5, FWIW

**Comment by ccapurso** [comment]
> I'm using libprotoc 3.21.5, FWIW

It looks like Hamid's protos were generated using v3.19.4 so the only diff was the version comment at the top. I don't think that we don't have a means to ensuring we're all running the same version. It might be worth reaching out to the rest of the team to let them know though? Other folks might run into this if they run a `make proto`.

**Review by ccapurso — APPROVED** [review]

**Review by hghaf099 — APPROVED** [review]
Can we pin the protoc version the same as the go version such that make command would complain about it?

**Comment by raskchanky** [comment]
@hghaf099 I think so. I'll see if I can put a PR together.

**Pull request merged**
