### PR TITLE
OCI KMS plugin documentation

### PR DESCRIPTION
**Pull request by vuhpham-oracle**
This is documentation for OCI KMS plugin for auto unseal https://github.com/hashicorp/vault/pull/6950

### CODE REVIEW

**Comment by vuhpham-oracle** [comment]
@kalafut @chrishoffman Is there any format/guideline we need to follow for this documentation?

**Comment by kalafut** [comment]
@vuhpham-oracle As long as they're similar to the format/content of existing storage/seal/auth docs, you should be pretty close. I hope to review the docs PRs today and will provide specific feedback.

One useful thing is to follow the "deploy/netlify — Deploy preview ready!  ... Details" link to see how our docs platform is rendering them (or compile errors if there are any). This will rebuild any time you update the PR.

**Comment by malnick** [comment]
Associated PR for the code: https://github.com/hashicorp/vault/pull/6950

**Comment by vuhpham-oracle** [comment]
@kalafut @malnick I've pushed a new commit for this doc to follow other KMS plugins's format. Thanks for reviewing it.

**Comment by chrishoffman** [comment]
Please review https://github.com/hashicorp/vault/blob/master/website/README.md.  The current PR will not be included in the sidebar without the changes described in the README.

**Pull request merged**
