### PR TITLE
Allow creating Consul management tokens

### LINKED ISSUE #714: Consul Secret Backend - support for management tokens
According to the current documentation on the [Consul secret backend](https://vaultproject.io/docs/secrets/consul/index.html), roles created in Consul can only have an ACL policy/rule set specified. As a result, it's not possible to use Vault to generate management tokens for Consul. We very much need this functionality.

Use case:
We're implementing Vault and Consul not only for dynamic secrets (mainly AWS), but also as a unified secret storage system. Since we're also using the "generic" Consul backend to store non-dynamic secrets (i.e. third-party API keys, and other manually-entered secrets), we need to be able to back up the Consul KV store as part of our DR plan (as well as part of our test plan). However, only a management-level Consul token can read all KV and ACL data. So, our scheduled backup job (running in Jenkins) needs management creds for Consul.

Without Vault being able to lease management-level tokens for Consul, we end up back in exactly the position that Vault is being implemented to avoid, namely privileged credentials hard-coded somewhere in configuration management.

### PR DESCRIPTION
**Pull request by jefferai**
Fixes #714

### CODE REVIEW

**Comment by armon** [comment]
LGTM

**Comment by kenjones-cisco** [comment]
@jefferai Is there any updated API documentation on feature?

**Comment by jefferai** [comment]
@kenjones-cisco It appears I forgot that. Sorry! Feel free to send a PR, or I'll schedule it to get to it eventually :-)

**Comment by jefferai** [comment]
@kenjones-cisco Fixed. I'll push an update to the website as well.

**Comment by kenjones-cisco** [comment]
Thanks @jefferai :+1:

**Pull request merged**
