### PR TITLE
UI: Show day of month instead of day of year in the expiration warning dialog

### LINKED ISSUE #11619: Incorrect expiration date in the UI
**Describe the bug**

image001

See it says it will expire on May 137th.

**To Reproduce**
I'm not really sure how to reproduce it: the last authentication was done today, May 17th.

**Expected behavior**

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.7.1
* Vault CLI Version (retrieve with `vault version`):
* Server Operating System/Architecture:

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values
```

**Additional context**

### PR DESCRIPTION
**Pull request by balent**
Fixes #11619

### CODE REVIEW

**Comment by balent** [comment]
Fixes #11619

**Review by arnav28 — APPROVED** [review]
Thanks for fixing it 👍

**Comment by zerkms** [comment]
Why wouldn't this little change be merged?

**Comment by balent** [comment]
I'm not authorized to merge. Can somebody with the right permissions merge? Thanks!

**Review by hashishaw — APPROVED** [review]
Thank you for making this change!

**Comment by hsimon-hashicorp** [comment]
Hi @balent! Apologies for the delay on getting this merged. Would you be willing to refresh these code changes with the current `main`, so we can get it unblocked in our automated tests? We can get it merged right away once that's done. Thanks so much for your patience!

**Comment by balent** [comment]
Hi @hsimon-hashicorp I've just merged in the latest changes from the `main` branch. Thanks!

**Review by hsimon-hashicorp — APPROVED** [review]

**Pull request merged**
