### PR TITLE
Added list functionality to logical aws backend's roles

### LINKED ISSUE #1545: AWS: support list for aws/roles/
Hello,

It will be very useful to be able to read (list) the configured roles for AWS backend.

Example:

```
$ vault list aws/roles
Key
---
role1
role2
```

Without that, we need to keep tracking of configured roles, it's not very effective !

Thank you.

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #1545

### CODE REVIEW

**Comment by jefferai** [comment]
:+1:

**Comment by LLBennett** [comment]
LGTM!

**Comment by fernando-villalba** [comment]
My god... can you guys please put more information on these tickets? I keep going around in circles trying to see where and how this was implemented and none of the tickets linked provides any meaningful information

**Comment by fernando-villalba** [comment]
Just a quick note that the actual path that was implemented was this:

`vault list auth/aws/roles`

**Pull request merged**
