### PR TITLE
Adding OAuth2 authentication backend

### PR DESCRIPTION
**Pull request by mikeokner**
Uses the [golang/oauth2](https://github.com/golang/oauth2) library to authenticate users using the [Resource Owner Password OAuth2 flow](https://tools.ietf.org/html/rfc6749#section-1.3.3).  Policies can be assigned 100% locally within Vault or assigned based on entitlements read from an OpenID Connect userinfo endpoint that supplies group assignments in some particular field.

This endpoint is similar to the existing Okta backend in terms of configuration and usage. This new oauth2 backend has been tested specifically with [Ping](https://www.pingidentity.com/), but should work with any OAuth2-compliant provider that plays nice with the golang library.

### CODE REVIEW

**Comment by jefferai** [comment]
We need to do some internal discussion around accepting this. Most OAuth2 implementation in the real world are incompatible (the RFC is way under-specced) so this likely can't serve as a "generic" `oauth2` backend, and may end up being mostly a `ping` backend. Most OAuth2 providers also do not actually allow the username/password flow from external sites.

**Comment by mikeokner** [comment]
I waffled on whether to target Ping specifically, but that golang/oauth2 library appears to be explicitly compatible with many common providers so I went ahead and made this backend as generic as possible. I can't think of anything in this backend that would preclude it from working with any other common oauth2 provider (that supports the password flow).

The password flow is the most convenient for users when available, and in situations where Vault is deployed within an organization along side an internal identity provider, I think it qualifies as "highly trusted." There are some additional challenges around using the auth code flow since most providers want to redirect within a browser upon successful authorization. For G-Suite users it looks like Google allows you to specify a special `redirect_uri` that will allow the user to copy/paste the token which could then be used via CLI like the GitHub backend, but that's not common to other providers as far as I can tell.

Anyway, let me know what you all decide.

**Comment by bkrodgers** [comment]
Jeff,

There are two modes in which this plugin can be used.  The first is to just use it for authentication and map users directly to policies.  This should work with any oauth2 provider that implements the full spec, as resource owner grant type is part of that spec.  I'm not sure what you mean by "Most OAuth2 providers also do not actually allow the username/password flow from external sites."  Ping absolutely does.

The second is to get your group/entitlement membership through the IDP and map those groups to policies in the back end.  This is indeed one which some providers might not support, but I would think many would.  Ping has good support for it.  It's pretty straightforward to set it up to return data from any arbitrary source of data on the UserInfo endpoint for a given client, which means it can be tied into any entitlement system an organization uses.  But since that's all done on the IDP side, the code in Vault stays fully generic.

Admittedly we're not experts here at Monsanto on other IDPs besides Ping (and to some extent Okta, which one of our acquired subsidiaries uses).  And yes, I agree the specs leave much to be desired, but I think this will still work with other IDPs.  At a minimum in the first mode, and I think many will support the second.

**Comment by bkrodgers** [comment]
Mike and I talked offline, and I think one distinction to be made is around the well-known providers like FB, Google, etc that offer OAuth/OIDC and Ping/Okta/Gluu/etc that are deployed to provide an IDP for an organization.  I do grant that FB, Google, etc may have limits on resource owner flow that mean this isn't going to work with them.  Our intent here is more to support deployments of Ping/Okta/Gluu/etc.  Obviously Okta is already covered by its own backend that uses some proprietary APIs to get groups.  Ping doesn't really have that same concept of groups as a native feature, but it can return groups and any other attributes you want through the UserInfo endpoint.  We used a generic "oauth2" name because we suspected other IDPs can do that too, but we don't know that for sure.  If you think it really is only useful for Ping, we're happy to rename it.

**Comment by mikeokner** [comment]
Basic usage of this backend would look like:

```shell
# Enable oauth2 backend
$ vault auth-enable oauth2
# Configure it with the provider details
$ vault write auth/oauth2/config \
       provider_url='https://ping.example.com/as/token.oauth2' \
       client_id='VaultTest' \
       client_secret='1234567890qwertyuiop' \
       scope='openid profile' \
       userinfo_url='https://ping.example.com/idp/userinfo.openid' \
       userinfo_group_key='vault_entitlements'
# Map a group name to a policy in Vault
$ vault write auth/oauth2/groups/some-entitlement policies=some-policy
# Assign a user locally to a group
$ vault write auth/oauth2/users/someuser groups=team_two
 ```

**Comment by panga** [comment]
@mikeokner This PR allow users to authenticate with OAuth2 Bearer tokens?

**Comment by mikeokner** [comment]
@panga no, this one currently only implements the resource-owner password flow. It probably won't get merged in its current state as it sounds like there's a plugin-based auth backend in the works, and they'd rather see something like this end up as a plugin, not mainlined. (See end of #2525 discussion)

**Comment by jefferai** [comment]
@panga In fact, the proliferation of backends that have come up in the last couple of months around this are exactly why we want to take the approach we took with the combined database backend. The vast majority of the logic can be shared, so we want to share that and have plugins handle the things that are different.

**Comment by jefferai** [comment]
@mikeokner Thanks for bringing this back up my radar due to closing it :-)

We do intend to have a generic OIDC backend at some point, maybe 0.9 if possible, but given the lack of standards around group/role claims it's likely to be a skeleton for many services. However, in 0.8 we came out with backend plugins, so you now don't need us to merge this in if it's working for you -- just make a couple of small tweaks and it can be built standalone!

**Comment by mikeokner** [comment]
@jefferai yep, that's the plan! It's been working without a hitch in production for a couple months now so I'm just going to migrate this to a plugin.

**Pull request closed without merging**
