### PR TITLE
bump etcd client to v3.5.13

### LINKED ISSUE #26659: TLSv1.3 does not work with etcd storage backend
**Describe the bug**
Vault etcd storage backend uses etcd client v3.5.7 which does not work with TLSv1.3 ([link](https://github.com/etcd-io/etcd/blob/215b53cf3b48ee761f4c40908b3874b2e5e95e9f/client/pkg/transport/listener.go#L572-L575)). The problem can be fixed by bumping the go.etcd.io/etcd/client version to [v3.5.8](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md) or later ([link](https://github.com/etcd-io/etcd/pull/15156)).

### PR DESCRIPTION
**Pull request by tsaarni**
This change updates to latest etcd client version. It allows TLSv1.3 to be used between Vault and etcd.

Fixes #26659

### CODE REVIEW

**Comment by tsaarni** [comment]
@hsimon-hashicorp @stevendpclark :wave: Just a gentle nudge :smile: 

I just wanted to follow up on this PR and check if you had a chance to consider its inclusion, as it would fix a TLS 1.3 issue for users.

**Review by VioletHynes — APPROVED** [review]
Hey! Thanks for this. I don't see any issues with including this, so I'll try and get this merged :)

**Comment by VioletHynes** [comment]
@tsaarni it looks like there are merge conflicts with main -- sorry for jumping the gun with my last comment. If you could get them fixed and tag me when it's ready to merge again, I can hit the merge button if everything looks good.

Sorry this one took a little bit to get some eyes on :)

**Comment by tsaarni** [comment]
Thank You @VioletHynes for the review!  Now again ready for merge :)

**Pull request merged**
