### PR TITLE
Explicitly set timezone with PostgreSQL timestamps.

### LINKED ISSUE #597: timezone issue with postgresql
Vault seems to use UTC for expiration times. However, with at least postgresql backend there's an issue if the database backend is something else than UTC.

I'm on UTC+3 and if I create one hour lease, the password is already expired. The workaround is to "SET time zone 'utc'" in the role creation template, but that doesn't work for renew lease.

I've created a lease (lease=3h, lease_max=240h) and postgresql says: "Password valid until 2015-09-08 15:58:33+03". Then I renew the lease by adding 3600 as increment and after that the password expires sooner: "Password valid until 2015-09-08 11:01:40+03".

### PR DESCRIPTION
**Pull request by lassizci**
Fixes #597

### CODE REVIEW

**Comment by jefferai** [comment]
Unless I'm missing something, this just sets it to your own system's specific timezone, and will fail for anyone else.

**Comment by lassizci** [comment]
http://golang.org/pkg/time/#Time.Format

```go
fmt.Println(time.Now())
fmt.Println(time.Now().UTC().Format("2006-01-02 15:04:05"))
fmt.Println(time.Now().UTC().Format("2006-01-02 15:04:05-0700"))
```

will print
```
2015-09-10 21:12:14.911866327 +0300 EEST
2015-09-10 18:12:14
2015-09-10 18:12:14+0000
```

The change here is to explicitly tell postgresql we are inserting times in utc instead of letting it to use it's default, whatever is configured. Vault uses UTC internally anyway.

**Comment by jefferai** [comment]
Ah, I see.

It would be my preference for connections to the database to simply call `SET time zone 'utc'` upon connecting. That could happen in DB(). It's more code, but it would also ensure that any later connection doesn't accidentally make the same mistake.

**Comment by BRMatt** [comment]
@jefferai would that work if we're opening multiple connections to the server? The [postgres docs for `SET`](http://www.postgresql.org/docs/9.4/static/sql-set.html) seem to imply the new `TZ` would only last for the duration of the connection the command is run on:

> SESSION
> Specifies that the command takes effect for the current session. (This is the default if neither SESSION nor LOCAL appears.)

**Comment by jefferai** [comment]
@BRMatt It should. Under the hood the Go SQL library uses a connection pool, so generally it will be set once and then be a no-op.

However, any time code in the backend needs to handle a database connection, it calls the backend's `DB` function to get the session. So if the `SET` command is run there before returning the session, any session used by the backend should have that option set.

The only concern would be if this drastically increases the number of calls being made to the DB. That depends mostly on whether this is a client side option or server side option, or, if it's a server side option, whether the utilization caused by more of these commands is completely negligible (which it very well may be).

**Comment by lassizci** [comment]
I tested this a little bit. If we execute query with ```set time zone 'utc'``` and create users in a loop (with increased connection pool size), some users have wrong expiration and some have the correct one. So it doesn't work like that directly.

Wasn't directly mentioned in the documentation, but luckily the (pq)library seems to support timezone as connection parameter, so we could add that to connection parameters. It's easy to test with just connection string:

```
vault write dbsecrets/config/connection value="postgresql://myuser:mypassword@127.0.0.1:5432/template1?sslmode=disable&timezone=utc"
```
vs

```
vault write dbsecrets/config/connection value="postgresql://myuser:mypassword@127.0.0.1:5432/template1?sslmode=disable"
```

**Comment by jefferai** [comment]
@lassizci The inconsistent results were after adding that query before any non-error return from .DB()? That strikes me as really strange.

That said, I do think adding the timezone value to the connection string makes sense. The only (really easy) rub there would be detecting whether there are already any parameters so we need an `&` or none so we need a `?` or whether a `?` is in the string but is the last character (so we need just the timezone string).

**Comment by BRMatt** [comment]
> @BRMatt It should. Under the hood the Go SQL library uses a connection pool, so generally it will be set once and then be a no-op.

Ok, but won't each individual connection managed by the pool have a separate session? I may be wrong about this - I've never really had to use per-session options before. It seems like the connection parameter may be a good way to work around this.

**Comment by jefferai** [comment]
@BRMatt Yes -- but if all sessions used elsewhere in the backend are returned by the `DB()` function, then calling the `SET` command on any session being returned directly before returning should have the correct behavior.

Regardless, I'm also a fan of using the connection parameter.

**Comment by BRMatt** [comment]
:facepalm: I see what you mean now, sorry about that!

**Comment by lassizci** [comment]
>@lassizci The inconsistent results were after adding that query before any non-error return from >.DB()? That strikes me as really strange.

Yes, that's what happened. I tested by increasing the connection pool to 8 and then creating 64 credentials in a loop. Half of the users had correct time zone and the rest didn't.

But when the timezone is set in the connection string, it seems to work reliably. My fork is now updated. I ended up converting url to key value pairs, if it's defined as url, since the library provides a function for that.

**Comment by jefferai** [comment]
path_role_create and secret_creds still have the expanded timestamp format.

Also, the `pq` library says that the ParseURL function is unnecessary and only retained for backwards compatibility. I'd prefer not to rely on it staying around (or working properly) forever. Please modify the connection string instead.

Thanks!

**Comment by lassizci** [comment]
>path_role_create and secret_creds still have the expanded timestamp format.
Wouldn't it be better practice to have timezone explicitly in time time formats?

>Also, the pq library says that the ParseURL function is unnecessary and only retained for >backwards compatibility. I'd prefer not to rely on it staying around (or working properly) forever. >Please modify the connection string instead.
Ok, I'll write my own parser. That just felt handy as we need to accept both URL style and pg connection string style and e.g passwords may have characters like ?.

**Comment by jefferai** [comment]
> Wouldn't it be better practice to have timezone explicitly in time time formats?

Much of the point of setting things to UTC in the connection rather than specifying those formats there is so that future changes that may not properly set the time zone in the string will still work correctly. So this is really a no-op. Leave it in if you feel strongly about it, but since it has no effect it doesn't really matter.

> passwords may have characters like ?.

Fair enough. Leave it as is.

**Comment by jefferai** [comment]
Merged -- thanks a bunch!

**Pull request merged**
