### PR TITLE
Split 'policies' command into 'policy-read' and 'policy-list'

### PR DESCRIPTION
**Pull request by vishalnayak**
cc: @sethvargo

### CODE REVIEW

**Comment by sethvargo** [comment]
Hey @vishalnayak 

I talked with @jefferai about this and I would prefer to see all the `policy-*` and `policies` command go away entirely instead of splitting them out into different functions. Policies should behave just like any other write `vault write sys/policies/foo policy="path ..."`.

**Comment by jefferai** [comment]
Also I think this needs to wait for a time when we can go through and make changes to everything at once. There are lots of commands that ought to be fixed up.

**Comment by sethvargo** [comment]
@vishalnayak - @jefferai and I talked a lot in Amsterdam about some really nice (backwards-compat) changes we could make in Vault to improve the UX. Maybe we should hash out a plan over a call and put together a plan.

**Comment by jefferai** [comment]
This may also be an excellent topic for the employee summit in less than a month when we're all face to face.

**Comment by jefferai** [comment]
Closing for now. We'll reopen if needed to discuss internally.

**Pull request closed without merging**
