### PR TITLE
limit custom max ttl to mount max lease ttl and allow 0 num uses and …

### PR DESCRIPTION
**Pull request by HridoyRoy**
…ttl if specified explicitly

This is an update to https://github.com/hashicorp/vault/pull/14474/files which implements a feature for https://github.com/hashicorp/vault/issues/14390

### CODE REVIEW

**Review by hghaf099 — APPROVED** [review]
lgtm

**Review by mpalmi — APPROVED** [review]

**Comment by RemcoBuddelmeijer** [comment]
After noticing this PR through the issue I worked on, I thought I would share my initial thoughts as I noticed something.

The current implementation guards for specific scenarios of custom num_uses/ttl - role num_uses/ttl combinations, but does not prevent the user from using infinite custom parameters.
From what I understand this PR is trying to allow infinite custom parameters and bind the custom ttl to the mounts max TTL. Part of this can already be done and might be broken in this PR.

Allow me to explain by showing what my design of the guard statement was:

1. First it checks if the parameter has been set to infinite, if yes it will check if the role's configuration entry is finite. Since it's bound to the role's configuration it may not be higher than it. If it is the case, it fails.
2. If this is not the case it will check if the role's configuration is finite. If this is not the case it will continue. However, if this is the case it will simply check if the custom parameter is in bound (for num_uses higher than and ttl lower than) with the role's configuration.

As seen in this [test case](https://github.com/hashicorp/vault/blob/3e6f7a35f62cba310e146b87da0bddbc8cd88688/builtin/credential/approle/path_role_test.go#L1200-L1211) a combination of infinite num_uses/ttls is allowed. But if the custom num_uses/ttl is infinite while the role's num_uses/ttl is finite, it breaks the rules. That is the purpose of the guard statement. This all is also mentioned in the endpoint's documentation.

If my assumptions are correct, I would propose to bind the role's TTL to the mount max lease ttl instead. The custom secret id will automatically be limited by it.

**Comment by HridoyRoy** [comment]
@RemcoBuddelmeijer you're right, my mistake. I'll update the PR to just keep the lines here [here](https://github.com/hashicorp/vault/pull/17001/files#diff-2192a05f927872939119d6a7808796eff8438caf56ee814e349e153a67ae5fbfR2403), as I want to ensure that the ttl specified in the request could not exceed the ttl on the backend. This would be especially problematic if no ttl on the role was set.

**Comment by HridoyRoy** [comment]
Doing a little more digging in the code @RemcoBuddelmeijer , it seems like `MaxLeaseTTL()` is indeed not used to guard against the ttl of the SecretID -- only the ttl of tokens that are issued. Given this, I'll go ahead and close this PR.

Thanks for the review, I appreciate it!

**Pull request closed without merging**
