### PR TITLE
Docs: Correct AES256 key length in Transit storage limits

### PR DESCRIPTION
**Pull request by krarey**
The AES256-GCM96 key was mis-labeled as AES128 under Transit storage limits. Corrected the table.

Looks like it was inadvertently copied from the row above. Adding @mgritter in case this is inaccurate.

### CODE REVIEW

**Review by mgritter — APPROVED** [review]
Yup, thank you! I consulted my original spreadsheet and the numbers are correct number for aes256, but it was mislabeled.

**Comment by krarey** [comment]
Awesome, thank you for confirming! I don't have the necessary permissions to merge this to master. Will it be picked up automatically, or does somebody else need to trigger it?

**Comment by mgritter** [comment]
You should have been able to merge after I gave approval, but I'll go ahead and do it.

**Comment by amoraroma** [comment]
Пт, 4 дек. 2020 г. в 21:31, Kyle Rarey <notifications@github.com>:

**Pull request merged**
