### PR TITLE
Added HA information to CLI when using different output format

### LINKED ISSUE #6179: Missing HA information in CLI when using format json/yaml
**Describe the bug**
HA information missing for `vault status --format=json (or yaml)`

**To Reproduce**
1. Run `vault status --format=json (or yaml)`
2. The HA information is missing from the output
```
$ vault status --format=json
{
  "type": "shamir",
  "initialized": true,
  "sealed": false,
  "t": 3,
  "n": 5,
  "progress": 0,
  "nonce": "",
  "version": "1.0.2",
  "migration": false,
  "cluster_name": "vault-cluster-xxxx",
  "cluster_id": "xxxx",
  "recovery_seal": false
}
```

With default format:
```
$ vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    5
Threshold       3
Version         1.0.2
Cluster Name    vault-cluster-xxxx
Cluster ID      xxxx
HA Enabled      true
HA Cluster      https://x.x.x.x:xxxx
HA Mode         active
``` 

**Expected behavior**
Expected the same values in the output when using `-format=json` vs `format=table`

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.2
* Vault CLI Version (retrieve with `vault version`): Vault v1.0.2 ('37a1dc9c477c1c68c022d2084550f25bf20cac33')
* Server Operating System/Architecture: Ubuntu

Vault server configuration file(s):

```hcl
ui = true
storage "consul" {
  address = "127.0.0.1:8500"
  path = "vault/test"
  service = "vault"
}
listener "tcp" {
 address = "0.0.0.0:8200"
 tls_disable = 0
 tls_cert_file = "/etc/pki/tls/vault/cert.pem"
 tls_key_file = "/etc/pki/tls/vault/key.pem"
}
```

### PR DESCRIPTION
**Pull request by michelvocks**
Fixes #6179

### CODE REVIEW

**Comment by michelvocks** [comment]
> It's kind of weird that the sys/seal-status endpoint is now returning information unrelated to seal. I think I'd be more comfortable with an approach that only modified what the vault cmdline does, as opposed to modifying the seal-status API.

I agree. The problem with modifying the cmdline is that it introduces two other imperfections.
1. `OutputData` (https://github.com/hashicorp/vault/pull/6186/files#diff-3e4377911a05a6f261016d1d5e1fec91R312) only accepts one data parameter. I'd have to merge both responses (sys/seal & sys/leader) into one combined struct which is also weird.
2. We still have to do two backend calls to get one correlated output.

I guess a better approach would be to create a new API endpoint (e.g. sys/status)?

**Comment by ncabatoff** [comment]
> 1. `OutputData` (https://github.com/hashicorp/vault/pull/6186/files#diff- 3e4377911a05a6f261016d1d5e1fec91R312) only accepts one data parameter. I'd have to merge both responses (sys/seal & sys/leader) into one combined struct which is also weird.

One idea (which I haven't tried): marshal both structs into json, then unmarshal them into maps.  Merge the maps, give the combined map as input to OutputData.  This way we keep the correct key names for each field, but we don't have to maintain another struct that mirrors the contents of the two underlying structs.

> 2. We still have to do two backend calls to get one correlated output.

That was already the case.

**Comment by jefferai** [comment]
Additionally `-output-curl-string` only shows the first call.

The right approach may be to deprecate the existing leader/seal-status calls and create a status endpoint. I suggest checking with Brian and see which direction he wants to go.

**Comment by michelvocks** [comment]
@briankassouf Would be nice to get your advice here if you got time 😄

**Comment by aphorise** [comment]
@michelvocks @jefferai @ncabatoff I believe this no longer relevant and may be closed? - please confirm.

**Comment by ncabatoff** [comment]
@aphorise Indeed, ty

**Pull request closed without merging**
