### PR TITLE
Add upnattribute config option to LDAP

### LINKED ISSUE #16712: LDAP UPNDomain option only works correctly if LDAP is Microsoft AD
Hey there!

I'm currently playing with LDAP and Kerberos in vault, and I've run into an issue. Basically, while the LDAP backend supports looking up the UPN, it assumes that the attribute the UPN is stored in is called `userPrincipalName` - however, that is only guaranteed to be the case if the LDAP happens to be Microsoft Active Directory. Given that LDAP schemas are not that well standardized across vendors, I believe this should be configurable, just like e.g. `groupattr`.

I checked the code at https://github.com/hashicorp/vault/blob/main/sdk/helper/ldaputil/client.go#L269-L273, where the attribute is indeed hardcoded:
```
func (c *Client) GetUserDN(cfg *ConfigEntry, conn Connection, bindDN, username string) (string, error) {
	userDN := ""
	if cfg.UPNDomain != "" {
		// Find the distinguished name for the user if userPrincipalName used for login
		filter := fmt.Sprintf("(userPrincipalName=%s@%s)", EscapeLDAPValue(username), cfg.UPNDomain)
```

Unless there are specific reasons to do otherwise, I can just quickly raise a PR to add a config option to make this configurable.

### PR DESCRIPTION
**Pull request by uubk**
This PR closes #16712.

Based on that issue, while the LDAP backend supports looking up the UPN, it assumes that the attribute the UPN is stored in is called userPrincipalName - however, that is only guaranteed to be the case if the LDAP happens to be Microsoft Active Directory. Given that LDAP schemas are not that well standardized across vendors, I believe this should be configurable, just like e.g. groupattr. This PR does just that, it adds a new config option `upnattribute` and defaults it to the old value.

### CODE REVIEW

**Comment by hsimon-hashicorp** [comment]
Hi there! Can you revert your edit to the CHANGELOG file, and instead include a file changelog/16713.txt with your changelog entry? That'll make the changelog check job happier. Thanks! :)

**Comment by uubk** [comment]
> Hi there! Can you revert your edit to the CHANGELOG file, and instead include a file changelog/16713.txt with your changelog entry? That'll make the changelog check job happier. Thanks! :)

Sure! Sorry, misread the instructions.

**Comment by VioletHynes** [comment]
Hi there @uubk ! Super sorry that this has languished without a review for so long. This looks good to me, and I'd be happy to approve this and try to get it merged if you could update the branch off main and fix the merge conflicts. I know that's a big ask after so long, but I'd love to get this merged as this seems to be a really nice change.

Thank you for your patience, and I'd love to get this over the finish line if you're still interested. Feel free to tag me as much as you need to get it over the line :)

**Comment by VioletHynes** [comment]
Hey there! This has been waiting for quite some time for a response now so I'm going to close it to prevent it from becoming more stale.

Sorry it took so long to get eyes on this, and I appreciate how frustrating that can be. If you're still interested in getting this in, then I'd encourage you to re-open this with the conflicts resolved. Thank you for your contribution and interest regardless!

**Pull request closed without merging**
