### PR TITLE
Allow hyphens in endpoint patterns of most backends

### LINKED ISSUE #559: write aws/roles fails with hyphen in path
I am seeing the following:

`vault write aws/roles/foo-bar` fails with "Unsupported Path".

`vault write aws/roles/foo_bar` succeeds.

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #559

### CODE REVIEW

**Comment by vishalnayak** [comment]
@jefferai Two commits crept into this PR, which do not belong here.
Install script's cleanup() method still needs to be hooked with EXIT status for proper cleanup.
I will do it in a separate effort.

**Comment by jefferai** [comment]
@vishalnayak it's its own branch, so feel free to force-push to wipe those away

**Comment by ekristen** [comment]
+1

**Comment by jefferai** [comment]
LGTM :+1:

**Pull request merged**
