### PR TITLE
Switch to a forked copy of pkcs7 to fix aws pkcs7 verification error

### LINKED ISSUE #4014: aws auth backend fail to verify signature
**Environment:**

* Vault Version: v0.9.4

auth backend: `aws-ec2`
auth role `auth_type`: `ec2`

**Expected Behavior:**

successful ec2 auth

**Actual Behavior:**

failed ec2 auth:

```
* failed to verify the signature
```

**Steps to Reproduce:**

```
vault write -address http://active.vault.service.consul:8200 -format json auth/aws/login role=$role pkcs7="$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 | tr -d '\n')" nonce=${nonce}
```

**Important Factoids:**

Worked on 0.9.3

### PR DESCRIPTION
**Pull request by jefferai**
Fixes #4014

### CODE REVIEW

**Comment by mohsen0** [comment]
Please release :)

**Comment by jippi** [comment]
@jefferai is it likely to be a quick release with this fix? seem like a pretty big regression, sufficiently big to yield a new patch release :)

**Comment by jefferai** [comment]
The chances will go way up if you can independently verify this fixes the problem and report back, as I've not had a chance to run testing suites.

**Comment by jefferai** [comment]
@joelthompson in case you're bored and have a good test setup at the ready :-)

**Comment by joelthompson** [comment]
For future reference, I tested both this fork of the pcks7 library as well as the updated upstream one, built using go1.10, and verified that both of them passed the test suites.

**Comment by jippi** [comment]
Thanks @joelthompson !

**Pull request merged**
