### PR TITLE
Added Artifactory secrets plugin

### PR DESCRIPTION
**Pull request by MitaliBo**
Added Artifactory secrets vault plugin under partner programs

### CODE REVIEW

**Review by hsimon-hashicorp — CHANGES_REQUESTED** [review]
Can you name it JFrog Artifactory, to be clear about the specific implementation? Thanks! :)

**Comment by MitaliBo** [comment]
> Can you name it JFrog Artifactory, to be clear about the specific implementation? Thanks! :)
Made the change, Thanks!

**Review by hsimon-hashicorp — APPROVED** [review]

**Comment by MitaliBo** [comment]
when this change will be reflected in plugin portal page? @hsimon-hashicorp

**Comment by hsimon-hashicorp** [comment]
@MitaliBo Apologies for the delay - updating our documentation is a slightly more manual process. It's there now, though! Thanks for your patience. :)

**Pull request merged**
