### PR TITLE
adds port parameter

### PR DESCRIPTION
**Pull request by Lexman42**

### CODE REVIEW

**Comment by tyrannosaurus-becks** [comment]
Hey! Should we close this in favor of #6144?

**Comment by Lexman42** [comment]
Fixes #5977

**Comment by chrishoffman** [comment]
🎉

**Comment by yazand** [comment]
When this fix will be available ? dose the latest binary of vault.exe include it ?

**Comment by yazand** [comment]
@Lexman42, When this fix will be available ? dose the latest binary of vault.exe include it ?

**Pull request merged**
