### PR TITLE
Netlify Deployment

### PR DESCRIPTION
**Pull request by jescalan**
So, I am very much new to terraform, feedback very welcome. In general here's what I'm aiming for here:

1. Terraform script added that provisions Netlify's configuration. This has been tested previously and is working nicely. Any of the variables are absolutely up for change if need be.

2. Makefile updated to use netlify's build image directly. The first run, this takes a bit longer to download due to it being larger than the hashicorp-middleman image, Netlify being a larger service that can deploy many types of sites. However, on subsequent runs its pretty quick and carries the additional benefit of cacheing dependencies between builds.

3. Removal of all old deploy script pieces that I could find. If there are any I missed please let me know and I'll remove them.

We will be setting this up on HashiCorp's internal TFE instance to keep track of state and serve as a bit of a buffer to Netlify config changes, which can easily cause downtime if not done carefully.

### CODE REVIEW

**Comment by alvin-huang** [comment]
LGTM after cleanup of the `.terraform` folder cleanup.

**Comment by jescalan** [comment]
Thanks for the feedback! Everything addressed in the most recent commits 😬

**Comment by jfreda** [comment]
One note here: I _think_ that unless either this PR is squashed and merged, this branch will need to be rebased first to prevent the Netlify provider binary from ending up in the repo.

**Comment by alvin-huang** [comment]
Good point @jfreda it'll be in git history from `17a96f8`

**Comment by jescalan** [comment]
@jfreda - great catch, I will squash it to a single commit

@meirish - thanks for taking the time to review this! we do still need the gemfile - netlify pulls the source and builds the site any time a new commit is pushed to the target branch, so it does still need to be able to install deps (although after the first run it does cache them unless they changed)

**Comment by jescalan** [comment]
Nope, we can drop this - good catch

**Pull request closed without merging**
