### PR TITLE
Revert "Backport of AutoMTLS for secrets/auth plugins into release/1.11.x (#16343)"

### PR DESCRIPTION
**Pull request by swenson**
This reverts commit b443be6491ba40bb45c9e08d5b52dd8ead3e1e73.

The original commit caused the PKI plugin to fail:

```
$ vault secrets enable pki
$ vault write -format=json pki/root/generate/internal \
        common_name=example.com \
        ttl=8760h

...
* Can not create root CA until migration has completed
```

### CODE REVIEW

**Review by calvn — APPROVED** [review]

**Comment by sathieu** [comment]
@swenson @calvn there is "promote-production" job that has started 18h ago, and still running: https://github.com/hashicorp/vault/runs/7452464155. Maybe this is the cause for https://github.com/hashicorp/terraform/issues/31493 and https://github.com/hashicorp/consul/issues/13850?

**Comment by swenson** [comment]
Hmm. Maybe @mladlow would know better?

**Comment by mladlow** [comment]
I'm catching up on some older emails while I was on PTO. Is this still an issue?

**Comment by swenson** [comment]
Looks like the releases were fixed, so this is no longer a problem.

**Pull request merged**
