### PR TITLE
Escape backslash to allow usage of dev server on Windows using MinGW

### PR DESCRIPTION
**Pull request by fubar-coder**
This is a partial fix for issue #95.

### CODE REVIEW

**Comment by ftyszyx** [comment]
i change the code you commit,and i build it ,why the question is still exist?

**Comment by fubar-coder** [comment]
I guess that they didn't merge the pull request yet, because a change like this smells like a hack. A better solution might be using a function to escape shell arguments and a way to call the OS' default shell (cmd instead of sh). IOW: The "problem" with my solution is, that it only works for UNIXish platforms (like MinGW on Windows), but doesn't work on pure Windows environments.

**Comment by ftyszyx** [comment]
i got it,you mean the vault can't run on pure windows enviroments.

**Comment by armon** [comment]
Sorry about the delay! Although a hack, it should work fine!

**Pull request merged**
