### PR TITLE
Changelog: fixed a typo and added lease expiry metrics

### PR DESCRIPTION
**Pull request by HridoyRoy**
Related PR: https://github.com/hashicorp/vault/pull/10375

### CODE REVIEW

**Review by mgritter — COMMENTED** [review]
This list is supposed to be grouped by subsystem, so the two "core" entries belong together.

**Review by mgritter — APPROVED** [review]
Looks good, but maybe @mladlow would prefer you use the new changelog automation?

**Comment by mladlow** [comment]
@HridoyRoy the changelog updates are in 1.6.0 - did these changes go into 1.6.0? If they did, we can leave the changelog as-is, if they did not, can you use the wiki link I'll send you to change this PR to using the new changelog format. Thanks for pinging me @mgritter!

**Comment by HridoyRoy** [comment]
Going to close this PR out and open an equivalent PR with the changelog tool.

**Pull request closed without merging**
