### PR TITLE
add the note about `s.` prefix to docs

### LINKED ISSUE #8092: Unclear failure when trying to init dev vault with invalid token ('s.' prefix)
**Describe the bug**
Trying to initialise vault server in DEV mode with a user provided token formatted like the ones vault generates results in a generic error. Apparently, custom (user defined) vault tokens cannot have a 's.' prefix (e.g. 's.6w3CpXn5vChbnpLtBlCJCUxs'). The error is not-so-helpful and i haven't seen this mentioned in the official documentation. 

**To Reproduce**
1. Run `vault server -dev -dev-root-token-id="s.6w3CpXn5vChbnpLtBlCJCUxs"`
2. See generic (not-so-helpful) error:
Error initializing Dev mode: failed to create root token with ID "s.6w3CpXn5vChbnpLtBlCJCUxs": 1 error occurred:
	* invalid request

**Expected behavior**
Have a more specific error message that clarifies why the token is invalid and/or mention this more clearly in the documentation.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.0
* Vault CLI Version (retrieve with `vault version`): 1.3.0
* Server Operating System/Architecture: alpine(vault container) and mac osx 64-bit

Vault server configuration file(s):

**Additional context**
Ran into this issue while trying to run a vault test container and submitted a PR to fail-fast while configuring the vault container ([https://github.com/testcontainers/testcontainers-java/pull/2228](url)).

### PR DESCRIPTION
**Pull request by vvelikodny**
fix issue #8092 
- improve dev custom token error description
- add the note to docs about impossible to create a custom token with 's.' prefix

### CODE REVIEW

**Comment by ncabatoff** [comment]
Hi @vvelikodny,

Thanks for the patch!

The doc change looks good.  I'm not sure about the code change though.  We already return the error correctly when going through the API:

```
mbp:ncabatoff ncc$ vault token create -id=s.d
Error creating token: Error making API request.

URL: POST http://localhost:8200/v1/auth/token/create
Code: 400. Errors:

* custom token ID cannot have the 's.' prefix
```

So I think the problem is more with the `server` command than the token backend.  Although the token backend probably needs a tweak too.  I created my own PR (#8196) to explore this issue.  

I think most of the time HandleRequest should either return a non-nil `logical.Response` (possibly including an error to expose to the user) or a non-nil error, but not both.  Then [RespondErrorCommon](https://github.com/hashicorp/vault/blob/master/sdk/logical/response_util.go#L17) should be used to interpret the results.

**Comment by vvelikodny** [comment]
@ncabatoff thanks, checked on your branch, looks good. I've updated PR too, left docs only

**Comment by ncabatoff** [comment]
Could you please also update the docs for the `id`param in website/pages/api-docs/auth/token/index.mdx under Create Token?

**Comment by vvelikodny** [comment]
> Could you please also update the docs for the `id`param in website/pages/api-docs/auth/token/index.mdx under Create Token?

done @ncabatoff

**Comment by vvelikodny** [comment]
I think better to update docs to give users know what format/characters are eligible for token ID

**Comment by ncabatoff** [comment]
Looks like the failure is because with the exception of leading `s.` or `b.`, a `.` in a token is intended to be used to record the namespace that token belongs to.  But in the example you give, there is no corresponding namespace.  So dots should not be used in user-defined token IDs.

I don't know what other constraints may exist (I haven't found any yet, but it's a big codebase).

**Comment by vvelikodny** [comment]
> Looks like the failure is because with the exception of leading `s.` or `b.`, a `.` in a token is intended to be used to record the namespace that token belongs to. But in the example you give, there is no corresponding namespace. So dots should not be used in user-defined token IDs.
> 
> I don't know what other constraints may exist (I haven't found any yet, but it's a big codebase).

issue here
https://github.com/hashicorp/vault/blob/e3446a58ae91f5c2804ef9c69442a2b7b3b3f1c2/vault/token_store.go#L1158-L1163

according to `SplitIDFromString` this function I think better restrict to use `.` in the token ID will be better

**Comment by ncabatoff** [comment]
Hi @vvelikodny, I'm sorry I forgot about this.  Could you resolve the conflict please, then I'll merge this?

**Pull request merged**
