### PR TITLE
fixed login link,request params,add json response

### PR DESCRIPTION
**Pull request by rajanadar**
1. fix login link
2. added personal access token to request message
3. added a sample json response

### CODE REVIEW

**Comment by jefferai** [comment]
It's not obvious but the login link is actually correct. The GitHub mount point does not have to be 'github'... so /login is the correct path on top of whatever the local mount point is.

**Comment by rajanadar** [comment]
right. but it maybe a consistency thing. all other auth backend docs mention login endpoint as 'auth/ldap/login', 'auth/app-id/login' etc. so the bare minimum, we could mention github in the same format as well.

additionally we could add a line to all auth backend login docs, that this mountpoint is variable. (which i think the users would be sort of aware of by now)

**Comment by rajanadar** [comment]
added a clarification line that the default mountpoint is shown in the url

**Comment by rajanadar** [comment]
if you still feel the original '/login' is clearer, let me know.. i'll revert that part.

**Comment by jefferai** [comment]
LGTM, thanks!

**Pull request merged**
