### PR TITLE
Write explicit -help output to stdout

### PR DESCRIPTION
**Pull request by cipherboy**
Per the consensus of most programs, and mirroring the GNU Coding Standards for CLI design, when users request `-help` explicitly via the CLI, this should be written to `stdout` to allow paging of output. `stderr` is (implicitly) fine when an invalid usage triggers the help text however.

In our case, `mitchellh/cli` helpfully adds a `HelpWriter` that we previously set to `stderr` explicitly. This writer is only called to print user-requested help text; it is not called on error cases (e.g., bad usage triggering additional help text to the user).

Thus it should safely be settable to `stdout`, enabling pagers without additional redirects and without affecting any user scripts relying on stdout not containing help text when bad usage occurs (or similarly, that stderr contains help when bad usage occurs).

See also: https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html
Resolves: #17004

`Signed-off-by: Alexander Scheel <alex.scheel@hashicorp.com>`

### CODE REVIEW

**Review by VioletHynes — APPROVED** [review]
Looks good! Thanks for this :)

**Review by dhuckins — COMMENTED** [review]
so if this was _just_ for `vault --help` would say OK, but in this case its not. if there's a bad command/arg, help is printed to stderr
eg:
`$ vault foo >stdout.txt 2>stderr.txt`
`$ cat stdout.txt. # empty`
`$ cat stderr.txt  # shows help`

that behavior is also consistent with gnu coreutils
```bash
# mac `ls` != gnu `ls`, using the latest ubuntu docker image here
$ ls --version
ls (GNU coreutils) 8.32
...
$  ls --foo >stdout.txt 2>stderr.txt
$ cat stdout.txt  # empty
$ cat stderr.txt
ls: unrecognized option '--foo'
Try 'ls --help' for more information.
```

also, this could potentially be a breaking change to some users:
if a user had a script that pipes the vault cli output to another program/process, would now need to read stdout instead of stderr to obtain the error info

**Comment by cipherboy** [comment]
@dhuckins Ah, I misread the initialization: 

https://github.com/mitchellh/cli/blob/25f4c7ceb617dfe9729b3ff32be02f7544ff7fb4/cli.go#L317-L322

I just need to provide `ErrorWriter` pointing back to the correct place and this is fixed, restoring the original behavior. See updated push.

**Comment by dhuckins** [comment]
> @dhuckins Ah, I misread the initialization:
> 
> https://github.com/mitchellh/cli/blob/25f4c7ceb617dfe9729b3ff32be02f7544ff7fb4/cli.go#L317-L322
> 
> I just need to provide `ErrorWriter` pointing back to the correct place and this is fixed, restoring the original behavior. See updated push.

```sh
$ vault foo > stdout.txt 2>stderr.txt
$ cat stdout.txt # empty
$ cat stderr.txt   # has expected help
```

lgtm! thanks for fixing @cipherboy

**Review by dhuckins — APPROVED** [review]

**Comment by cipherboy** [comment]
Thanks all! Merging for 1.13...

**Pull request merged**
