### PR TITLE
Add Yandex.Cloud KMS as the seal wrapping mechanism

### PR DESCRIPTION
**Pull request by AndreyZamyslov**
The changes add support for [Yandex.Cloud](https://cloud.yandex.com/) [KMS](https://cloud.yandex.com/docs/kms/) as the seal wrapping mechanism

### CODE REVIEW

**Comment by luc-lynx** [comment]
@jefferai Could you please take a look at the PR?

**Comment by AndreyZamyslov** [comment]
There are TestCassandraBackend test fail in 'ci/circleci: test-go-race' check.
But it looks like the test is not directly related to the changes made in this PR

**Comment by luc-lynx** [comment]
@vishalnayak could you please take a look at the PR?

**Comment by luc-lynx** [comment]
@mladlow Hello Meggie, our colleagues from Yandex suggested to ask for your help with this PR. Could you please take a look or suggest a reviewer for the PR?

The PR adds support for Yandex Cloud KMS and is aimed to facilitate usage of Hashicorp Vault in Yandex Cloud.

**Comment by suslovsergey** [comment]
Any news guys?

**Comment by suslovsergey** [comment]
Stop wasting time guys! Can any one to review this PR and merge?

**Comment by mladlow** [comment]
Hey @suslovsergey , @AndreyZamyslov , and @luc-lynx ,

We’ve done a preliminary review of the overall scope of this addition. We’ve determined that we’re unable to appropriately review the change, or subsequent updates to the seal wrapping mechanism. Even as a community-supported seal wrap, this change is too significant and creates too much risk for our team. Therefore, we’re going to close the PR.

I recognize that this PR represents a lot of effort on your part, and I’m sure this isn’t welcome news. Generally speaking, we recommend contributors open issues describing their planned changes before creating large PRs. This helps us give an indication of whether a proposed change might be too large for us to accept before a PR is created.

There is an effort underway in https://github.com/hashicorp/go-kms-wrapping to make KMS wrapping pluggable. I don't have a timetable for availability on this change, but when that functionality is available, this would be a good plugin point.

**Pull request closed without merging**
