### PR TITLE
Updates the k8s helm platform docs

### PR DESCRIPTION
**Pull request by burtlo**
To increase practitioner success with our products it felt important to provide updated content and links to learn resources. There are a number of guides now in the [Run Vault on Kubernetes](https://learn.hashicorp.com/vault?track=getting-started-k8s#getting-started-k8s) track. The new guides explore different features of running Vault with the Vault Helm chart. I also found that we failed to describe all the supported modes (adds `external` mode and `development` mode examples).

- Adds learn link to index pages
- Adds learn link to annotations docs
- Adds helm development example with learn link
- Adds helm external example with learn link 

### Run Page

- Updates to talk about the external mode
- Updates the helm install overview to show that the releases can also
  be the way to install
- Rewrites the how-to to include showing how to start in each mode
- Each mode that has a guide links off to a guide
- Re-organizes the Unseal and Init to a section and places all the
  various other unseals underneath it
- Moves updating below the unseal and init
- Shows some basic usage of the helm CLI with a value and file override

### CODE REVIEW

**Comment by burtlo** [comment]
The content for `stable-website` is different than `master`. Shou

**Comment by vishalnayak** [comment]
I think `https://github.com/hashicorp/vault/blob/master/website/data/docs-navigation.js` needs updating to add the new example pages. Can you verify that the changes reflect on the local version of the website? `cd website && make website`.

**Comment by burtlo** [comment]
I ran it locally `npm install && $(npm bin)/next dev`. Yes, that file needed to be updated. Index of examples displays the others. I respected the existing order of modes up top and other details below. It is not alphabetical and that feels wrong. Thoughts?

Also, `make website` failed for me. It was missing a module. 

```
$ make website
# ...
 error ] ./components/subnav/index.jsx
Module not found: Can't resolve '@hashicorp/react-subnav' in '/website/components/subnav'
{ Error: Cannot find module '/website/.next/server/static/development/pages/_document'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.loadComponents (/website/node_modules/next/dist/next-server/server/load-components.js:22:25)
    at DevServer.findPageComponents (/website/node_modules/next/dist/next-server/server/next-server.js:517:60)
    at DevServer.renderErrorToHTML (/website/node_modules/next/dist/next-server/server/next-server.js:754:33)
    at DevServer.renderErrorToHTML (/website/node_modules/next/dist/server/next-dev-server.js:15:862)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '/website/.next/server/static/development/pages/_document'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.loadComponents (/website/node_modules/next/dist/next-server/server/load-components.js:22:25)
    at DevServer.findPageComponents (/website/node_modules/next/dist/next-server/server/next-server.js:517:60)
    at DevServer.renderErrorToHTML (/website/node_modules/next/dist/next-server/server/next-server.js:754:33)
    at DevServer.renderErrorToHTML (/website/node_modules/next/dist/server/next-dev-server.js:15:862) code: 'MODULE_NOT_FOUND' }
```

**Comment by vishalnayak** [comment]
I don't think we need alphabetical order there.

**Pull request merged**
