### PR TITLE
Add 'pss_salt_length' parameter in transit/sign endpoint (#7531)

### PR DESCRIPTION
**Pull request by mbreban**

### CODE REVIEW

**Comment by jefferai** [comment]
I think this could be significantly simplified by passing the string value from the parameter into the sign function and doing a simple switch on the string value, without needing to define the constants and constant maps. Or, alternately, keep the map but map to the existing Go stdlib constants instead of redefining them locally.

I also think if this is being implemented we should accept a string number as well. So we check if the string is "auto" or "hash" and if it's not either we attempt to parse (a non empty string) as a number, and if successful use that as the length.

**Comment by mbreban** [comment]
Hello @jefferai
I fixed my previous PR.
Please let me know about the new implementation.

**Comment by jefferai** [comment]
I think it'd be better with a different type that can allow both integers and strings
 At this point though the CLA is outstanding so until that's signed I'm going to hold off on any further review.

**Comment by mbreban** [comment]
I did sign the CLA one month ago.

**Comment by jefferai** [comment]
Hmm it's showing here as not signed. I can ask someone to look into it. Could you also try it again just to be sure?

**Comment by chrishoffman** [comment]
When it is showing as not signed, it usually means the email attached to the commit does not match your github account.  It will require you to force push so that the history only shows the matching email address.

**Comment by jefferai** [comment]
Oh good point @chrishoffman , forgot about that

**Comment by mbreban** [comment]
Hi @jefferai,
By saying "_a different type that can allow both integers and strings_", do you mean using the interface type?
Should the function _pathSignWrite_ pre-process the data or should it be done only by the _Sign_ function?

**Comment by stevendpclark** [comment]
Hello @mbreban, thanks for the original contribution. I'm closing this PR out as it has been implemented and merged within #16549.

**Pull request closed without merging**
