### PR TITLE
Add support for context and add more documentation

### PR DESCRIPTION
**Pull request by sethvargo**
This PR adds support for Golang's [context.Context](https://golang.org/pkg/context) in the `api` package and also improves the API package documentation.

### CODE REVIEW

**Comment by jefferai** [comment]
I think this is a really great start! I don't want to add these to the public API as is though since we've been hamstrung in many cases by API calls taking in fixed parameters. With new API calls we usually require discrete types, and this is a good opportunity here if we are paralleling all existing calls to enforce this API wide.

**Comment by sethvargo** [comment]
Hey @jefferai 

I completely agree with you, _however_, the Go guide on context very specifically says that context should never be a struct member and should always be the first parameter to the function call.

**Comment by jefferai** [comment]
Right, it's the *rest* of the parameters that am I concerned about.

**Comment by sethvargo** [comment]
Ah okay - sorry. I misunderstood. Were you looking to adopt a pattern like I did in the Go Fastly lib where [each function has it's own "Input" struct](https://github.com/sethvargo/go-fastly/blob/master/fastly/director.go#L48-L79)?

**Comment by jefferai** [comment]
I haven't seen the Go Fastly lib but sounds similar, yeah.

**Pull request closed without merging**
