### PR TITLE
Added DataStax Astra DB as storage configuration

### PR DESCRIPTION
**Pull request by melienherrera**
**What Changed**
-Added "DataStax Astra DB" to [docs directory](https://www.vaultproject.io/docs/configuration/storage) "Configuration" -> "Storage" -> "DataStax Astra DB" 
-Added .mdx file with configuration steps

**Why?** 
-To add DataStax Astra DB in the documentation as a backend configuration
-To offer an additional option as an external storage dependency/backends

**Tested?**
-Tested locally

### CODE REVIEW

**Comment by melienherrera** [comment]
New commit - fixed broken link on[ Helm Chart Installation](https://www.vaultproject.io/docs/platform/k8s/helm) page. 

This [link](https://www.vaultproject.io/docs/platform/k8s/helm#:~:text=Please%20refer%20to%20the%20Helm%20documentation%20or%20the%20Vault%20Installation%20to%20Minikube%20via%20Helm%20tutorial.) took me to 404 error. Updated link to direct to this [page. ](https://learn.hashicorp.com/tutorials/vault/kubernetes-minikube-consul)

**Comment by melienherrera** [comment]
Hi there - just bumping this PR, if we can hopefully get this looked at.

**Comment by schavis** [comment]
@melienherrera Thank you for your contribution!

To get your plugin listed on the site, you should document its usage in the Github repo where you are maintaining the code and submit a [Plugin Submission Issue](https://github.com/hashicorp/vault/issues/new?assignees=&labels=ecosystem%2Fplugin&projects=&template=plugin-submission.md&title=%5BPlugin+Portal%5D+Plugin+Submission+-+%3CPLUGIN+NAME%3E) to get your offering added to the [Integrations page](https://developer.hashicorp.com/vault/integrations).

I'm happy to review the content and provide feedback if you would like, but we typically don't document community plugins directly in Vault documentation.

**Comment by melienherrera** [comment]
Hi @schavis thanks for taking a look at this even after some time. I have submitted a Plugin Submission Issue. Additionally, we have this documented on our Open Source Integrations page: https://awesome-astra.github.io/docs/pages/tools/integration/vault/#installation-and-setup

**Comment by schavis** [comment]
> I have submitted a Plugin Submission Issue. Additionally, we have this documented on our Open Source Integrations page: https://awesome-astra.github.io/docs/pages/tools/integration/vault/#installation-and-setup

Awesome, thank you :) Do you mind if I close the PR, or do you want to keep it open until the issue is resolved?

**Comment by melienherrera** [comment]
> 

I dont mind you closing the PR. I can follow the issue. Thank you!

**Comment by schavis** [comment]
Closing PR with permission from author

**Pull request closed without merging**
