### PR TITLE
remove needless import

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by sethvargo** [comment]
This LGTM, but I am going to defer to @mitchellh or @armon to merge since they worked on these most recently.

**Comment by armon** [comment]
This is actually an oddity of the SQL driver loading system in Go. Those imports appear useless, but it triggers their package `init` function which loads the drivers.

**Comment by mitchellh** [comment]
Yep, if you run the tests without the imports you'll see they fail, as well (acceptance tests)

**Comment by mattn** [comment]
Okay, but you have still mistake. https://github.com/hashicorp/vault/blob/master/builtin/logical/mysql/path_role_create.go#L9

**Comment by mitchellh** [comment]
Ah, yeah that one is probably not needed. It used to be. :)

**Comment by mattn** [comment]
you will fix it in your self soon, so i will not make PR. :)

**Comment by mitchellh** [comment]
Hah yes I'll grab this one. Thanks :)

**Pull request closed without merging**
