### PR TITLE
Update aws-sdk-go deps

### LINKED ISSUE #4721: "Failed to read seal configuration" errors after upgrading to 0.10.2
**Describe the bug**
After upgrading from 0.10.1 (or 0.10.0) to 0.10.2, vault produces the following errors:

```
[ERROR] core: failed to read seal configuration: error="UnmarshalTypeError: cannot unmarshal string into Go value of type []uint8"
[INFO ] core: security barrier not initialized 
```

**Environment:**
* Vault Server Version (retrieve with `vault status`): 0.10.2
* Vault CLI Version (retrieve with `vault version`): 0.10.2
* Server Operating System/Architecture: Alpine Linux 3.6 / Docker

Vault server configuration file(s):

```hcl
listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = "true"
  proxy_protocol_behavior = "use_always"
  proxy_protocol_authorized_addrs = "REDACTED"
}

storage "dynamodb" {
  ha_enabled      = "true"
  region          = "us-east-1"
  table           = "REDACTED"
  advertise_addr  = "REDACTED"
  recovery_mode   = 1
}

disable_mlock = "true"
ui = "true"
```

### LINKED ISSUE #4742: Bump AWS
Pull in a version of the dep containing https://github.com/aws/aws-sdk-go/pull/1978

### PR DESCRIPTION
**Pull request by kalafut**
Fixes #4721
Fixes #4742

### CODE REVIEW

**Comment by jefferai** [comment]
Watch this break something else. But, gotta do what we gotta do, unless we want to update *just* that package.

**Comment by kalafut** [comment]
Yeah it’s a lot of changes. I guess we have to consume it at some point, but maybe the big update can be done right after we stabilize 0.10.3 (or so) to maximize the time on it. I can rework to just get the one change in instead.

**Comment by jefferai** [comment]
Up to you -- I'd look at the surface of the change (if it's just your fixes, vs. a lot of others) because sometimes they have a lot of intermingled changes. If it's just yours though, might be worth cherry-picking and save the big update for post-0.10.3.

**Comment by kalafut** [comment]
I'm not comfortable taking in almost 70 changed files with just a few days testing. Fortunately, `govendor fetch` of just the affected package brings in only my change so there should be no cherry-picking required, nor broken coupling.

See PR #4744.

**Pull request closed without merging**
