### PR TITLE
[WIP] Add comment on FieldSchema Default usage

### PR DESCRIPTION
**Pull request by kalafut**

### CODE REVIEW

**Comment by michelvocks** [comment]
Do we still have to run `go mod vendor` manually when we change `sdk/` stuff?

**Comment by kalafut** [comment]
@michelvocks I think we've deemed it not necessary since we're telling people to build with go modules.

**Comment by jefferai** [comment]
While this is in many cases correct there's a lot of nuance.

For one thing, defaults being specified there can be valuable -- I would assume -- for OpenAPI, and potentially for some UI cases ("if you don't enter anything here, the default will be X").

The other is that not using Default is a double edged sword. While it means we can update what a not-set value is in a newer Vault release, it also means that us updating the value results in changed behavior for anyone who upgrades. So using the Default = possibly bad old behavior, but stable; not using it = possibly better new behavior, but unstable.

To some extent this may simply mean revisiting our pattern of GetOk followed by, if it's a create operation, Get. We use GetOk a lot now, which is great, and we don't _always_ do a Get on the value if it's a create operation -- we're inconsistent there. But I think there's room to say, we should specify what the default is at any given time in the schema (we could use a const value to keep it synced there and elsewhere in the code) while not necessarily persisting that value via a Get if it's not given. That way we can populate it in OpenAPI and the UI if desired but just leave things blank if not.

That obviously doesn't really address the potentially-breaking-upgrade-behavior issue but that's really something we generally need to think about on a case-by-case basis. I don't think a definitive answer either way addresses all possible needs.

**Comment by kalafut** [comment]
@jefferai Agreed. I wrote this after getting multiple questions about it from newer devs. But since I wrote it, I've been thinking a lot about our default handling and also our patterns for updating objects (i.e. roles) by individual member, and the current pattern of GetOk/req.Operation==Create/etc. I agree there is a more extensive discussion to be had here, and there's certainly no urgency to add this comment right now, though we should revisit the topic and decide on some guidance, both for the benefit of newer devs and for consistency.

**Comment by jefferai** [comment]
Sounds good. For the moment I advised Jason to add Default values into the schema for the JWT stuff he's doing so that it's documented, but he can choose whether or not to actually use it if GetOk doesn't return anything.

**Comment by jefferai** [comment]
FWIW generally I think the trend has been to _not_ use Get even on the Default value because it doesn't literally match what the user put in. So outside of a confusion factor, there's other issues, e.g. a Terraform factor ("what I put in isn't what came out"). So yeah, we should figure out the right pattern and stick to it (except when there are good reasons not to) but then this becomes a case of going through and trying to make things consistent.

**Comment by jefferai** [comment]
Although -- that was more an issue back in the day when we were using Get everywhere instead of GetOk.

**Comment by catsby** [comment]
Hey @kalafut - what's the status of this PR? It's been inactive for sometime, can we move towards a resolution of sorts?

**Comment by kalafut** [comment]
@catsby I'll reconcile the recommendations in a different forum than this PR. Thanks.

**Pull request closed without merging**
