### PR TITLE
Don't allow setting dead server last contact threshold to less than 1 minute

### PR DESCRIPTION
**Pull request by raskchanky**
This is a frequent source of problems when people tune their autopilot configs. I took a quick pass over the other autopilot config values and didn't see any that screamed for validation quite as much as this one, but if there are others that people think should be validated for some valid range of values, I'm happy to add those.

### CODE REVIEW

**Comment by msdundar** [comment]
I think in some pieces of official Vault documentation 10 seconds was in place, and I assume people simply adopted that. I believe a best-practices document or some kind of a guideline about autopilot flags could've been very useful as the difference between 1 minute and 24 hours (the default) for dead server last contact is still too big!

**Comment by msdundar** [comment]
@raskchanky I think in some pieces of official Vault documentation 10 seconds was in place, and I assume people simply adopted that. I believe a best-practices document or some kind of a guideline about autopilot flags could've been very useful as the difference between 1 minute and 24 hours (the default) for dead server last contact is still too big!

**Comment by raskchanky** [comment]
@msdundar I think you're probably right re: 10 seconds being somewhere in the official docs. I'll see if I can track it down. We designed the autopilot defaults to be appropriate for most use cases, so most of the time, tuning isn't necessary. I can see now that we don't mention that in our docs, however, and in fact, the language used could be easily interpreted to suggest that people should tune these. I appreciate you calling out these inconsistencies in our docs. I'll do my best to get them updated.

**Comment by msdundar** [comment]
If I'm not mistaken, it was [this tutorial](https://developer.hashicorp.com/vault/tutorials/raft/raft-autopilot#autopilot-configuration), and was the example right under the `Note` section. However, the example seems to be updated to 1m as well:

```
vault operator raft autopilot set-config \
    -dead-server-last-contact-threshold=1m \
    -server-stabilization-time=30 \
    -cleanup-dead-servers=true \
    -min-quorum=3
```

Many thanks for your quick reply and thanks for taking care of the minimum value! 🎉

**Pull request merged**
