### PR TITLE
Maximum number of retries aws sdk attempts for recoverable exceptions.

### PR DESCRIPTION
**Pull request by mohsen0**
Potentially this could be a configuration too, AWS defaultRetryer has a backoff logic for a set of recoverable exceptions.

Related issue: #3942 

https://github.com/hashicorp/vault/blob/master/vendor/github.com/aws/aws-sdk-go/aws/client/client.go#L59

### CODE REVIEW

**Comment by jefferai** [comment]
The SDK default is 3. 30 seems like a lot...

**Comment by jefferai** [comment]
I'm actually now a bit confused by the purpose of this PR. The original issue was for Vault to attempt to retry failed requests. But the code you linked to for the client suggests that it's already using a client default of 3 retries. The fact that it's still failing probably means it is an error that actually should be propagated back.

**Comment by mohsen0** [comment]
True, But there is an option in the SDK to increase the number since it is across all of the services. yeah, 30 is a lot, maybe 10 try?

**Comment by mohsen0** [comment]
Changed it to 10 try

**Comment by jefferai** [comment]
If you turn this into something that can be configured in both the credential and secrets backend I will consider it, but I'm not going to merge something that sets the value to an arbitrary non-default static number, especially given that this can already be done via env vars.

**Comment by mohsen0** [comment]
Thanks, I will look into that,
But before what variables you are referring too?

**Comment by jefferai** [comment]
I didn't refer to variables -- can you point out what you're asking about?

**Comment by mohsen0** [comment]
" especially given that this can already be done via env vars."

**Comment by jefferai** [comment]
Sorry, brain fart. I think I mixed up the aws.UseServiceDefaultRetries with aws.UseEnvDefaultRetries.

**Comment by mohsen0** [comment]
Can you have a look?

**Comment by jefferai** [comment]
The default for the parameter if not set by the user will be zero but this will actually disable retries. I think you want to use aws.UseServiceDefaultRetries as the default value for the field.

**Comment by mohsen0** [comment]
On other note, Noticed kops (the kubernete tool for aws), Hardcoded the value for this to 13. Using the same aws sdk.
But now, I understand this way solution is more elegant.
https://github.com/kubernetes/kops/blob/88984d4b477dbb59e124f0626e1cc23d9b5b0aef/upup/pkg/fi/cloudup/awsup/aws_cloud.go#L55

**Comment by mohsen0** [comment]
Updated the PR with the default value.

**Comment by joelthompson** [comment]
Adding my own $0.02 here, I'd like to echo what @jefferai said about 30 being excessive -- you'll really do yourself a favor if you track down what's causing all the excessive API traffic. Many things will be having these issues, not just Vault (and I speak from personal experience).

Also, having a retry count of 30 is probably counter-productive -- many people will just complain that Vault is "slow" under certain circumstances and either file impossible-to-track-down bugs or just stop using it. So, in most cases, it's probably better to actually fail out to let people know what's going on so they can correct it, rather than just constantly increase the retry count. 3 might be a bit low, but 30 is probably too high.

**Comment by mohsen0** [comment]
I agree I was just testing the waters with 30 :) , 30 is a lot, I have already looked into other possible causes too, but practically speaking with 3 retries backtracking functionality cannot do much.

**Comment by mohsen0** [comment]
Please let me know if anything else is required to be done by me,
Regarding the build failure, I started my branch from v0.9.3 tag, and I run the tests for each package but I can not figure out why the build is failing, it seems to unrelated to this change,

```
msarmadi@mac02474:[~/go/src/github.com/hashicorp/vault]: make test TEST=./builtin/logical/aws
==> Checking that code complies with gofmt requirements...
==> Checking that build is using go version >= 1.9.1...
go generate
ok  	github.com/hashicorp/vault/builtin/logical/aws	0.022s
msarmadi@mac02474:[~/go/src/github.com/hashicorp/vault]: make test TEST=./builtin/credential/aws
==> Checking that code complies with gofmt requirements...
==> Checking that build is using go version >= 1.9.1...
go generate
ok  	github.com/hashicorp/vault/builtin/credential/aws	0.531s```

**Comment by mohsen0** [comment]
Thanks for the help, all the checks have passed.

**Comment by jefferai** [comment]
Thanks!

**Comment by mohsen0** [comment]
When do you think we will have 0.9.4?

**Comment by jefferai** [comment]
Soon.

**Pull request merged**
