### PR TITLE
Add support for key rotation

### PR DESCRIPTION
**Pull request by armon**
This PR adds support for key rotation. This allows the master key to be changed as part of a "rekey" operation. During a rekey, the unseal configuration (number of shares, threshold of shares) can be modified. The encryption key which protects the storage backend can also be changed as part of a "rotate" operation.

Both of these can be done online, and in an HA configuration of Vault. The changes to the underlying files  are backwards compatible and Vault does an automatic upgrade of them.

### CODE REVIEW

**Comment by armon** [comment]
/cc: @abedra I'd love any feedback you have!

**Comment by boncheff** [comment]
I am looking forward to using this feature @armon

**Comment by abedra** [comment]
@armon just saw the notification. I will review today and make suggestions if I have them.

**Comment by armon** [comment]
@abedra Thanks!

**Comment by abedra** [comment]
Overall approach looks good. I had a couple of minor questions but am really happy to see this feature added. Will load it up over the next couple of days and test it out.

**Comment by armon** [comment]
@abedra Awesome, thanks for reviewing. The current approach does not actively re-write keys as they are accessed. The plan is instead to add a future "migrator" that at low QPS continuously scans and migrates all keys in the background.

**Pull request merged**
