### PR TITLE
Add OCI Auth Plugin

### PR DESCRIPTION
**Pull request by mauruthig**
Hello Vault, on behalf of Oracle Cloud Infrastructure, I am submitting the "OCI Auth Plugin" for Hashicorp Vault.

### CODE REVIEW

**Comment by malnick** [comment]
@mauruthig Thnank you for submitting this! A couple of things:

1. We'd like to break this into a separate repo, can you PR this code into https://github.com/hashicorp/vault-plugin-auth-oci?

2. Because Oracle provides HashiCorp with both a copyright and patent license to use the code that they contribute, the "all rights reserved" section of your copywrite header is not accurate. Can you update this to “Copyright © 2019, Oracle and/or its affiliates.”?

**Comment by vuhpham-oracle** [comment]
@malnick Jeff, I'll be working on update this PR.
1. I assume a PR for only files which have changes? Could you please clarify what specific code to PR https://github.com/hashicorp/vault-plugin-auth-oci? The reason for this question is this code is couple to vault project structure, it has some updates on tests, and existing files. I wonder why we want to have it in a separate repository?

2. We removed "all rights reserved" on latest commit. Could you double check on "Files changed" tab?

**Comment by malnick** [comment]
Thanks @vuhpham-oracle, the copyright headers look great!

As for why we want to move to a separate repo, we're trying to decouple the Vault core from the plugins overall. See https://github.com/hashicorp/vault-plugin-auth-kubernetes as an example.

**Comment by malnick** [comment]
Superseded by https://github.com/hashicorp/vault-plugin-auth-oci/pull/1

**Pull request closed without merging**
