### PR TITLE
Add support for polyhashing

### PR DESCRIPTION
**Pull request by LolalyLuo**
Hello,

We've implemented a polyhashing store as an option for initializing and unsealing Vault installations. You can read more on this [here](https://github.com/PolyPasswordHasher/PolyPasswordHasher/blob/master/academic-writeup/paper.pdf). We believe this is a good addition to ease rekeying and user interaction. As of now, the functionality is pretty raw, but we'd like your feedback on the following:

- [ ] Writing unit tests
- [ ] Updating the docs regarding this new feature
- [ ] Updating the interface in a way that makes more sense to you

Thanks!

### CODE REVIEW

**Comment by jefferai** [comment]
I understand the idea behind PolyHashPassword (I think) but I'm honestly not seeing the value it provides for Vault, other than potentially letting you know if an individual share is a valid share (which is not necessarily something we want to leak anyways); some of the other properties (such as not being able to perform verification without enough seeded entries) seem like drawbacks.

Can you explain in more detail what utility this provides -- how/why it modifies Vault's flow, what the security and/or UX benefits are, drawbacks, etc.?

**Comment by jefferai** [comment]
Hi @LolalyLuo ,

We've looked at the code and we've read the paper and we think that while the research is novel and interesting the applicability to Vault isn't straightforward. Unlike the hashed password case, Vault's master key is _already_ split with Shamir, and this is a part of its security stance. Adding a polyhashing layer on top adds extra complexity but it's not clear that it necessarily adds more security, and has some drawbacks like needing to see enough values supplied to fill its database (I might have the terminology there wrong, currently GitHub is refusing to load the paper) -- it seems like by the time enough values are provided, Vault would be unsealed.

We really appreciate the contribution, but for now we're not going to merge it. Thanks though!

**Comment by SantiagoTorres** [comment]
Hello @jefferai , sorry for the late reply. We were busy with other tasks we had for this project.

This PR stemmed from a talk we had with @armon almost a year ago. He encouraged us to submit to start a dicussion.

I understand the applicability (specially in terms of user interface) is not that straightforward. However, I think there are some benefits of adopting _polyhashing_ as an alternative:

1. It allows for easier secret rotation. Essentially, we get the chance to _dissociate_ shares from the information that's given to the user
2. From this, it is easier to revoke shares without needing to re-key the whole database
3. Although this may apply to passwords, it would be possible to use polyhashing to provide share-selectability (i.,e, the passwords are virtual shares that are assigned to the database).

I assume it'll have drawbacks too (e.g., the users could choose a low-entropy password), which we can discuss.

Again, sorry for the late reply, and I understand this seemingly came out of the blue. We'd like to continue the discussion on this though :)

**Comment by jefferai** [comment]
Hi @SantiagoTorres ,

One of the main issues is that it's not clear that the advantages outweigh the disadvantages. Bootstrapping is a problem, since it's a hard sell for us to switch to a mode (Isolated Validation) that theoretically can be more easily compromised.

We also currently have no issues with low-quality passwords, and I would prefer to avoid building in password validation rules. Right now it's on the key share holders to choose appropriate passwords for their password manager (where they are presumably storing their key); however, if that's where they store their polyhashing password, the attack surface is exactly the same anyways...but meanwhile someone brute forcing on Vault would potentially have e.g. a 10 character password (~80 bits) to brute force instead of 256 bits.

It's also not clear we want to revoke shares without rekeying for the same reason that we don't want to add shares without rekeying -- rekeying provides oversight, and that's good. You also don't run the risk of revoking too many shares accidentally and losing enough to meet threshold.

**Comment by SantiagoTorres** [comment]
Hi @jefferai, thanks for replying!

> One of the main issues is that it's not clear that the advantages outweigh the disadvantages. Bootstrapping is a problem, since it's a hard sell for us to switch to a mode (Isolated Validation) that theoretically can be more easily compromised.

Right, for the sake of this PR, we considered that Isolated Validation wouldn't be something Vault would benefit from. We are assuming that vault effectively bootstraps --- unsealing vault is pretty much the same process as bootstrapping. I think that this addition wouldn't stand in the way of HA and would actually benefit from it in the same way "vanilla" vault does.

> We also currently have no issues with low-quality passwords, and I would prefer to avoid building in password validation rules [...]

This is totally understandable. An alternative pathway is having the **server choose the "password" as a random string instead**. This approach would be different from what we proposed, but it may align more with your design choices. Entropy-wise there is no difference, and interface-wise the user wouldn't notice anything different (other than maybe having to specify a custom flag to enable this mode during `vault init`).

The benefit is that the token provided as a shard is in no way related to the secret. Administrators can't come together to recover the secret without interacting with the server. In a sense, the threat model is expanded from simple shard compromise to shard *and* server compromise. (this also assumes that an external storage system e.g., cassandra or so is already compromised  the actual sensitive information).

> It's also not clear we want to revoke shares without rekeying for the same reason that we don't want to add shares without rekeying -- rekeying provides oversight, and that's good. You also don't run the risk of revoking too many shares accidentally and losing enough to meet threshold.

Right, I see this is also the reason you guys didn't add code for full lagrange interpolation. I imagine with this other approach this would still stand, with the added benefit that a user whose shard must be revoked, will not know anything about the shard itself (e.g., in the case a backup is compromised, they must also compromise an old version of the polyhashing store to recover the shard). 

As a last benefit if we use this random string: we can stretch the tokens that are provided to the user using a load factor. Although bruteforcing a secret without knowing any shards is  unfeasible, it may be possible to do so when having *k - n* shares (if n is low). Stretching the shards may be something you'd like to do to avoid this scenario.

**Comment by jefferai** [comment]
OK, let me talk with the team internally.

**Comment by jefferai** [comment]
Going to reopen for now so as to not have this drop off my todo list.

**Comment by SantiagoTorres** [comment]
Great!

I'll also keep an eye on this PR to continue any discussion.

Thanks!

**Comment by jefferai** [comment]
As an update, I think the way we're leaning is to add the polyhash support, but with a number of changes from what's here (that mostly just remove a lot of the code here):

1) It should be the default, so any options to pass in polyhash passwords should go away; instead, random passwords (similar to the actual key shares now) should be generated and returned
2) Support needs to be added to recovery configs, not just barrier configs
3) Upgrades must be transparent -- current unseal keys work, on rekey it switches to polyhash scheme

We're still finalizing a "go" on this from everyone involved but I think by making this "more secure by default" instead of adding additional options, and not having the issues with Isolated Validation, it's a much easier sell :-)

**Comment by SantiagoTorres** [comment]
Great! 

I'll wait for the definitive go on this. In the meantime, we can start with easy tasks such as 1. and 2. on our side.

**Comment by jefferai** [comment]
@SantiagoTorres I'd hold off on any changes for the moment until things get decided on our end.

**Comment by jefferai** [comment]
Hi @SantiagoTorres ,

We're sort of struggling to understand how polyhashing, as would be used within Vault, provides extra security compared to the current system.

The reason is that, currently, even if key holders come together with key shares and derive the master key for Vault, this master key is only useful with a compromise of the underlying data store...decrypting the keyring, then using that to decrypt other values.

With polyhashing, the key holders can't derive the master key directly, but assuming that you have a threshold of compromised key holders, and assuming (like in the current case) a compromise of the underlying data store, an attacker that collects these polyhashed key shares simply runs them through the database -- which they'll have access to -- using some easily derived/open source code, and gets the master key.

Either way, you need a threshold of key holders and the underlying data store, but it doesn't seem like polyhashing changes the fundamental security model/stance, just adds an extra (but in this scenario trivially-defeated) step once all of the other requirements are met.

**Comment by SantiagoTorres** [comment]
Hi @jefferai, 

I just wanted to Ack on this. Let me write up a more grounded response (e..g, with examples) on this so we can be completely sure we are on the same page on the current threat model of Vault and the one after adding polyhashing.

Thanks!

**Comment by SantiagoTorres** [comment]
Hi @jefferai, 
      
I've spent some time reviewing my assumptions and the way that vault behaves. I realized that, for most of the production configurations, the addition that I'm proposing barely makes any difference. The encryption key to decrypt the barrier key is derived from the shards, and this configuration is stored in the database using the physical backends (i.e. in the database).

For the time being, I don't think it is reasonable to continue seeking this integration. We'll continue to explore other possibilities that may benefit Vault from Polyhashing, but I'd rather start a discussion over if that is to happen down the line with a more solid example/better examples.

**Comment by jefferai** [comment]
OK. Thanks though!

**Pull request closed without merging**
