### PR TITLE
Usability improvements for migrate command

### PR DESCRIPTION
**Pull request by jackkleeman**
I've just completed a Vault migration from C* to S3, and these are some changes I made to make this simpler:

1) Allow specification of path roots, instead of just migrating everything under /, you can select some specific folders like core. I didn't want to migrate `sys/expire/id` for example, so I set a root to `sys/policy/`.
2) Allow exclude paths. I wanted to exclude `logical/*/certs/*` as carrying across thousands of certs seemed pointless
3) Allow you to decide not to set a lock. I did the migration by starting a new cluster while the old cluster was running, and migrating workloads. I didn't want to touch the old storage at all.

If we're okay with these changes I will update docs :)

### CODE REVIEW

**Comment by kalafut** [comment]
Thanks. These seem like useful enhancements. There is some other work going on with parallelizing the process, so the review will be under the context that that PR lands.

**Comment by abdennour** [comment]
Are you coming from https://monzo.com/blog/migrating-vaults-storage-with-no-downtime ?

**Comment by jackkleeman** [comment]
Yes, I wrote that post!

**Comment by aphorise** [comment]
@ncabatoff @calvn assuming the merge conflict is resolved is there any reason why this PR could not be merged already? - I recall seeing threads related to a potential raw migrate sometime in the past and outside that simply allowing for exclusions by known entries / logical UID of mounts during migrate could be feasible?

**Comment by aphorise** [comment]
Hey folks - revisiting this & one thing that's seemingly missing is a documentation update to reflect this parameter - under:
 - [**Vault Documentation**: operator migrate](https://developer.hashicorp.com/vault/docs/commands/operator/migrate)

WDYT @jackkleeman? - can you kindly update the merge conflict too?

There's one additional use case I can I see for this feature - where at present there's no way to exclude paths (in either migrate or snapshots for example) then one can use this migrate approach to get some level of exclusion that's otherwise not possible by any other means.

**Comment by jackkleeman** [comment]
@aphorise hey, sorry four years later i dont really have the context to continue with this PR - if someone else would like to take on my changes, that'd be fine by me. going to close for now

**Pull request closed without merging**
