### PR TITLE
Consul require consistent

### PR DESCRIPTION
**Pull request by briankassouf**

### CODE REVIEW

**Comment by vishalnayak** [comment]
@briankassouf Can we update the doc with this option? (website/source/docs/config/index.html.md)

**Comment by briankassouf** [comment]
@vishalnayak added!

**Comment by jefferai** [comment]
It would be good to check with the Consul team if they think there may be more consistency modes in the future than the current three. If so may want to change this from a bool to a string with defined values. (I don't think this is likely but easier to check now than change later.)

**Comment by jefferai** [comment]
Also I am concerned that people seeing "require_consistent" will make bad assumptions about Consul not being consistent by default, even though that's not really the case. Maybe this should be "strong_consistency" instead.

**Comment by rcgenova** [comment]
Is the "stale" consistency mode something that we would absolutely rule out? There could be a read scalability advantage, but I guess you'd run the risk of getting a 403 on a read that occurs immediately after an auth. Docs state that "reads can be arbitrarily stale but are generally within 50 milliseconds of the leader".

**Comment by jefferai** [comment]
In talks about that with Armon (a long time ago, though) we both felt like that should be avoided. If it was 50ms then it'd be fine but the "arbitrary" part is potentially concerning.

I'm not against it per se but would be interested in seeing real world data to figure out likelihood. That said, it's a reason to maybe use strings now rather than change later.

**Comment by briankassouf** [comment]
Yeah I like the idea of switching to strings, it also will remedy the issue of the config name being imprecise.

**Pull request merged**
