### PR TITLE
MSSQL Provider - First cut at an mssql provider, ported from the mysql provider

### PR DESCRIPTION
**Pull request by worldspawn**
Full disclosure: I have no idea idea what I'm doing. I write c# in my day to day.

I've ported the mysql stuff to mssql mostly by searching for mysql and duplicating the file or adding new lines as appropriate. Passes the ./physical tests.

Haven't modded any docs/readmes.

MSSQL_ADDR can be `127.0.0.1` or `127.0.0.1,1433`

### CODE REVIEW

**Comment by armon** [comment]
@worldspawn Is the goal a MSSQL secret backend or storage backend or both? Since currently it is attempting to do both, but I'm not sure if that was the goal.

**Comment by armon** [comment]
@worldspawn There is still a lot here that is MySQL specific. There are subtle differences between the SQL commands to use that requires reading the MSDN docs closely to make the equivalent updates not yet done here.

**Comment by worldspawn** [comment]
Hi @armon - Yes thats the goal. 

The revoke/grant stuff I guess is still mysql. I think I forgot about it while trying to get the tests working. Tables should be created ok though. Frankly I'm not worried about getting the SQL right, it'll be easy enough. I just want to get the tests executing for so they are failing for bad-setup-dont-know-what-im-doing reasons so I can test the changes I make to the sql.

**Comment by jefferai** [comment]
I'm going to close this for now; if you continue work on it and it's ready for another look, please feel free to re-open or to open a new pull request.

**Pull request closed without merging**
