### PR TITLE
Clarify that Swift only supports v1.0 auth

### PR DESCRIPTION
**Pull request by bradjones1**
Re: https://github.com/hashicorp/vault/issues/2069

### CODE REVIEW

**Comment by jefferai** [comment]
The way this is worded makes it sound like there ought to be other variables for non-1.0 auth endpoints.

**Comment by bradjones1** [comment]
@jefferai I believe the Swarm library in the vendor directory supports v3 auth but it looks like the implementation in the Vault code is for v1; so I believe Vault would need to be updated to let the library decide, maybe. I'm not a Go developer so my review of the code was basic enough to get this far but I thought I would open a PR to at least start the conversation. I tried to see if I could find a repository for the Swift integration since the docs say it's "community maintained" but it looks like it's all in the main vault repo? Sorry I'm not in a position to be of more help improving the Swift backend.

**Comment by jefferai** [comment]
@bradjones1 I just meant that, literally, the change you made to the docs makes it seem to the reader like there are non-1.0 params:

> For Swift, the following options are supported for v1.0 auth endpoints:

vs. e.g. `For Swift, the following options are valid; only 1.0 auth endpoints are supported:`

**Comment by bradjones1** [comment]
@jefferai Good point; sorry for the confusion. I've updated per your feedback.

**Comment by jefferai** [comment]
Thanks!

**Pull request merged**
