### PR TITLE
[auth/gcp] Add missing permission to documentation

### PR DESCRIPTION
**Pull request by lawliet89**
Otherwise, Vault will return 500 due to 403 from Google API while trying to authenticate a GCE instance.

### CODE REVIEW

**Comment by tyrannosaurus-becks** [comment]
@emilymye hi! Would you be willing to take a quick peek at this?

**Comment by lawliet89** [comment]
For some context, before I added the `` permission to the custom role, I was getting this from Vault audit logs

```hcl
 {
auth: {
   token_type: "default"    
  }
  error: "googleapi: Error 403: The caller does not have permission, forbidden"   
  
request: {
   
data: {
    jwt: "hmac-sha256:<REDACED>"     
    role: "hmac-sha256:<REDACTED>"     
   }
   id: "16042703-1abe-7f5f-7d5b-e34bcae7b3d4"    
   
namespace: {
    id: "root"     
   }
   operation: "update"    
   path: "auth/gcp/login"    
   remote_address: "10.1.1.1"    
  }
  
response: {
  }
  type: "response"   
 }
```

**Comment by emilymye** [comment]
This is probably due to `add_group_aliases`, which was added later and requires an additional permission (https://github.com/hashicorp/vault-plugin-auth-gcp/blob/master/plugin/path_role.go#L83-L89). It might be better to instead document this under https://github.com/hashicorp/vault/blob/master/website/pages/docs/auth/gcp.mdx#group-aliases and mention this in the set-up as only required when using `add_group_aliases`

**Comment by lawliet89** [comment]
I have edited the text to mention that the permission is only required for group aliases.

**Pull request merged**
