### PR TITLE
Updates identity/group to allow updating a group by name (#10223)

### LINKED ISSUE #10223: Group-membership inconsistencies when using identity/group to remove member entities by group name
**Describe the bug**
Group-membership inconsistencies arise when using `identity/group` *by group name only* to remove member entities:
- The group reflects the new membership, with the entity missing.
- The entity shows that it is still a member of the group.

The result is that tokens for the entity are still granted the policies for the group.

**To Reproduce**

This script reproduces the behavior:
```bash
#!/bin/bash                                                                                                                                                                                                                                                                                                                  

readonly group_name=group-name
readonly token=devRootToken

function kill_vault {
    pkill -P $$
}
trap kill_vault EXIT

vault server -dev -dev-root-token-id="$token" >/dev/null 2>&1 &
sleep 1

function vault_api {
    local -r path="$1" ; shift
    curl -s -H "X-Vault-Token: $token" "$@" "http://localhost:8200/v1/$path"
}

function print_membership_info {
    echo -ne "\tgroup $group_id says members are:  "
    vault_api "identity/group/id/$group_id" | jq -c .data.member_entity_ids
    echo -ne "\tentity $entity_id says groups are:  "
    vault_api "identity/entity/id/$entity_id" | jq -c .data.group_ids
}

readonly entity_id="$(vault_api identity/entity -d'{}' | jq -r .data.id)"
readonly group_id="$(vault_api identity/group -d"{\"name\": \"$group_name\",\"member_entity_ids\":[\"$entity_id\"]}" | jq -r .data.id)"
echo "Initially:"
print_membership_info

vault_api identity/group -d"{\"name\": \"$group_name\", \"member_entity_ids\":[]}" >/dev/null
echo "After updating group $group_id to remove $entity_id using identity/group"
print_membership_info
```

The output will be something like:
```
Initially:
        group 3f174f6a-2f9f-933b-8352-a997ad1e01c7 says members are:  ["86a30c8d-54c6-f1aa-0e6d-c77e38379ab9"]
        entity 86a30c8d-54c6-f1aa-0e6d-c77e38379ab9 says groups are:  ["3f174f6a-2f9f-933b-8352-a997ad1e01c7"]
After updating group 3f174f6a-2f9f-933b-8352-a997ad1e01c7 to remove 86a30c8d-54c6-f1aa-0e6d-c77e38379ab9 using identity/group
        group 3f174f6a-2f9f-933b-8352-a997ad1e01c7 says members are:  []
        entity 86a30c8d-54c6-f1aa-0e6d-c77e38379ab9 says groups are:  ["3f174f6a-2f9f-933b-8352-a997ad1e01c7"]
```

**Expected behavior**

I expect the entity's list of groups to always be in sync with the group's list of members.  

**Environment:**
* Vault Server Version (retrieve with `vault status`):
```
$ vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.5.4
Cluster Name    vault-cluster-cac3084b
Cluster ID      d0383e61-ddb4-65d7-96a0-6256b52decf9
HA Enabled      false
```

* Vault CLI Version (retrieve with `vault version`):
```
$ vault version
Vault v1.5.5 (f5d1ddb3750e7c28e25036e1ef26a4c02379fc01)
```

* Server Operating System/Architecture:
```
$ cat /etc/os-release | grep VERSION=
VERSION="16.04.4 LTS (Xenial Xerus)"
```

* Vault server configuration file(s):

Default configs only.  Dev mode.

**Additional context**

This inconsistency does not arise when using `identity/group/name/$group_name` or `identity/group/id/$group_id` to remove the entity from the group, so the "fix" in our case is just to use a different endpoint, but I think it's important to clarify (and possibly fix) the behavior of the endpoint in question when used in this way.  It's true that the documentation for `identity/group` only promises to update an existing group if the ID is given, but if the ID is not given -- and the name matches the name of an existing group -- the behavior is not specified in the documentation.  The most obvious possibilities seem to be:

- **Vault returns an error (4xx):**  Vault could complain that that endpoint can only update existing groups by ID and that updates by name for existing groups should be done by `identity/group/name/$group_name`.  It's not clear that that's desirable behavior, and anyway it's not what Vault is actually doing.
- **Vault updates the group by name:**  Vault could choose to update the group by name, which may be what the caller wants.  Vault's current behavior seems to be to do so, but only partially, since it's updating the group itself but not cascading the change down to the removed entity.  If Vault is changed to fully perform the update by name for existing groups via this endpoint, the documentation should be updated to clarify the behavior.

In any case, it seems that Vault should never behave in a way that results in the mismatch between the entity and the group.  The result in our case was that the entity was still getting policies for the group, despite the group thinking the entity was no longer a member, leading to entities maintaining access to secrets for which we thought access had been revoked.

### PR DESCRIPTION
**Pull request by dr-db**
Fixes #10223.

### CODE REVIEW

**Comment by dr-db** [comment]
The new test I wrote passes (for me), but I had a hard time figuring out whether I broke other tests, because they seem to be failing even on `master` right now, as far as I could tell.

**Review by mgritter — COMMENTED** [review]
The fix and test look good.

There are a couple changes I would like.

One thing that has to be changed (due to the length of time this PR has been open, sorry) is that the documentation has changed location, from website/pages to website/content.

The other problem is that the root cause of the bug should be addressed, which is that in `handleGroupUpdateCommon` this code handles lookup by name succeeding when lookup by ID does not:

```
               groupByName, err := i.MemDBGroupByName(ctx, groupName, false)
               ....
                case group.ID == "":
                        group = groupByName
```

The problem here is that `groupByName` is the "original" object still in the memory database, so any modification --- like altering the entity list -- is done in-place and bypasses update of the index.  The working code paths all make a copy and modify that copy.

So, with the change you made, we can remove that case of the switch statement and have the only way to modify a group by name is to look it up before calling `handleGroupUpdateCommon`.

**Comment by mgritter** [comment]
I will create a new PR using yours as the base (as I don't assume you're still actively working on this.) For more on the root cause, see https://github.com/hashicorp/go-memdb/issues/76

**Comment by mgritter** [comment]
New PR: https://github.com/hashicorp/vault/pull/10812

**Pull request closed without merging**
