### PR TITLE
Allow almost all leagal LDAP DNs to be used

### PR DESCRIPTION
**Pull request by bluecmd**
Implement LDAP escaping according to RFC 4514 to allow complex LDAP usernames/groups to be used.

Leaving ASN BER encoded values unsupported for now.

### CODE REVIEW

**Comment by bluecmd** [comment]
This is the first step to solve https://github.com/hashicorp/vault/issues/347

**Comment by bluecmd** [comment]
Since https://github.com/go-ldap/ldap/pull/19 is now merged I added group parsing as well.

**Comment by bluecmd** [comment]
The CI fails because I have no idea how to run "godep save ./..." on vault. For some reason it wants to remove aws-sdk-go//internal/apierr and Travis doesn't like that.

**Comment by armon** [comment]
LGTM! Thanks! Sorry about delay, I was on vacation.

**Comment by armon** [comment]
Fixed by #347

**Comment by armon** [comment]
This got merged in c81262332798e5139b4e862affe5fc5a0bc97ef8, had to do it manually because of conflict

**Comment by bluecmd** [comment]
Cool! But, ehum, that removed my authorship of the commit. Not sure that's 100% kosher.
Please make sure my commit is intact. I'd be happy to help you resolve the conflict instead.

**Comment by armon** [comment]
Hmm I'm not sure why it didn't just treat it as a merge commit like normal. I'm not sure how to change it now.

**Comment by bluecmd** [comment]
*sigh* Oh well. Since the easiest way I can think of is to revert the commit and commit it again I guess I'll have to be pragmatic and let it go. My nickname is in the branch-name at least so I guess that's some form of authorship.

Anyway, thanks again for merging!

**Comment by armon** [comment]
@bluecmd Apologies, I didn't mean to scrub your authorship. @sethvargo is trying to fix it, and has more git-fu than me

**Comment by sethvargo** [comment]
@bluecmd https://github.com/hashicorp/vault/pull/379

**Pull request closed without merging**
