### PR TITLE
gofmt -w -r 'interface{} -> any' .

### PR DESCRIPTION
**Pull request by sashamelentyev**

### CODE REVIEW

**Comment by hsimon-hashicorp** [comment]
At 635 files changed, this is an enormous PR. May I ask what your reasoning is behind this? Thanks!

**Comment by sashamelentyev** [comment]
Just use any type instead of empty interface. Replace all empty interface to any in one PR. If this problem - i can split PR

**Comment by hsimon-hashicorp** [comment]
If this is simply a stylistic choice, we are not likely to accept or merge this PR. The scope of the PR itself can be dangerous, and this change does not seem necessary. Is there a rationale behind replacing the empty interfaces?

**Comment by sashamelentyev** [comment]
Under hood any equivalent to empty interface.
https://github.com/golang/go/blob/master/src/builtin/builtin.go#L95
Rationale - code looks cleaner and takes up less space

**Comment by hsimon-hashicorp** [comment]
We're grateful for your time and effort, however we won't be able to accept this PR at this time. In general, we tend to prefer to make large-scale refactor changes within the Vault engineering team directly. Also, this change appears to require Go 1.18+ and thus would break backports to previous versions. As I said, we definitely appreciate your concern here, and we'll look at updating our code for readability and conciseness on an on-going basis. :)

**Pull request closed without merging**
