### PR TITLE
website: restrict node engines to <= 16.x

### PR DESCRIPTION
**Pull request by BRKalow**
Restrict the node engines declaration for the website so it only uses up to 16.x.

### CODE REVIEW

**Review by thiskevinwang — APPROVED** [review]
Note: adding this due to new [Node 18 availability ](https://vercel.com/changelog/node-js-18-lts-is-now-available)

**Review by ccapurso — APPROVED** [review]
Looks good, thanks!

**Comment by BRKalow** [comment]
@ccapurso I'll need you to merge this when it's ready as I don't have permissions 🙏

**Comment by ccapurso** [comment]
@BRKalow, enabling auto-merge which will go through unless `main` changes in the process.

**Pull request merged**
