### PR TITLE
Add sb extract to enable Storybook composition

### PR DESCRIPTION
**Pull request by amyrlam**
This enables Vault Storybook to be seen on https://github.com/hashicorp/design-system-website/blob/main/taskbox/.storybook/main.js#L25

Ref: hashicorp/cloud-ui#1457 and https://github.com/hashicorp/design-system-website/blob/main/taskbox/.storybook/main.js

### CODE REVIEW

**Comment by amyrlam** [comment]
Tagged Vault frontends for review 

@didoo @Dhaulagiri please update the URL in `design-system-website` if this is merged while I'm out

**Comment by amyrlam** [comment]
@hashishaw Hey, I'm back! Possible to merge this in? I don't have authorization to merge. Please let me know!

**Comment by hashishaw** [comment]
welcome back @amyrlam! Merged, thank you!

**Comment by amyrlam** [comment]
thanks!

**Pull request merged**
