### PR TITLE
Correct bolt write time

### PR DESCRIPTION
**Pull request by raskchanky**
As @maxb mentioned on https://github.com/hashicorp/vault/pull/22097 the fact that this metric is a total and not per write means it should be a gauge, not a summary. This corrects that in the code as well as the docs.

While I was in there, I noticed that the way we're getting transaction stats is actually [deprecated in the bolt library](https://pkg.go.dev/go.etcd.io/bbolt#TxStats), so I updated everything to use the new functions.

### CODE REVIEW

**Comment by schavis** [comment]
Content update LGTM. Feel free to merge once an ENG reviewer signs off on the other changes

**Review by schavis — APPROVED** [review]

**Review by hghaf099 — APPROVED** [review]
LGTM

**Comment by banks** [comment]
Thanks for fixing this Josh. 

I think it should probably be a counter though not a gauge. Gauges are for numbers that go both up and down in general like "number of things connected". This is actually a counter counting how many microseconds we have spent writing to disk cumulatively.

In practice the main way the metric is useful would be by treating it as a counter (like you do for say requests serviced, or CPU time elapsed) and then taking a rate (or irate) to produce a utilisation metric of "number of seconds per second spent writing" where 1 would indicate 100% utlisation and 0 would indicate no utilsation in that sample period. It _might_ be possible to do the same as a gauge but I think the semantic is really a counter - for example you don't expect that graph to be reset every time you restart (rates on counters genreally correct for counter resets while gauges do not).

What do you think?

This is also kind of a breaking change to our metrics which is fine if it goes out in a major release but might be worth a mention in the upgrade notes. It's minor and I doubt will impact many folks so not a show stopper but I'd lean towards a mention there since it could break peoples dashboards if they were using this metric in some way (never mind that it was probably meaningless before whatever they were trying to do with it).

**Comment by raskchanky** [comment]
@banks Thanks for pointing this out, as I'm definitely no metrics expert. I didn't realize counters were something you could set values of in increments of more than 1, but it looks like go-metrics does let you do that. TIL. I'm happy to change it if you think that's more appropriate and put something in the upgrade notes too.

**Pull request merged**
