### PR TITLE
Renew Lease was not respecting Age Header from Cache

### PR DESCRIPTION
**Pull request by Freyert**
### What
https://github.com/hashicorp/vault/issues/16439 identified that occasionally the Vault Agent Template server would wake up at the incorrect time to renew leased credentials.

I believe I've identified a potential root cause which is that the Vault API library was not accounting for the `Age` header returned from the cache. Without accounting for cache `Age` template servers will work from the original TTL from the cached renew request instead of the true aged TTL.

### How
This change checks the renew request for an Age header and adjusts the TTL accordingly.

### Why
The Vault Agent Cache inserts an `Age` header based on the time the original response was received from the Vault Server ([source](https://github.com/hashicorp/vault/blob/main/command/agent/cache/lease_cache.go#L205)).

This can be used to calculate an approximation of the "true" remaining TTL. (However, imagine a worst case scenario you have several layer of caches then you could potentially see a large error between the Server TTL and the final cache's TTL. It may be better in the future to rely on a "valid_until" strategy, but that has its own problems and is far outside the scope of this issue.)

LifeTimeWatcher's [`doRenew`](https://github.com/hashicorp/vault/blob/76165052e54f884ed0aa2caa496083dc84ad1c19/api/lifetime_watcher.go#L239-L251) uses [`client.Sys().Renew`](https://github.com/hashicorp/vault/blob/9c6d25ad1627d8309cf58c0128ba33119c3c80d6/api/lifetime_watcher.go#L249) which "encapsulates" the Renew API call. This interface currently drops vital information regarding the `Age` header, but modifying the interface to return an age along with the secret would be a large change requiring effort by downstream library users.

Handling `Age` inside `client.Sys().Renew` enforces the _expected_ behavior without breaking the interface.

fixes: https://github.com/hashicorp/vault/issues/16439

### CODE REVIEW

**Comment by Freyert** [comment]
Another approach could be to have the Cache update the TTL before forwarding.

**Comment by hsimon-hashicorp** [comment]
Hi there! Please don't forget to include a [changelog entry](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md#changelog-entries). :)

**Comment by Freyert** [comment]
@hsimon-hashicorp CHANGELOG uploaded! Thank you for inspecting the PR. 🤞 everything goes well.

**Comment by Freyert** [comment]
Hmmm, this might not be the best way to fix this problem.

Ultimately, _any_ request could be cached and have an `Age` header. This only covers the case where someone calls `cache: received request: method=PUT path=/v1/sys/leases/renew`.

If a Client `reads` a secret for the first time it will also not be aware that there is an `Age` header.

Here are some alternatives:


* Parse the secret and adjust the TTL whenever pulling it from the Cache.
  * Would cause a lot more garbage collection to parse, modify, re-serialize.
  * Potentially more modifications exist which would be beneficial to perform when fetching an item from the cache.
* ParseSecret ingests an entire request, including headers and manages the TTL - Age modification
  * Requires touching a lot of code, but reduces garbage collection issues by only doing parsing/modification when necessary.

**Comment by Freyert** [comment]
This isn't the right approach. We need to make the api package cache conscious.

It's probably best to follow HTTP Cache semantics instead of rolling a different solution. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Pull request closed without merging**
