### PR TITLE
Handpick cluster cipher suites when they're not user-set

### PR DESCRIPTION
**Pull request by jefferai**
There is an undocumented way for users to choose cluster cipher suites
but for the most part this is to paper over the fact that there are
undesirable suites in TLS 1.2.

If not explicitly set, have the set of cipher suites for the cluster
port come from a hand-picked list; either the allowed TLS 1.3 set (for
forwards compatibility) or the three identical ones for TLS 1.2.

The 1.2 suites have been supported in Go until at least as far back as
Go 1.9 from two years ago. As a result in cases where no specific suites
have been chosen this _ought_ to have no compatibility issues.

Also includes a useful test script.

### CODE REVIEW

**Comment by kalafut** [comment]
I'm a little confused by the test script output. With or without `cluster_cipher_suites` configured, I get 11 YES's, including stuff like `DES-CBC3-SHA` that isn't in the list.

**Comment by jefferai** [comment]
I checked it into `scripts/` just in case it's useful later since I found it useful as a quick verifier. I figured curl could just dump the cipher preferences from the server but didn't see how, so that's what I found. I didn't intend it as an automated test. Happy to remove it.

You just start a Vault cluster and hit it against the cluster port (e.g. `-dev-ha`). Probably @kalafut is hitting the API port.

**Comment by kalafut** [comment]
@jefferai Haven't rechecked but yeah that's gotta be it re: the API port. I'm good with the script being checked in. I found it interesting/useful.

**Comment by jefferai** [comment]
Merging -- comments were around the script not the actual functionality.

**Pull request merged**
