### PR TITLE
Renew the semaphore key periodically

### PR DESCRIPTION
**Pull request by tsilen**
The semaphore key is used to determine whether we are the leader or not and is set to expire after TTL of 15 seconds. There was no logic implemented to renew the key before it expired, which caused the leader to step down and change every 15 seconds. A periodic timer is now added to update the key every 5 seconds to renew the TTL.

### CODE REVIEW

**Comment by jefferai** [comment]
Thanks for this, this will solve some problems reported on the mailing list. Looks pretty good overall -- one comment. Since the channel is closed directly before any return from the function, I'd prefer to see the close happen in a (simple anonymous) deferred function. That way any future logic added doesn't need to remember to properly close the channel. If you could do that and test it, that would be fantastic.

Thanks!

**Comment by tsilen** [comment]
The channel is actually only closed on failure cases, the function returns it on success. But let's see if it can be made cleaner somehow.

**Comment by jefferai** [comment]
I looked at your most recent code and it looks good, with you assigning to err. The even easier way to do it is to name the return error variable. Then you can either `return foo, errSomething` or `return bar, nil`, or you can simply assign to it directly (if you assign to both, you can simply "return").

That way, you don't need to worry about accidentally redeclaring err at some point later with `:=`; whatever is returned, you can access it by name within the closure.

**Comment by tsilen** [comment]
Thanks! Makes sense. I made the change, seems to work well.

**Comment by jefferai** [comment]
Looks great, one small request: there are other places in the function where `err` is used. Can you simply name the returned error something like `retErr` to make sure that it's always clear which error variable is being assigned to?

After you do that, I'm happy to merge.

Thanks!

**Comment by tsilen** [comment]
Yep, that's changed now, too.

**Comment by jefferai** [comment]
Awesome. Thanks!!!!!

**Pull request merged**
