### PR TITLE
Return parameter warnings even if the response otherwise has no content

### PR DESCRIPTION
**Pull request by maxb**
A few versions ago, Vault implemented warnings (which get displayed by
the CLI) when a user attempts to pass a parameter to a Vault endpoint,
that the endpoint is not expecting. That's great, it leads users to
discover failures to read the docs correctly with much less pain.

However, I've just discovered that this feature gets silently turned off
if the response being generated is nil, which would translate to an HTTP
204 No Content response. This is surprising, as the user gets no
feedback that one of the usual feedback methods for mistakes has been
contextually disabled.

This change conditionally promotes the response to a real JSON response
when it is necessary to include parameter warnings.

Having done so, I then discover that cubbyhole writes were then all
generating warnings, as the relevant `TakesArbitraryInput` flag had not
been set on that endpoint - so fix that too. A similar fix will be
needed for KV v1 as well. (I'll create that PR too.)

### CODE REVIEW

**Comment by averche** [comment]
I like this change for the overall UX but I do have a concern:

Would we be returning a `200` response in case a warning is issued (in place of a `204`)? I'm wondering if this may break backwards compatibility assumptions. It seems OK since technically the request does not recognize the fields and issues a warning, but still...

P.S. There are a few tests that are currently failing (expecting a nil response, likely the requests have redundant fields).

**Comment by maxb** [comment]
> Would we be returning a `200` response in case a warning is issued (in place of a `204`)?

Yes, we would - this is something Vault already does for other warnings - on the fly promotes the `204` to a `200` if it has warnings to return.

Example:

```
$ vault write auth/approle/role/foo token_type=service
Success! Data written to: auth/approle/role/foo
```
(that's how the CLI handles a 204)

But change the parameter to something it dislikes and...

```
$ vault write auth/approle/role/foo token_type=default-service
WARNING! The following warnings were returned from Vault:

  * default-service has no useful meaning; adjusting to service
```

now we get a 200 to convey the warning.

> I'm wondering if this may break backwards compatibility assumptions.

It is a concern to some extent, but there is existing precedent, and it would only come into effect if the user was _actually sending an incorrect parameter_ to the API.



> P.S. There are a few tests that are currently failing (expecting a nil response, likely the requests have redundant fields).

Oops. I keep doing this... changing something I do not think the tests should be enforcing and then being surprised...

**Comment by maxb** [comment]
Oh dear... rather more concerningly, it turns out that with this, Vault will also promote a `404 Not Found` to a `200 OK` if there are warnings to return :facepalm:. I will correct that...

**Comment by maxb** [comment]
I'm moving this back to draft status. As I explore the problem, I realise it's a huge can of worms, which I should write up as several issues.

I'm thinking it might be worth considering moving warnings out of the JSON body entirely, and instead handling them by introducing `X-Vault-Warning` headers.

This would decouple the ability to return warnings from details of the operation involved, and is the only way we could accomodate warnings an all requests, including `DELETE` requests and ones that have been defined to return a `404 Not Found`.

**Comment by averche** [comment]
> I'm thinking it might be worth considering moving warnings out of the JSON body entirely, and instead handling them by introducing X-Vault-Warning headers.

That's an interesting idea but I wonder if it could break some of the existing workflows.

**Comment by maxb** [comment]
Potential scope of this PR has grown beyond what is reasonable - I'm going to close it, and if I manage to get back to this topic at some point in the future, will break it up into multiple PRs.

**Pull request closed without merging**
