### PR TITLE
Vault 3268 update go version

### PR DESCRIPTION
**Pull request by pmmukh**
- Updates go versions as needed, based on steps https://docs.google.com/document/d/16sjIk3hzFDPyY5A9ncxTZV_9gnpYSF1_Vx6UA1iiwgI/edit#bookmark=id.82xjf6b7po1e / https://hashicorp.atlassian.net/wiki/spaces/VAULT/pages/1717011010/The+Vault+Release+Procedure
- Updates sdk version to the one in https://github.com/hashicorp/vault/pull/12406

### CODE REVIEW

**Review by swayne275 — COMMENTED** [review]
i think you want to at least also update Dockerfile.ui

**Comment by swayne275** [comment]
and go.mod and sdk/go.mod. see step e here: https://docs.google.com/document/d/16sjIk3hzFDPyY5A9ncxTZV_9gnpYSF1_Vx6UA1iiwgI/edit#bookmark=id.82xjf6b7po1e

**Comment by raskchanky** [comment]
https://hashicorp.atlassian.net/wiki/spaces/VAULT/pages/1717011010/The+Vault+Release+Procedure also has a pretty complete list of places to update.

**Comment by pmmukh** [comment]
@swayne275 thanks for the catches! I'll be updating the Dockerfile.ui, missed that. For the go.mods though, it looks like we don't have a minor version of go there, so it's only go1.15 https://github.com/hashicorp/vault/blob/release/1.7.x/go.mod#L3. Also on the doc, nick mentions we shouldn't be updating sdk/go.mod, I'm not really clear on whether we should or not but the go version there seems to be 2 major versions older rn, so not sure if I should be touching it https://github.com/hashicorp/vault/blob/release/1.7.x/sdk/go.mod#L3
also cc @raskchanky

**Comment by swayne275** [comment]
@pmmukh i'm not 100% sure about the sdk/go.mod either, but the comment that I read was it isn't necessary for 1.8+ (and this is 1.7)

re the regular go.mod - is there no minor version because we don't do that, or because maybe it was last updated when go 1.15 came out and we hadn't done it since?

**Comment by pmmukh** [comment]
@swayne275 ahh that may be, about the sdk/go.mod change being reqd before 1.8, I'm not sure.
Regarding maintaining minor versions on either go.mod file, I don't think that's ever been done actually, cause I was looking at older release branches like https://github.com/hashicorp/vault/blob/release/1.4.x/sdk/go.mod, and I'm not seeing minor versions of go anywhere.

**Comment by swayne275** [comment]
@pmmukh i just looked it up. the go directive in the mod file is only really relevant for compatibility purposes. since patch versions don't change compatibility, it shouldn't matter (though this isn't explicityly stated). i'll update the doc

**Comment by pmmukh** [comment]
aha, that makes sense, thanks for looking it up and the doc change @swayne275 !

**Review by ncabatoff — APPROVED** [review]

**Review by swayne275 — APPROVED** [review]

**Pull request merged**
