### PR TITLE
Let lifetime watcher retry until end of lease

### PR DESCRIPTION
**Pull request by andrejvanderzee**
This pull request retries renewals on error until the end of the lease (minus grace), instead of abruptly restarting the lifetime watcher (and revoking tokens/secrets as a result). 

The problem is described in detail here: https://github.com/hashicorp/vault/issues/10918.

@ncabatoff

### CODE REVIEW

**Comment by andrejvanderzee** [comment]
@ncabatoff Any change that someone can look at this? We do have a production problem and our current workaround is a rolling restart of all our k8s production deployments every week, just to make sure we do not run into this vault-agent sidecar edge-case. This MR makes vault agents more resilient against temporary problems not being able to renew leases of tokens and secrets.

**Comment by andrejvanderzee** [comment]
@ncabatoff  @jefferai 

Can someone please take a look at this Vault Agent resilience issue? Our workaround now is doing rolling upgrades of all our Kubernetes deployments when it nears the TTL of the vault token. Insane.

The current implementation of `func (r *LifetimeWatcher) doRenew() error` is just not OK, I hope you can acknowledge that? 

I think the whole `doRenew()` requires a proper refactoring, but this PR at least makes Vault Agent more resilient with a patch on the _error/problem-path_ only, which causes vault token and secrets to be unnecessarily renewed to soon!

**Comment by andrejvanderzee** [comment]
@ncabatoff  @jefferai 

Can someone please take a look at this Vault Agent resilience issue? Our workaround now is doing rolling upgrades of all our Kubernetes deployments when it nears the TTL of the vault token. Insane.

The current implementation of `func (r *LifetimeWatcher) doRenew() error` is just not OK, I hope you can acknowledge that? 

I think the whole `doRenew()` requires a proper refactoring, but this PR at least makes Vault Agent more resilient with a patch on the _error/problem-path_ only, which causes vault token and secrets to be unnecessarily renewed to soon!

**Comment by andrejvanderzee** [comment]
@ncabatoff @jefferai 

Ping...

**Comment by andrejvanderzee** [comment]
@ncabatoff @jefferai

Any chance that this will be picked up?

**Comment by ncabatoff** [comment]
Hey @andrejvanderzee,

I'm sorry to have left you hanging for so long.  I've added a story to the current sprint to tackle this issue.  I think this PR is on the right track, though I would like to see some tests.  Maybe factor out the first bit of doRenew so that we can provide our own artificial renewFunc when testing.  Would you like to work on those, or shall I?

**Comment by andrejvanderzee** [comment]
Hi @ncabatoff, no problem at all, we are just very happy that it is being picked up now, as it occasionally is causing problems in our prd environments. I won't have much time, so if you could add the tests that would be wonderful :-) 

As a side note: To mitigate the problem, we put VAULT_MAX_TRIES on 12. The problem with this approach is that every common error will end up in a "context deadline exceeded", because retrying is handled inside the Vault client and after 12 retries you exceed  VAULT_CLIENT_TIMEOUT. 

Thanks for putting this in your sprint :-)

**Comment by ncabatoff** [comment]
Closing this in favour of #11445.

**Pull request closed without merging**
