### PR TITLE
Added TOTP MFA

### PR DESCRIPTION
**Pull request by m-massaro**
Added an implementation of the OATH TOTP algorithm based on RFC 6238 and RFC 4226.
It uses SHA1 as default hashing algorithm.
The implementation is not ready to use though, we were not able to add this new method alongside the existing one (Duo MFA) and we had to replace the MFAPaths and MFARootPaths (line 28 and 35 on helper/mfa/totp/mfa.go)

### CODE REVIEW

**Comment by jefferai** [comment]
Hi @m-massaro ,

Thanks for contributing this! We will probably need to wait on it a bit -- we are going to be revamping the backend APIs in 0.5-0.6 and along with that will probably come major changes to MFA, because we'd like to have it supportable in all backends. I'm not yet sure exactly what that will look like, but I'm marking this as "future" so that this doesn't get lost/forgotten about.

**Comment by ctchurch** [comment]
We're interested in having this functionality.  What is the status of merging it in now that 0.6 is out?

**Comment by jefferai** [comment]
@ctchurch We have some very big plans around this type of functionality but they're still a bit out, because we have more core work to do first. This PR in and of itself likely won't be merged; as the OP noted, it's incompatible with the existing implementation for Duo.

**Comment by sethvargo** [comment]
Hi there,

Thank you for the PR, and sorry this sat for so long. This is available as of Vault 0.7.1: https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#071-may-5th-2017

https://www.vaultproject.io/docs/secrets/totp/index.html

**Pull request closed without merging**
