### PR TITLE
docs: Document environment variables

### PR DESCRIPTION
**Pull request by mfischer-zd**
I'm not sure how to generate tables using your doc generator, but hopefully this will work.

### CODE REVIEW

**Comment by jefferai** [comment]
Thanks for this. Can you add VAULT_TOKEN?

**Comment by mfischer-zd** [comment]
Sure, will do.

**Comment by mfischer-zd** [comment]
Done, ready for review.

**Comment by vishalnayak** [comment]
@mfischer-zd These changes will not be reflected until there is an entry in website/source/layouts/docs.erb

**Comment by mfischer-zd** [comment]
@vishalnayak updated per your feedback

**Comment by jefferai** [comment]
Great...thank you!

**Pull request merged**
