### PR TITLE
UI: update link-to-external 

### PR DESCRIPTION
**Pull request by hellobontempo**

### CODE REVIEW

**Review by zofskeez — APPROVED** [review]
Thanks for catching this! This should have been picked up by `ember-template-lint` since the [no-curly-component-invocation](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-curly-component-invocation.md#no-curly-component-invocation) rule is a part of the recommended config. I'll try and find out what the issue is with that for the future.

**Comment by zofskeez** [comment]
> I'll try and find out what the issue is with that for the future.

After further thought, because `link-to-external` was invoked with positional parameters the linter would have recognized it as a helper and not triggered the rule. Adding that component to the `disallow` array for the rule in `.template-lintrc` should trigger the rule for the future.

**Comment by zofskeez** [comment]
The [docs](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-curly-component-invocation.md#examples) are maybe a bit misleading and it seems that regardless of adding a component to `disallow` it will not identify curly invocation with positional params other than `link-to`.

**Comment by hellobontempo** [comment]
> no-curly-component-invocation

This is confusing...

Thanks for taking a look!

**Pull request merged**
