### PR TITLE
Update OIDC docs for Azure AD

### PR DESCRIPTION
**Pull request by janbrunrasmussen**
Based on my experience documented in this issue https://github.com/hashicorp/vault/issues/6494, and encouraged by @kalafut, I am adding some documentation for using the OIDC auth method with Azure AD. I have not put it in bullet form, since it does not cover every single necessary step, and I did not want to take up too much space on the page.

Please let me know if it follows the spirit of the docs and if I need to update/change/expand something.

### CODE REVIEW

**Comment by kalafut** [comment]
@stenio123 I know you’ve been documenting some of this elsewhere. Care to take a look?

**Comment by stenio123** [comment]
Thank you for the invite! I was actually working on the Google integration, added an example to https://github.com/hashicorp/vault-guides/tree/master/identity/oidc-auth. 

The instructions for Azure look fine and I appreciate greater clarity, my only concern is since this is documenting the requirements for an external service, what happens if Azure changes the way it manages its identity settings? Do we have any process to ensure references to external resources are kept up-to-date?

Having said that, I still think that greater clarity trumps future concerns, so personally I like having the Azure requirements documented.

**Comment by janbrunrasmussen** [comment]
I can move it to demo like documentation here as well if you prefer? https://github.com/hashicorp/vault-guides/tree/master/identity/oidc-auth

**Comment by kalafut** [comment]
I think it's fine here. This page is intended to be a collection of tips for getting a provider set up for those already working through docs/api. Terse is fine, and I expect plenty of community edits because they'll be the first to catch when something is off for some provider. Guides and other tutorials have a different format and goal.

**Comment by kalafut** [comment]
Thanks!

**Comment by drivard** [comment]
Hi guys, I am trying to setup the OIDC auth method following this documentation but I can't figure out what is the error I am doing. I documented all the steps I followed [here](https://stackoverflow.com/questions/60006916/hashicorp-vault-oidc-auth-method-with-azure-ad-error-validating-signature) could you please help.

**Pull request merged**
