### PR TITLE
Don't exit just because we think there was a possible deadlock

### PR DESCRIPTION
**Pull request by ncabatoff**
Fixes https://github.com/hashicorp/vault/issues/21338

### CODE REVIEW

**Review by VioletHynes — APPROVED** [review]
Makes sense to me, we don't want to be crashing Vault for users because of potential deadlocks.

I'm not too sure how we could write an elegant test for this behaviour, since we'd need to wait for 30s, but this is something that our existing tests missed. It's something we should think about adding some kinds of tests for, at least.

**Review by banks — COMMENTED** [review]
I attempted to verify that this _probably_ does what we expect I didn't test manually but based on [reading the source code](https://github.com/sasha-s/go-deadlock/blob/00ee193ea4a32e0dea6c837f4fa6416c12242cc8/deadlock.go#L39) for the library it does indeed seem to be the change we want.

I think this looks like a less risky position to take for now. We can decide later based on occurences of the log messages whether it would be better to allow users to opt in/out of the crash behaviour and/or modify the timeout.

**Review by banks — APPROVED** [review]
Forgot to approve

**Comment by ncabatoff** [comment]
Manual 1.11 backport: https://github.com/hashicorp/vault/pull/21350
Manual 1.12 backport: https://github.com/hashicorp/vault/pull/21349

**Pull request merged**
