### PR TITLE
Bump etcd client api dep

### LINKED ISSUE #4349: Vault with etcd backend storage with multiple adresses uses only the first server's ServerName for all endpoints, generating bad cert tls error on etcd side
**Environment:**

* Vault Version: Vault v0.10.0 ('5dd7f25f5c4b541f2da62d70075b6f82771a650d')
* Etcd Version: v3.3.3
* Operating System/Architecture: Ubuntu 16.04/x86

**Vault Config File:**

```hcl
storage "etcd" {
  address = "https://etcd-0.example.com:2379,https://etcd-1.example.com:2379,https://etcd-2.example.com:2379"
  etcd_api = "v3"
  ha_enabled = "true"
  path = "vault/"
  tls_ca_file = "/etcd/rootCA.crt"
  tls_cert_file = "/etcd/client.crt"
  tls_key_file = "/etcd/client.key"  
}

listener "tcp" {
 address     = "127.0.0.1:8200"
 tls_disable = "true"
}

api_addr = "http://127.0.0.1:8200"
cluster_addr = "http://127.0.0.1:8201"
```

**Startup Log Output:**

```
==> Vault server configuration:

             Api Address: http://127.0.0.1:8200
                     Cgo: disabled
         Cluster Address: https://127.0.0.1:8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", tls: "disabled")
               Log Level: debug
                   Mlock: supported: true, enabled: true
                 Storage: etcd (HA available)
                 Version: Vault v0.10.0
             Version Sha: 5dd7f25f5c4b541f2da62d70075b6f82771a650d

==> Vault server started! Log data will stream in below:

2018-04-13T16:15:52.200+0700 [DEBUG] storage.cache: creating LRU cache: size=0
2018-04-13T16:15:52.208+0700 [DEBUG] cluster listener addresses synthesized: cluster_addresses=[127.0.0.1:8201]
```

**Expected Behavior:**

All the etcd endpoints don't throw tls error and accept the connection

**Actual Behavior:**

Two last etcd endpoints thrown tls error, stating bad certificate, thus rejecting them.
I suspect that this is because Vault sends request to them using the first server's (etcd-0) server name.

**Sample etcd error logs: (from etcd-1. etcd-2 showed the same error)**
```
2018-04-13 08:01:50.267438 I | embed: rejected connection from "10.10.145.64:32946" (error "remote error: tls: bad certificate", ServerName "etcd-0.example.com")
2018-04-13 08:05:30.852145 I | embed: rejected connection from "10.10.145.64:33136" (error "remote error: tls: bad certificate", ServerName "etcd-0.example.com")
2018-04-13 08:05:30.932451 I | embed: rejected connection from "10.10.145.64:33144" (error "remote error: tls: bad certificate", ServerName "etcd-0.example.com")
```

**Steps to Reproduce:**

- Create an etcd cluster of three endpoints with client-tls enabled
- Implement vault with etcd backend storage with multiple endpoints
- Start up the server
- See the etcd error

### LINKED ISSUE #4961: Vault is inaccessible if an etcd unit is lost
**Describe the bug**
When vault is deployed in a cluster, using etcd for HA management, losing the first etcd unit in the 'address' list results in vault returning 500s 

**To Reproduce**
- Deploy 3 units of vault. In my test case use 1 mysql unit for storage and 3 units of etcd for ha_storage.
- Initialise and unseal vault and validate API with "vault status"
- Shutdown the etcd unit that corresponds to the first IP in the 'address' list (in the 'ha_storage "etcd" ' section)
- Run "vault status" with VAULT_ADDR pointing at any of the vault units

```$ vault status
Error checking leader status: Error making API request.

URL: GET http://10.53.82.200:8200/v1/sys/leader
Code: 500. Errors:

* context deadline exceeded
```

**Expected behavior**
I would expect vault to continue to function and respond to API requests, without interruption, in the event of losing an etcd unit. 

**Environment:**
* Vault Server Version: 0.10.3
* Vault Client Version: 0.10.1
* Server OS: Ubuntu 16.04.5 (Xenial) x86_64

Vault server configuration file(s):

```hcl
api_addr = "http://10.53.82.113:8200"
cluster_addr = "http://10.53.82.113:8201"
disable_mlock = true
storage "mysql" {
  username = "vault"
  password = "kpzLkcjfmX9w45n542zwLyrJBppfg5rP"
  database = "vault"
  address = "10.53.82.226:3306"
}
ha_storage "etcd" {
  ha_enabled = "true"
  address = "https://10.53.82.119:2379,https://10.53.82.150:2379,https://10.53.82.157:2379"
  tls_ca_file = "/var/snap/vault/common/etcd-ca.pem"
  tls_cert_file = "/var/snap/vault/common/etcd-cert.pem"
  tls_key_file = "/var/snap/vault/common/etcd.key"
  etcd_api = "v3"
}
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

# Localhost only listener for charm access to vault.
listener "tcp" {
  address = "127.0.0.1:8220"
  tls_disable = 1
}
```

**Additional context**

On the active vault unit the following entries appear in its log when the etcd unit goes down:

```
2018-07-20T08:24:16.614Z [WARN ] core: leadership lost, stopping active operation
2018-07-20T08:24:16.614Z [INFO ] core: pre-seal teardown starting
2018-07-20T08:24:16.614Z [INFO ] core: stopping cluster listeners
2018-07-20T08:24:16.614Z [INFO ] core: shutting down forwarding rpc listeners
2018-07-20T08:24:16.614Z [INFO ] core: forwarding rpc listeners stopped
2018-07-20T08:24:16.907Z [INFO ] core: rpc listeners successfully shut down
2018-07-20T08:24:16.907Z [INFO ] core: cluster listeners successfully shut down
2018-07-20T08:24:16.907Z [INFO ] rollback: stopping rollback manager
2018-07-20T08:24:16.908Z [INFO ] core: pre-seal teardown complete
```

The standby vault units do not log anything as a result of the lost etcd unit.

### LINKED ISSUE #7582: Taking around 20mins after loosing leader when one etcd is down intermittently.
**Describe the bug**
etcd 3.3.15 cluster has 3 nodes
vault in HA mode, has 3 nodes

**To Reproduce**
1. deploying 3 etcd nodes and 3 vault nodes,
2. confirmed that vault secrets list -detailed is working.
3. shutdown one etcd node(most likely the first one in endpoints list)

then vault command is not working properly with below error
context deadline exceeded
or
local node not active but active cluster node not found

**Expected behavior**
there could be error but it should be back online soon

**Environment:**
* Vault Server Version (retrieve with `vault status`):
upstream with etcd 3.4 dependency
upstream with etcd 3.3.15
upstream without modification
* Vault CLI Version (retrieve with `vault version`):
Vault v1.1.1 (cgo)
* Server Operating System/Architecture:
Ubuntu 18.04.3 x86_64

Vault server configuration file(s):

```hcl
# Paste your Vault config here.
# Be sure to scrub any sensitive values

api_addr = "http://10.0.0.8:8200"
cluster_addr = "http://10.0.0.8:8201"
storage "mysql" {
  username = "vault"
  password = "6qSmBLJBCtXG4kdhXSq9zn9PjKtNJKgH"
  database = "vault"
  address = "10.0.0.6:3306"
}
ha_storage "etcd" {
  ha_enabled = "true"
  address = "https://10.0.0.4:2379,https://10.0.0.5:2379,https://10.0.0.7:2379"
  tls_ca_file = "/var/snap/vault/common/etcd-ca.pem"
  tls_cert_file = "/var/snap/vault/common/etcd-cert.pem"
  tls_key_file = "/var/snap/vault/common/etcd.key"
  etcd_api = "v3"
}
listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

# Localhost only listener for charm access to vault.
listener "tcp" {
  address = "127.0.0.1:8220"
  tls_disable = 1

```

**Additional context**

I inserted println to analyze, I found out when etcd node is down,
vault leader lose leader and it is back after around 20mins

all vault nodes has c.standby = true for 20mins. then vault command is not working properly.

### LINKED ISSUE #7931: Support for etcd 3.4
**Is your feature request related to a problem? Please describe.**
Hashicorp Vault 1.3.0 can't connect to Etcd storage backend if Etcd version is 3.4.x.

**Describe the solution you'd like**
Add support for Etcd version 3.4 as a storage backend.

**Additional context**
Error message from my case:
`“vault: Error initializing storage of type etcd: failed to check etcd status: client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint.”`

### PR DESCRIPTION
**Pull request by michelvocks**
Fixes #4961
Fixes #4349
Fixes #7931
Fixes #7582
Related PR: https://github.com/hashicorp/vault/pull/7403

This PR bumps the version of the etcd client SDK to V3.4.3 (2019-10-24) which requires additional dependency updates to `google.golang.org/api` and other.

This PR has been successfully tested against a 3-node etcd cluster (V3.3.18).

### CODE REVIEW

**Comment by jefferai** [comment]
The only two things I think you need to run here are
```
go get github.com/hashicorp/vault-plugin-secrets-gcp@master
go get go.etcd.io/etcd@3cf2f69b5738fb702ba1a935590f36b52b18979b
```
Which for me results in a pretty minimal and reasonable diff.

**Comment by michelvocks** [comment]
> The only two things I think you need to run here are
> 
> ```
> go get github.com/hashicorp/vault-plugin-secrets-gcp@master
> go get go.etcd.io/etcd@3cf2f69b5738fb702ba1a935590f36b52b18979b
> ```
> 
> Which for me results in a pretty minimal and reasonable diff.

I started with `go get -u go.etcd.io/etcd@v3.4.3` which apparently produces a complete different output. :confounded:

Thanks tho!

**Comment by jefferai** [comment]
Don't use `-u` with go modules, it doesn't work the way you think it does. :-)

**Comment by michelvocks** [comment]
@catsby Thanks. Fixed.

**Comment by michelvocks** [comment]
@catsby @jefferai Would be great to get another look on this to avoid additional future rebases.

**Comment by jefferai** [comment]
What version of Go are you using?

**Comment by jefferai** [comment]
I forgot about the GCP bit up above. That fixes/explains that issue. I still have differences though -- I am guessing that is due to Go 1.13.x vs 1.12?

**Comment by michelvocks** [comment]
> I forgot about the GCP bit up above. That fixes/explains that issue. I still have differences though -- I am guessing that is due to Go 1.13.x vs 1.12?

Yes, I was still using go 1.12.7. I upgraded to 1.13.6 and reran the go mod commands.

**Comment by jefferai** [comment]
That looks better but I think you forgot to run `go mod tidy` :-)

**Comment by michelvocks** [comment]
Now with `go mod tidy`.

**Comment by michelvocks** [comment]
Rebased. @jefferai @catsby

**Pull request merged**
