### PR TITLE
Basic Auth support for Etcd

### LINKED ISSUE #859: Add basic auth to etcd
It would be great to support Basic Auth Information in the etcd backend for security. Implementation should be trivial by allowing configuration values for Username and Password and feeding it to the etcd client.

### PR DESCRIPTION
**Pull request by wikiwi**
Fixes #859.

This PR adds Basic Auth support for Etcd. Implementation is straight forward. It introduces two configuration variables: `username` and `password`, which is passed to the Etcd client.

### CODE REVIEW

**Comment by wikiwi** [comment]
Can we add Environment Variable support for this?
Something like:
ETCD_USERNAME
ETCD_PASSWORD
I'm more than glad to add it to the PR.

**Comment by wikiwi** [comment]
Added fallback to Environment Variables to PR. I will modify or remove it upon request.

**Comment by jefferai** [comment]
Thanks for submitting this! It looks good with one change: the preference order we usually use is config file < environment variables < command line flags. So can you flip the logic such that it looks in config for each value if the environment variable is empty?

**Comment by wikiwi** [comment]
I took the behavior directly from the s3.go implementation: https://github.com/hashicorp/vault/blob/master/physical/s3.go#L54-L57

I will flip the logic, I prefer that order too.

**Comment by wikiwi** [comment]
Updated PR with flipped logic.

**Comment by jefferai** [comment]
Ah, thanks for pointing that out -- I will change the S3 behavior for 0.5.

**Comment by jefferai** [comment]
LGTM -- thanks!

**Pull request merged**
