### PR TITLE
Load-balanced etcd support

### PR DESCRIPTION
**Pull request by emk**
Some etcd configurations (such as that provided by compose.io) place the etcd cluster behind multiple load balancers or proxies.  In this configuration, calling Sync (or AutoSync) on the etcd client will replace the load balancer addresses with the underlying etcd server address.

This will cause the etcd client to bypass the load balancers, and may cause the connection to fail completely if the etcd servers are protected by a firewall.

This PR provides a "sync" option for the etcd backend, which defaults to the current behavior, but which can be used to turn off of sync. This corresponds to `etcdctl`'s `--no-sync` option.

This PR also documents the existing "username" and "password" options.

### CODE REVIEW

**Comment by jefferai** [comment]
@emk Isn't this simply fixed by providing the right values to etcd? See https://github.com/coreos/etcd/issues/2734#issuecomment-95336706

**Comment by emk** [comment]
It's a little hard to tell, actually.

The `etcdctl` client provides a `--no-sync` flag to get this exact behavior, and the support team at compose.io has confirmed that this is the only way to actually make things work:

> Hi!
> 
> This is related to `--no-sync` option in etcdctl (as you correctly suspected). In our etcd architecture we provide 2 entry points to the etcd cluster (called portals) and the remaining members communicate with each other over private network. That's why you need make sure disable node discovery with `--no-sync` option in your client implementation. You can see the details of the cluster on app.compose.io/{URL REDACTED} and that our command line script example uses `--no-sync` option, too.
> 
> Let us know if you have any further questions or concerns.

It's entirely possible that there's another way to solve this problem, but disabling sync is required to operate with at least one major hosted `etcd` vendor. So it might be reasonable to offer something equivalent to the `etcdctl` flag `--no-sync` in Vault's etcd backend.

**Comment by emk** [comment]
Anyway, thank you for looking at this, and if you think the right answer is for me to argue with compose.io support, I'm happy to try. :-)

**Comment by jefferai** [comment]
I'll take a look at this tomorrow... I think the right answer is probably "both" :-)

**Comment by jefferai** [comment]
Hi @emk 

It looks good, but I wonder if it would be better, rather than having it be a bool, to have it be a tri-state string (default "no", supports "yes" and "auto") so that the "auto" behavior can be supported. What do you think?

**Comment by emk** [comment]
Yeah, I tried to design it so that it could support "true", "false" and "auto" at a future date. But I'm happy to try to figure out how to enable `AutoSync` and use whichever set of values your prefer. 

I do feel that the default should be either "yes" or "auto" for three reasons:

1. The existing etcd backend defaults to "yes," and it might be nice to preserve backwards compatibility.
2. Most people running their own vault without a load balancer setup will probably want to sync.
3. The `etcdctl` client defaults to syncing but allows it to be turned off.

So even though our use case requires "no", it might not be the best default.

**Comment by jefferai** [comment]
Sorry, my mistake -- I meant default "yes". I just mixed up which was the current default -- I agree we shouldn't change it.

I think if you don't want to figure out AutoSync now that's fine -- but I'd make it a string option so that it's easy to enable in the future, rather than changing the semantics of a boolean option...which would still accept "yes" and "no" but if people had put "true" or "false" or "1" or "0" it might break compatibility.

**Comment by emk** [comment]
OK, I'll try to tackle this either later today or tomorrow.

**Comment by jefferai** [comment]
@emk Hi there...any update?

**Comment by jefferai** [comment]
I'm going to merge this and convert the option to a string, so that auto can be done in the future.

**Comment by emk** [comment]
My apologies! I was busy with a bunch of other stuff, and didn't see your ping. Thank you very much for going ahead and merging this.

We're using an S3 storage backend (to simplify regulatory stuff) with compose.io-hosted etcd for leader elections, and it appears to be working nicely. This is definitely a user-friendly setup for first-time H/A vault users.

Once again, my aplogies for the slow reply, and my thanks for a great project!

**Comment by jefferai** [comment]
No problem! I merged it and changed it to a string, so if you get around to "auto" support later it's ready.

**Pull request merged**
