### PR TITLE
adding prometheus info to make more self-service

### PR DESCRIPTION
**Pull request by mikegreen**
Based on customer feedback, adding entire job_name example for prometheus

### CODE REVIEW

**Comment by ncabatoff** [comment]
This looks good, but I imagine most users have TLS setup, do you want to give an example for that as well, e.g.

```
scrape_configs:
- job_name: vault
  metrics_path: /v1/sys/metrics
  scheme: https
  params:
    format: [prometheus]
  tls_config:
    ca_file: ca.pem
  bearer_token: %s
  static_configs:
  - targets:
    - '%s'
```

Just showing the structure here, your example is better overall.

**Comment by mikegreen** [comment]
Good idea. Added.

**Comment by mikegreen** [comment]
Agree on those. 
I'll make separate issues for those to track and get to them next week.
https://github.com/hashicorp/vault/issues/8352

**Comment by ncabatoff** [comment]
Sorry, finally getting back to this.  One last request before I merge it: looking at the preview, it seems a bit funny to have the text starting with "Vault does not use the default Prometheus path" indented.  It almost makes it look like it's associated with the `disable_hostname` telemetry option.  If you scroll down to the Stackdriver section you can see there a paragraph following bullets that isn't indented ("It is recommended to also enable the option..."), which looks more natural to me.

**Comment by ncabatoff** [comment]
Thanks!

**Pull request merged**
