### PR TITLE
Split Changelog into Smaller Files

### PR DESCRIPTION
**Pull request by ltcarbonell**
Trims the changelog to the N-2 latest versions to that it is able to be rendered on Github

### CODE REVIEW

**Comment by maxb** [comment]
@ltcarbonell Although it would be really nice to trim the main changelog, this change as is would greatly hinder viewing past information, as the changelogs in those tags are **not consistently up to date** with the information on the main branch!!

(It would also be necessary to dance around from one Git ref to another to look when a change happened.)

Perhaps instead, simply breaking the changelog up into a few files all kept in main would be a simpler and more useful change? i.e.

* CHANGELOG.md
* CHANGELOG-pre-v1.1.md
* CHANGELOG-pre-v1.12.md

roughly implementing a policy of starting a new volume every 4000 lines or so.

**Comment by ltcarbonell** [comment]
> @ltcarbonell Although it would be really nice to trim the main changelog, this change as is would greatly hinder viewing past information, as the changelogs in those tags are **not consistently up to date** with the information on the main branch!!
> 
> (It would also be necessary to dance around from one Git ref to another to look when a change happened.)
> 
> Perhaps instead, simply breaking the changelog up into a few files all kept in main would be a simpler and more useful change? i.e.
> 
> * CHANGELOG.md
> * CHANGELOG-pre-v1.1.md
> * CHANGELOG-pre-v1.12.md
> 
> roughly implementing a policy of starting a new volume every 4000 lines or so.

@maxb I tend to agree with the sentiment (and it is something we have discussed a bit internally as well).  Ideally we want to find a balance between _too_ much and _too_ little information on these.  I like the idea of simply breaking it up, since that will help maintain search-ability as well.

**Review by mladlow — COMMENTED** [review]
Would it be possible to add a "Previous versions" section to the top of the changelog.md file that links to these earlier changelog files?

**Review by mladlow — APPROVED** [review]
Thanks for taking care of this @ltcarbonell - it's a big improvement!

**Pull request merged**
