### PR TITLE
Adds support for sending audit logs to Apache Kafka

### PR DESCRIPTION
**Pull request by Mongey**
Adds support for sending audit logs to [Apache Kafka](https://kafka.apache.org).

This can make it easier to get audit logs into different systems for analysis. 

🙈 Lots of dependancies

### CODE REVIEW

**Comment by jefferai** [comment]
Just as an FYI, we have some pretty major changes planned for the audit system in a few releases from now, so we may not merge this until that lands and this can be adapted.

**Comment by Mongey** [comment]
NP, thanks for letting me know @jefferai

**Comment by VioletHynes** [comment]
Hey there! I realize that it has been some time since you submitted this PR, and I apologize for the delay. Obviously, there are a lot of merge conflicts for this PR to be resolved before it can be merged.

Notably also, the vendor folder approach is outdated, now, and go modules solve the version freezing problem. We're open to supporting this use case, but there's quite a lot of work to be done to get this PR into a mergeable state.

We've been making a substantial update to the audit log system, to enable future enhancements, that may affect this PR. 

I wanted to let you know that if you're still interested in implementing this, then we're open to it, but also I understand that this might require a lot of rework, so if that's too much, or if the need for this feature has gone by now, we understand. Thanks a bunch for the contribution so far!

**Comment by hsimon-hashicorp** [comment]
Due to the age of the PR and @VioletHynes's comments, I think it might be best to close this PR and open a new one if you're still interested in this functionality. Thanks, and apologies for the rather long delay!

**Pull request closed without merging**
