### PR TITLE
Add full CA Chain to /pki/cert/ca_chain response

### PR DESCRIPTION
**Pull request by cipherboy**
As mentioned in #13489, calls to read `/pki/cert/ca_chain` would return a partial chain, excluding the root authority. By adding a new field, `ca_chain` to the response, we can include the entire chain without breaking backwards compatibility.

We test three main scenarios:
    
 1. A root-only CA's `/cert/ca_chain`'s `.data.ca_chain` field should contain only the root,
 2. An intermediate CA (with root provide) should contain both the root and the intermediate.
 3. An external (e.g., `/config/ca`-provided) CA with both root and intermediate should contain both certs.

n.b.: I think the existing note around `ca_chain` in the documentation is wrong, hence its removal. 

Additional note: this is only the full chain as _known to Vault_. If the entire (from a TLS client's PoV) chain wasn't provided during either `/intermediate/set-signed` or `/config/ca`, Vault wouldn't know the entire chain and thus couldn't provided. That'd be an enhancement for the future.

### CODE REVIEW

**Review by kitography — COMMENTED** [review]
This looks good to me.

**Review by kitography — APPROVED** [review]
Actually approving this time.  Looks good to me :)

**Review by divyapola5 — APPROVED** [review]

**Review by stevendpclark — COMMENTED** [review]
Code looks great 👍  

I would just like to see an update to the "Read CA Certificate Chain" api docs to mention if they want the full CA Certificate chain it is available within the "Read Certificate" api with the ca_chain parameter...

**Comment by cipherboy** [comment]
Thanks @stevendpclark, I've added a note -- let me know if that seems right?

**Review by stevendpclark — APPROVED** [review]

**Pull request merged**
