### PR TITLE
WIP: Passthrough request headers

### PR DESCRIPTION
**Pull request by greysond**
Implementation of #3509, using audited-headers as a template.

This allows, through configuration, the passing of specific request headers to specific paths. 

Please let me know if anything looks awry, as this is my first time contributing to this project.

Thanks!

### CODE REVIEW

**Comment by jefferai** [comment]
Closing for now. #3509 was stalled for a reason, as we were deciding what we wanted the API to look like.

**Comment by jefferai** [comment]
Thanks though!

**Comment by jefferai** [comment]
@joelthompson FYI in case you want to coordinate.

**Comment by jefferai** [comment]
@greysond The person that was going to work on this won't be able to. If you're interested in picking this up we can chat about how we want it to work.

**Comment by greysond** [comment]
Absolutely!

**Comment by greysond** [comment]
Is there a good place for me to read up on what the desired functionality is? Is there a community hashicorp or vault Slack?

I have some free time today, so I'd love to get started on it.

**Comment by jefferai** [comment]
@greysond Sorry about not getting back to you, your reply got buried in email which I was ignoring due to working on a release :-/ Can you email jeff at the company I work for dot com with an email address and I'll invite you to a Slack channel?

**Pull request closed without merging**
