### PR TITLE
UI: fixes link from to show page from entity policies list

### PR DESCRIPTION
**Pull request by hellobontempo**
this PR previously addressed a capabilities issue in the show template, but we decided to approach the solution another day and get to the root of the problem (rather than supply a bandaid fix)

### CODE REVIEW

**Review by zofskeez — APPROVED** [review]
Thanks! I wonder how this worked in the first place if the model was being unloaded on route change by that mixin? Maybe something changed in the run loop timing or something in the new version.

**Comment by zofskeez** [comment]
A few policy tests are failing but I'm guessing they just need to be updated to have `this.capabilities.isLoaded` returning true.

**Comment by hellobontempo** [comment]
> A few policy tests are failing but I'm guessing they just need to be updated to have `this.capabilities.isLoaded` returning true.

It ended up being more complicated than that...updated the template so that tests pass. 

I'm not sure if changing the capabilities check from `this.capabilities` to `this.model.capabilities` has far reaching consequences? The capability model seemed to be what was causing the problem...

**Review by zofskeez — COMMENTED** [review]
I'm not familiar with the capabilities model but it looks to me like using lazyCapabilities on the policy model itself is more appropriate. It might be a good idea to get another set of eyes on this just to be sure.

**Review by hashishaw — APPROVED** [review]

**Pull request merged**
