### PR TITLE
yarn --verbose run: fix no output timeout in CI

### PR DESCRIPTION
**Pull request by samsalisbury**
CI kills the job after 10 mins with no output, verbose mode should output enough to prevent this timeout happening.

### CODE REVIEW

**Review by Monkeychip — APPROVED** [review]

**Comment by samsalisbury** [comment]
Closing as stale.

**Comment by mladlow** [comment]
@samsalisbury this was approved, why wasn't it merged?

**Comment by samsalisbury** [comment]
@mladlow I figured if this was still an issue then we would have heard about it? Happy to reopen & update if there's still a need for this.

**Comment by samsalisbury** [comment]
OK, I just checked master and this change hasn't been made there, so I'll reopen and get this merged as it should be there really for reliability.

**Comment by samsalisbury** [comment]
Just re-did the work and force-pushed as easier than merging all these months later :)

**Comment by mladlow** [comment]
Thanks! I'm pretty sure it does still fail in this way from time to time.

**Pull request merged**
