### PR TITLE
Fix "does not exists" grammar

### PR DESCRIPTION
**Pull request by stevegore**
This PR just replaces the phrase "does not exists" with the grammatically correct "does not exist". It's just a little jarring to get an error message with a grammar mistake.

### CODE REVIEW

**Comment by jefferai** [comment]
Anything you've changed in the vendor dir will be reverted at the next vendor update. Those would have to be separate PRs with the relevant projects.

**Comment by stevegore** [comment]
Of course, that makes complete sense. Will do.

**Comment by catsby** [comment]
For now @stevegore I would be happy to merge this PR if the changes made to the `vendor` directory were removed.

**Comment by stevegore** [comment]
Sure no problem. Changes to the vendored dependencies have been made in their respective repos. Will remove here now.

**Comment by stevegore** [comment]
Changes to the `vendor` directory have been removed.

**Comment by catsby** [comment]
Thank you!

**Pull request merged**
