### PR TITLE
python is not found on macOS Monterey

### PR DESCRIPTION
**Pull request by lmilbaum**
* add instructions on how to link python to python3

### CODE REVIEW

**Comment by cipherboy** [comment]
\o Hello @lmilbaum 

Do you have the error message we got? To the best of our knowledge, the Vault Go server doesn't depend on Python in its build process. If this affects the UI code (`make static-dist` &c), the `ui/README.md` would probably be a better place for it.

**Comment by lmilbaum** [comment]
> \o Hello @lmilbaum
> 
> Do you have the error message we got? To the best of our knowledge, the Vault Go server doesn't depend on Python in its build process. If this affects the UI code (`make static-dist` &c), the `ui/README.md` would probably be a better place for it.

Thanks @cipherboy. Pushed a change. LMK if that works better.

**Comment by cipherboy** [comment]
Hi @lmilbaum -- we've attempted to reproduce this on several of our MacOS and Ubuntu machines without a `python` (unversioned) executable and have been unable to. We're going to go ahead and close this without merging. Do let us know if you have the complete build logs of the failure without unversioned python, as we'd be curious to see them. Thanks!

**Comment by lmilbaum** [comment]
Thanks @cipherboy. I have moved on to deal with higher priority tasks. I am ok with closing this ticket.

**Pull request closed without merging**
