### PR TITLE
Remove the string 'Vault' from version information

### PR DESCRIPTION
**Pull request by vishalnayak**

### CODE REVIEW

**Comment by vishalnayak** [comment]
@sethvargo Probably the `v` can also be dropped. The use case was just that the string "Vault" in the output was redundant.

**Comment by jefferai** [comment]
I'm very ambivalent about this change, as this wasn't meant to be something that would be parsed in the first place, since it was humans that wanted to know the version number. But, if `v` isn't included in the output, it should be removed from the docs as well.

**Comment by vishalnayak** [comment]
@jefferai Updated docs. Atlas listener was using short form of version *without* the prerelease. Updated that as well.

**Comment by jefferai** [comment]
@vishalnayak Please check with Atlas team about that change...that may be on purpose.

**Pull request merged**
