### PR TITLE
CockroachDB supports high availability

### PR DESCRIPTION
**Pull request by mbertschler**
Unless I am misunderstanding the definition of high availability here, CockroachDB supports it if the cluster is setup correctly

### CODE REVIEW

**Comment by ncabatoff** [comment]
High availability in this context does not mean that the storage itself is highly available, it means that the Vault code to interface to that storage implements the `HABackend` interface, which allows *Vault* to be highly available with that backend.  In other words we know how to use it to allow failover to standby Vault nodes.

**Comment by mbertschler** [comment]
@ncabatoff ah thanks for clarifying. Would you be interested in a PR that enables this for the CockroachDB backend?

**Comment by ncabatoff** [comment]
@mbertschler sure that would be great!  I don't know much about cockroachdb, but I did help with the postgresql HA implementation, and I understand cockroachdb is somewhat compatible with PG.  So you might want to have a look at how the PG HA implementation works.

**Comment by tyrannosaurus-becks** [comment]
Thanks for this PR, @mbertschler ! Since the docs are accurate _for now_, I'm going to go ahead and close this. However, if you do end up adding a PR enabling high availability for CockroachDB, please do feel free to re-add that text. Thanks again!

**Pull request closed without merging**
