### PR TITLE
Update docs 4 standalone tls

### PR DESCRIPTION
**Pull request by phozzy**
Solves #13410
Updates the document to meet the changes to k8s certificates API.

### CODE REVIEW

**Comment by hsimon-hashicorp** [comment]
@phozzy did you mean to close this PR? Let me know. :)

**Comment by phozzy** [comment]
@hsimon-hashicorp I thought that it is possible to reuse previous one. But it seems that after a force push, it is not possible.

**Comment by hsimon-hashicorp** [comment]
Looks good, @taoism4504! Thanks for the contribution, @phozzy. :)

**Comment by phozzy** [comment]
🤔

**Comment by taoism4504** [comment]
@phozzy , can you resolve the file conflicts?

**Comment by schavis** [comment]
@phozzy Please resolve the conflicts. If there is no activity on this PR by September 8th, the content team will close the PR.

**Review by schavis — APPROVED** [review]

**Pull request merged**
