### PR TITLE
Add DogStatsD metrics output.

### LINKED ISSUE #2490: Support DogStatsD for telemetry
It would be nice to have this feature implemented for vault as well https://www.consul.io/docs/agent/options.html#telemetry-dogstatsd_addr

It sends similar metrics to the already implemented `statsd_address`, but adds tagging and support for other datadog features.

### PR DESCRIPTION
**Pull request by jefferai**
Fixes #2490

### CODE REVIEW

**Comment by jefferai** [comment]
Ported directly from Consul. Parsing tests pass, so going to just merge.

**Comment by jippi** [comment]
I guess this also still uses classic statsd paths rather than tagged metrics paths?

**Comment by jefferai** [comment]
Maybe?

**Comment by josegonzalez** [comment]
Yeah its classic statsd paths. Should be fairly easy to switch to tagged metric paths as shown in this pull request for [consul](https://github.com/hashicorp/consul/pull/3369/files), though it would require at least a minor release.

**Pull request merged**
