### PR TITLE
Fixed path to file sink page

### PR DESCRIPTION
**Pull request by ArsenyBelorukov**
there is a typo to the "file sink" page.

### CODE REVIEW

**Comment by hghaf099** [comment]
Thanks for contributing the the project. Would you please sign the CLA? That is needed prior to merge the PR.

**Review by schavis — APPROVED** [review]

**Comment by hsimon-hashicorp** [comment]
Hello @ArsenyBelorukov - just a reminder that we need the CLA signed in order to merge this. If you're having issues with the CLA bot, it's usually related to trying to sign it with an email address versus a GitHub ID, or not having your organization publicly visible if it's a corporate CLA. Thanks in advance!

**Comment by schavis** [comment]
@ArsenyBelorukov reminder to sign the CLA so we can merge your contribution. As the PR is over 6 months old, it'll closed as abandoned on May 10, 2024.

**Comment by ArsenyBelorukov** [comment]
it is already fixed

**Pull request closed without merging**
