### PR TITLE
Don't allow duplicate SAN names in PKI-issued certs

### LINKED ISSUE #6571: Vault should not create duplicate SAN entries
We use Vault so sign CSRs and issue certificates and have a small feature request:

Problem description: Assume the following PKI role to sign server certificates:
`vault write pki/roles/example allowed_domains=example.com allow_subdomains=true client_flag=false`

A typical CSR which for example should cover two domains looks like this:

> Certificate Request:
>     Data:
>         Version: 0 (0x0)
>         Subject: O=Foobar, CN=one.example.com
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 Public-Key: (2048 bit)
>                 Modulus:
>                     00:[...]
>                 Exponent: 65537 (0x10001)
>         Attributes:
>         Requested Extensions:
>             X509v3 Subject Alternative Name:
>                 DNS:one.example.com, DNS:two.example.com
>     Signature Algorithm: sha256WithRSAEncryption

When this CSR is submitted to Vault via "vault write pki/sign/example csr=@...csr" we receive the following certificate back:

> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number:
>             1f:e2:09:f2:81:e1:b9:46:e1:9d:30:b7:fb:46:07:5d:2c:02:bb:eb
>     Signature Algorithm: sha256WithRSAEncryption
>         Issuer: CN=My Root CA
>         Validity
>             Not Before: Apr 11 16:35:36 2019 GMT
>             Not After : Apr 11 16:44:06 2019 GMT
>         Subject: CN=one.example.com
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 Public-Key: (2048 bit)
>                 Modulus:
>                     00:[...]
>                 Exponent: 65537 (0x10001)
>         X509v3 extensions:
>             X509v3 Key Usage: critical
>                 Digital Signature, Key Encipherment, Key Agreement
>             X509v3 Extended Key Usage:
>                 TLS Web Server Authentication
>             X509v3 Subject Key Identifier:
>                 EC:E5:E7:61:26:4C:A5:E3:E7:DF:83:37:BB:E0:4F:3A:3F:E9:5A:D7
>             X509v3 Authority Key Identifier:
>                 keyid:18:5B:DB:70:29:43:75:E2:D8:80:8D:3A:CC:C0:62:CD:EF:37:5F:F4
>             X509v3 Subject Alternative Name:
>                 **DNS:one.example.com, DNS:two.example.com, DNS:one.example.com**
>     Signature Algorithm: sha256WithRSAEncryption

The certificate now contains "DNS:one.example.com" two times in the SAN extension. This is not a huge problem, but makes the certificate unnecessarily larger and the domain name list harder to read.

I know that the client could avoid this by specifying "exclude_cn_from_sans=true" in his request, but most clients are lazy and unconditonally setting exclude_cn_from_sans=true for every request leads again to other problems for CSRs which cover only one domain name and do not include a SAN extension at all.

 

Since I'm not aware of any use case of duplicated SAN entries, I suggest that before copying the CN into the SAN extension, Vault should check if the exact same entry already exists. If yes, the CN will not be copied.

### PR DESCRIPTION
**Pull request by mr-tron**
Fixes #6571

### CODE REVIEW

**Comment by jefferai** [comment]
Thanks for doing this! I don't think the test actually exercises the functionality though as you've added a new unique name instead of a duplicate. Can you update the tests?

**Comment by mr-tron** [comment]
image
I think that test covered it. We duplicates CN in SANs, but after issuing we have only 3 SANs. When we added duplicates we had 4.

**Comment by mr-tron** [comment]
Any news? I think new functionality is covered with tests. We add same domain to CN and to SANs and count that results array contains only 3 domains and check every domain.
If you disagree, may be you can describe what more I can cover with tests?

**Comment by jefferai** [comment]
Nope, thanks for pointing that out, I missed it.

**Comment by jefferai** [comment]
Looks good, thanks!

**Pull request merged**
