### PR TITLE
Add local flag to docs for API endpoints.

### PR DESCRIPTION
**Pull request by clstokes**

### CODE REVIEW

**Comment by jefferai** [comment]
The local flag is not only supported on Vault Enterprise. There is just no feature on the open source side that uses it. But you can configure a mount to be local in OSS and later upgrade to Enterprise with replication and have the local flag be respected.

**Comment by clstokes** [comment]
How about this instead? 

> Additionally, the following options are accepted in Vault open-source, but relevant functionality is only supported in Vault Enterprise:

**Comment by jefferai** [comment]
@clstokes Yeah, that's better!

**Comment by clstokes** [comment]
Updated. I thought _allowed_ might be clearer than _accepted_.

**Comment by jefferai** [comment]
Looks good! Thanks!

**Pull request merged**
