### PR TITLE
Fixes #2789

### LINKED ISSUE #2789: DynamoDB backend is failing to list secrets in the Generic Secret provider
This is using Vault 0.7.2 on a Windows platform.  I've tried running it in both single-node mode as well as HA-mode with 2 nodes using the DynamoDB storage backend.  I'm using an account that has full permissions against the DynamoDB table instance that's being used for storage.

I can read and write secrets to the default Secret Provider mount at `/secret`, but if I try to list, I get an error (in the case of the CLI it returns no secrets found, but if I use the API directly, I see it's returning back an error).

For example, assuming I have written 2 secret entries named `s1` and `s2`:

```
C:\test\local>vault read -address=http://127.0.0.1:8200 secret/s1
Key                     Value
---                     -----
refresh_interval        768h0m0s
foo1                    bar1


C:\test\local>vault read -address=http://127.0.0.1:8200 secret/s2
Key                     Value
---                     -----
refresh_interval        768h0m0s
foo2                    bar2
foobar2                 foobaz2

C:\test\local>vault list -address=http://127.0.0.1:8200 secret
No value found at secret/

```

If I use the HTTP API directly, when listing the secrets at `/secret` I get back this response:
Request:
```
GET http://127.0.0.1:8200/v1/secret?list=true HTTP/1.1
X-Vault-Token: xxxx
Host: 10.20.1.61:8200
```
Response:
```
HTTP/1.1 404 Not Found
Cache-Control: no-store
Content-Type: application/json
Date: Thu, 01 Jun 2017 19:03:05 GMT
Content-Length: 14

{"errors":[]}
```

Just for comparison, I ran the same set of tests on Vault instances using Consul and S3 storage backends, and they worked as expected.

### PR DESCRIPTION
**Pull request by ebekker**
Corrects DynamoDB record path resolution when running Vault server on
Windows

### CODE REVIEW

**Comment by briankassouf** [comment]
@ebekker nice catch! I think the `path.Dir` function should work as it doesn't use OS specifics. https://golang.org/pkg/path/#Dir

**Comment by ebekker** [comment]
Ah yes, much nicer, the global replace of `ToSlash` felt a bit *icky*.

**Comment by ebekker** [comment]
@seiffert -- since you are the original author of this backend, wondering if you can do a quick sanity check to make sure that I didn't miss some nuance of your original implementation by doing a switch from `filepath` to `path` package in manipulating the record Paths?

**Comment by seiffert** [comment]
This change makes sense to me. Thanks!

**Pull request merged**
