### PR TITLE
Website update typography

### PR DESCRIPTION
**Pull request by jasoncostello**
:wave: This PR is part of a larger initiative by HashiCorp to create a more consistent typographic experience across all of the OSS sites. I updates the fonts to Klavika and Open Sans and updated the logo. There are a few related tweaks to variables and font-weights to adjust accordingly.

### It looks like this:

screencapture-localhost-4567-1488487850373

cc/ @pearkes

### CODE REVIEW

**Comment by jefferai** [comment]
@jasoncostello is this ready? (Saw the commits after initial PR so wanted to check)

**Comment by pearkes** [comment]
@jefferai This is good to merge, thanks!

**Comment by jasoncostello** [comment]
@jefferai Yes, it's ready. Just forgot to push that last commit while I was submitting the PR 😄

**Comment by jefferai** [comment]
👍

**Pull request merged**
