### PR TITLE
plugin/secrets/auth: enable multiplexing

### PR DESCRIPTION
**Pull request by fairclothjm**
- the plugin will be multiplexed when run as an external plugin by vault versions that support secrets/auth plugin multiplexing (> 1.12)
- we continue to set the TLSProviderFunc to maintain backwards compatibility with vault versions that don't support AutoMTLS for secrets/auth plugins (< 1.12)

### CODE REVIEW

**Review by swenson — APPROVED** [review]
LGTM

I did a spot check on the AWS and Transit.

It looks like the Transit plugin doesn't work as a standalone plugin (even before this change) :( But AWS worked fine.

**Comment by cipherboy** [comment]
@swenson I think PKI and Transit will not work as a standalone plugin due to requiring managed key support among other things, which isn't exposed via the external plugin GRPC interface.

**Comment by fairclothjm** [comment]
@swenson @cipherboy Thanks! I don't think there will be any problems with calling ServeMultiplex here for PKI and Transit. However, I am unsure if I should keep this change for them. I am not sure if it will cause any confusion for people reading the code? Any thoughts?

**Comment by cipherboy** [comment]
@fairclothjm Not sure, we're about to add these for SSH as well, so perhaps its just better to leave them consistent across all plugins and we ca sort this out later? Are we expecting customers to attempt to run these externally, now?

**Comment by fairclothjm** [comment]
@cipherboy 
> Are we expecting customers to attempt to run these externally, now?

No, I don't expect so.

> so perhaps its just better to leave them consistent across all plugins and we ca sort this out later

sounds good to me

**Pull request merged**
