### PR TITLE
Normalize the page title format in backend docs

### LINKED ISSUE #2636: Can the page titles for all the backends be normalized?
Can the page title format for all the backends (Auth, Audit, Secrets and Storage) be normalized?  Some of this was already cleaned up for the Secret backends in https://github.com/hashicorp/vault/commit/0fe2e84e3a559e68a25bbe6f622a37ec0ae47209 and Storage backends already seem to follow this nicer convention, but it would be nice to clean this up for all the remaining backends.

When looking at a few backends opened up in browser tabs, I think it would be helpful to have the name appear first so that it's quick to decipher what the page is about and then quickly identify which backend category it falls into.  Here's how they currently appear across the different categories:

vault-backends-doctitles

### PR DESCRIPTION
**Pull request by ebekker**
Fixes #2636

### CODE REVIEW

**Comment by vishalnayak** [comment]
Adding a `-` to the titles of secret backends or removing `-` from all the changes here, would fully normalize all the backends I suppose.

**Comment by ebekker** [comment]
Agreed -- what's everyone's opinion?  Add the `-` to the Secret backends or remove it from the other 3?  I prefer *with* the hyphen myself, but I can go either way, and I'll be happy to finish up the change to conform with the group consensus.

**Comment by vishalnayak** [comment]
@ebekker I am leaning towards not having the `-`.

**Comment by ebekker** [comment]
Very well.  For the Storage backends -- since they are in the `Configuration` subsection, they currently follow the pattern of `Backend Name - Storage Backends - Configuration` so I assume you want to keep the  `-` between "Storage Backends" and Configuration" and rename "Storage Backends" to Storage Backend, correct?  For example:

Old Title | New Title
-|-
`S3 - Storage Backends - Configuration` | `S3 Storage Backend - Configuration`

Also, all the title headers in the page contents currently match up with their corresponding page-structure titles, do you think these should be updated to match the new title format, or leave them as they are?

**Comment by vishalnayak** [comment]
@ebekker Regardless of it being in the configuration section, we can just name the titles as `S3 Storage Backend`, `Consul Storage Backend`, etc. This will go inline with the headers too.

**Comment by chrishoffman** [comment]
There is some general docs work happening now that will hopefully make this more consistent.  Closing this PR since things have moved significantly since this was opened.

**Pull request closed without merging**
