### PR TITLE
fixing the return type of verify otp

### PR DESCRIPTION
**Pull request by rajanadar**
it seems to be 200 on valid OTP and 204 on invalid OTP. (i think it should be an error.. 400 or 404)
but for the moment, fixing the docs to match the existing behavior.

### CODE REVIEW

**Comment by rajanadar** [comment]
one other option instead of 400 or 404 response type is to have a 200 response all the time, with a secret structure, with one of the fields in the "data" packet being "IsValid" which'll be true/false. If true, then the other "data" fields will be non-null.

**Comment by jefferai** [comment]
I think 204 was used because the response is empty and *technically* neither of the 400 or 404 conditions are satisfied, at least according to the literal specs. The verifying agent is supposed to check that the ip and username match. I had actually thought the other day about whether it should be a 404, even though it's not that the resource isn't found, it's that the OTP isn't found.

@vishalnayak thoughts?

**Comment by vishalnayak** [comment]
I agree with @jefferai.
It is a valid request to validate an invalid OTP. So it cannot be 400. Similarly, it is not 401 or 403 either since it is not an unauthorized or a forbidden request. It is a valid request.

It also doesn't make sense to call it 404 because client in this case is not requesting for a resource that is ID-ed by OTP. 204 seems fine and is used in many other similar use cases in vault.

**Comment by jefferai** [comment]
@vishalnayak OK. Let's keep it at 204 and just make sure it's documented. It's up to the helper to look for a correct response and not just at the status code.

**Comment by jefferai** [comment]
Merging this as-is -- thanks!

**Pull request merged**
