### PR TITLE
Add LDAP authentication to api

### PR DESCRIPTION
**Pull request by RickyGrassmuck**
This pull request adds LDAP to the Vault API package.

First PR here so Roast away and let me know if there is anything else needed from my end!

### CODE REVIEW

**Comment by hsimon-hashicorp** [comment]
Welcome to the HashiCorp Vault repo! We're glad you're here. No roasting, I promise. We'll get the review process started soon. :)

**Comment by hsimon-hashicorp** [comment]
Can you add a changelog entry, as well? We require one for all user-facing changes. :)

**Comment by RickyGrassmuck** [comment]
> Can you add a changelog entry, as well? We require one for all user-facing changes. :)

 No problem, entry added!

**Comment by RickyGrassmuck** [comment]
Forgot I had this PR open when I synced with upstream. I'll revert this when I get back to my desk later this evening.

**Comment by RickyGrassmuck** [comment]
Accidentally pulled changes in from upstream to my forks main so I have opened a new PR (#13841) for this feature on it's own branch. Closing out this PR

**Pull request closed without merging**
