### PR TITLE
UI: VAULT-17007 Add Dashboard to the sidenav

### PR DESCRIPTION
**Pull request by kiannaquach**
**Description**
- Add Dashboard to the side nav
Screenshot 2023-06-07 at 1 30 50 PM

### CODE REVIEW

**Review by zofskeez — COMMENTED** [review]
Currently the Vault logo in the top left of the sidebar is actually a link that we should now point to the dashboard route. It's in the `Sidebar::Frame` component and the HDS component is `Hds::SideNav::Header::HomeLink`

**Comment by kiannaquach** [comment]
@zofskeez Thanks for catching that! I've added a TODO since that logo nav item link is reliant on the `localStorage` work that will be done in another PR! Also added that as criteria in the ticket!

**Comment by zofskeez** [comment]
> that logo nav item link is reliant on the localStorage

Interesting so will the user be able to define which route will be there _home_ view?

**Comment by kiannaquach** [comment]
In a sense, yes, they will be able to define their home route if the user wanted to opt into the new dashboard ui.

The user stories are:

If the user opted into the new dashboard ui by clicking "New Dashboard UI available" next to the Secret Engine, the logo should always link to the dashboard

If the user did not opt into the new dashboard ui, then the logo should always link to the secret engine list view

**Comment by zofskeez** [comment]
Gotcha that sounds good thanks for the context!

**Review by zofskeez — APPROVED** [review]

**Pull request merged**
