### PR TITLE
Allow the policies menu point to be displayed in ui

### PR DESCRIPTION
**Pull request by pouyana**
Allows the policies menu point to be displayed to the user when the user has access to the policies.

### CODE REVIEW

**Comment by briankassouf** [comment]
@yhyakuna Could you take a look at this?

**Comment by meirish** [comment]
This was an issue with the code in the UI - https://github.com/hashicorp/vault/pull/6301 should fix it so the existing admin policy in that guide will show the policies tab.

**Comment by aphorise** [comment]
I believe this is no longer relevant and has been fixed since - @pouyana can you please confirm?

@yhyakuna your input also welcome.

**Comment by aphorise** [comment]
Closing as issue seems already resoled on [the related learn guide section](https://learn.hashicorp.com/tutorials/vault/policies#write-a-policy) as per the original intent on this PR.

**Pull request closed without merging**
