### PR TITLE
Fix: handle max_request_size<=0

### PR DESCRIPTION
**Pull request by guacamole**
Signed-off-by: guacamole <gunjanwalecha@gmail.com>

This PR tries to fix the issue #9936 
Setting `max_request_size` to 0 or a negative number should disable request size limiting 

### Motivation

As per the documentation: `max_request_size` is the maximum allowed request size, in bytes. Defaults to 32 MB. Specifying a number less than or equal to 0 should turn off limiting altogether.

#### Implementation details

Old implementation:
* when `max_request_size` is 0, it gets set to a default size of 32 MB
* when  `max_request_size` is negative, it throws an error saying: " max_request_size cannot be negative"

New implementation:
* when `max_request_size`  set to less than or equal to 0, the limiting is disabled

### CODE REVIEW

**Comment by guacamole** [comment]
@raskchanky Would you please have a look at this ?

**Review by raskchanky — CHANGES_REQUESTED** [review]
One issue with the current approach is that 0 is Go's default value for integers, so if no max request size is specified, it will be 0, in which case the default _should_ be used. Otherwise, it's kinda pointless to have a default value 😁.

In my opinion, the right fix here is to:
* remove the error saying max request size can't be negative
* if max request size is negative, then disable it
* update the docs to reflect this change

Also, in addition to fixing the existing CI failure, it'd be great to have some additional tests showing that:
* the default max request size is still in place if it's not overridden
* it's properly disabled when set to a negative value
* the config is parsed correctly with negative values in it

Thanks so much for working on this!

**Comment by guacamole** [comment]
@raskchanky Thanks for the input, I'm working on it!

**Comment by HridoyRoy** [comment]
Hi @guacamole ,
It's been a while since we've heard from you. Wondering if you were still working on this PR? 

Thanks so much!

**Comment by guacamole** [comment]
Hello @HridoyRoy  
 sorry for the long time, I'll get to it today and have an update for you soon:)

**Comment by guacamole** [comment]
Hi @raskchanky , I just rebased my PR from master and `test-go` is failing on circle-ci . Would you please check the failing test cases as the http module did not fail on my local.

**Review by HridoyRoy — APPROVED** [review]
@guacamole lgtm!

**Review by raskchanky — APPROVED** [review]

**Comment by HridoyRoy** [comment]
I've created a docs PR to go with this change[ here](https://github.com/hashicorp/vault/pull/10723/files)

**Pull request merged**
