### PR TITLE
Core: Persist Mount Table. One cicle

### PR DESCRIPTION
**Pull request by valli0x**
I don't think there's a need for two iterations in persistMount

### CODE REVIEW

**Comment by mpalmi** [comment]
Greetings, @Nikita1821! Thanks for your submission.

Have you had a chance to look at our [Contribution Guidelines](https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md#pull-requests)? Please make sure to review and update the PR to be in compliance with these guidelines.

**Comment by valli0x** [comment]
@mpalmi check pr please

**Comment by mpalmi** [comment]
@valli0x Thanks for updating the PR with a changelog. If you don't mind I'd also be interested in seeing a bit more context/description around this change.

Specifically interested in:
> Your pull request should have a description of what it accomplishes, how it does so, and why you chose the approach you did. PRs should include unit tests that validate correctness and the existing tests must pass. Follow-up work to fix tests does not need a fresh issue filed.

It may also be helpful to add an issue and link to that in the PR description:
> Creating an issue in advance of working on the PR can help to avoid duplication of effort, e.g. maybe we know of existing related work. Or it may be that we can provide guidance that will help with your approach.
 If you could provide more context in the PR description, that would help the review a bit.

It appears some of the [test-go-remote-docker](https://circleci.com/gh/hashicorp/vault/515713?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) tests are failing. I kicked the tests off again, so let's see if the results are the same or can just be chalked up to flakiness.

**Comment by valli0x** [comment]
rotation_test.go:733: Skipping MongoDB Atlas test because VAULT_MONGODBATLAS_PROJECT_ID not set

**Comment by valli0x** [comment]
mongodbhelper.go:68: could not start docker mongo: no reachable servers

**Comment by valli0x** [comment]
In function persist(Mount/Auth/Audit) use two iteration by table 
1. For check table type entry in table
2. For add entry in local/non-local keys
I think it may do in one iteration by mount/auth/audit table

**Comment by valli0x** [comment]
@mpalmi I look up test detail and I don't why failed

**Comment by mpalmi** [comment]
> @mpalmi I looked at the test details and it looks like some strange

It appears that the latest on your branch is based off of an old commit in main. If I'm not mistaken, the issue was fixed here: https://github.com/hashicorp/vault/commit/247a019be0ace89bfa3cdc54c0294829bf390ef0

At any rate, you might want to rebase on the latest main, or otherwise merge main into your branch. Let's see if that fixes the tests.

**Comment by valli0x** [comment]
@mpalmi test is correct

**Comment by valli0x** [comment]
@mpalmi check my request please

**Comment by valli0x** [comment]
@mpalmi check please, I removed the commit

**Comment by valli0x** [comment]
@mpalmi Can you check my pr?

**Comment by valli0x** [comment]
@mpalmi maybе today?)

**Review by mpalmi — APPROVED** [review]

**Pull request merged**
