### PR TITLE
Fix etcd2 ha backend

### PR DESCRIPTION
**Pull request by shsjshentao**
This problem will happen easily in low performance disk machine.
renewSemaphoreKey can check the key status(missing, expiration and deletion).
if the key status is abnormal, must stop channel.

### CODE REVIEW

**Comment by jefferai** [comment]
I'm a bit hesitant about merging this simply because I don't have any experience whatsoever with it. CoreOS is actively supporting the etcd3 backend, is it possible for you to switch to it?

**Comment by shsjshentao** [comment]
We will consider switching to etcd3 later. But the customer used etcd2 data. We need more test to upgrade etcd ha and vault ha in case of data loss.

**Comment by jefferai** [comment]
I'd feel better if someone who knows the etcd2 backend and/or etcd2 APIs would chime in. That said, I believe you can just switch from etcd2 to etcd3. @xiang90 do you know if there are any issues there?

**Comment by chrishoffman** [comment]
Closing due to inactivity.

**Pull request closed without merging**
