### PR TITLE
Use generate endpoint instead of admin-generate during MFA setup

### PR DESCRIPTION
**Pull request by needToRoll**
fixes: #17113

To do this I updated the adapter used by the MfaSetupStepOne component.
(And adjusted the expectations in the tests)

Any questions and/or feedback is appreciated.

### CODE REVIEW

**Review by hashishaw — APPROVED** [review]
Excellent work, thank you!

**Comment by needToRoll** [comment]
Hi @hashishaw, 

I noticed that the CI checks that are executed on circleci seem to be stuck somehow.
Is there anything I should do about that?

Thank you for the fast review and the compliment.

**Comment by hashishaw** [comment]
> Hi @hashishaw,
> 
> I noticed that the CI checks that are executed on circleci seem to be stuck somehow. Is there anything I should do about that?
> 
> Thank you for the fast review and the compliment.

@needToRoll I approved it to run, but it looks like something didn't kick off correctly. Separately, we're evaluating internally whether this is the expected workflow, so I'm going to un-approve for now until we figure out the best way forward. Either way, I'll update you here on the decision and hopefully the workflow will become more clear!

**Review by hashishaw — CHANGES_REQUESTED** [review]
Un-approving temporarily

**Comment by needToRoll** [comment]
Alright just let me know (i.e.: @-me) if there is anything I should do.
Thanks for being transparent

**Review by hashishaw — APPROVED** [review]
After discussion we would like to accept this PR! 

@needToRoll Since this is a relatively new UI feature, would you mind answering some questions about your use case with MFA? If so I will loop in @finnstech -- they are a PM on the Vault team. We'd love your feedback to continue to make the Vault UI better!

**Comment by needToRoll** [comment]
> Since this is a relatively new UI feature, would you mind answering some questions about your use case with MFA?
Sure, I can give you some feedback altough I might not be your typical user :)

**Comment by hashishaw** [comment]
@needToRoll would you please push an empty commit so that it kickstarts the CircleCI jobs again? 🙏

**Comment by finnstech** [comment]
> > Since this is a relatively new UI feature, would you mind answering some questions about your use case with MFA?
> 
> Sure, I can give you some feedback altough I might not be your typical user :) One thing that I think might be relevant here I've alread tried to describe here: #18028

Yeah, I am a PM on Vault and was curious about how you're expecting users to interact with MFA. It doesn't seem like it would scale to use this Web-based method for onboarding more than a handful of users, which is a valid but not typical case.

**Comment by needToRoll** [comment]
> would you please push an empty commit so that it kickstarts the CircleCI jobs again?
@hashishaw That did not work... Do you have any other idas on what to do/try next?

**Comment by hashishaw** [comment]
@needToRoll we're experiencing some difficulties with CircleCI 😁 Admin-merged and we're all set! Thanks for your patience!

**Comment by needToRoll** [comment]
@finnstech Hi, thank you for reaching out.
First of all: Yes my user base is very small (between 5 and 10 users, this is why I mentioned that I might not be a typical user).

**In regards to the onboarding process:**
From the perspective of an administrator it would be great to have the option to create an enforcement with a grace period.
This could look something like this:
As an administrator I define an enforcement with a grace period of i.e.: 10 days.
As soon as a user that is affected by the enforcement logs in (during said grace period), he is prompted to setup his TOTP-App.
From that point on the user would allways have to present his second factor passcode.

Once the grace period is over users that did not steup their TOTP-App would get an error telling them to contact the administrator. (The fallback would be to use the admin-generate endpoint) and send them the TOTP-QR Code some other way.)

In order to make TOTP less of a hassle implementing a validation step as described in (#18028) would be important.
Note that both MS-Authenticator and Google-Authenticator ignore the algorithm specified within the optauth-URL and therefore generate invalid passcodes. (I filed bug-reports for both of them, but I don't expect much)

One last thing that I noticed is that even after a user has set up his TOTP. He is not required to use it during logins until the admin sets up an enforcement.
This is a bit counter intuative (at least to me) because it takes away the oportunity for security-cautious users to enable 2FA at their own will.

I hope you can take something away from this feedback even tough I do not have the large userbase you might have suspected.

If you do have any follow up questions feel free to ask them.

Best regards
Florian

PS: English is not my first language... Sorry :)

**Comment by needToRoll** [comment]
Hi @hashishaw thank you for your support! 👍

**Comment by finnstech** [comment]
@needToRoll Thank you for clarifying and sharing your use case!

**Pull request merged**
