### PR TITLE
fix: Correctly handle TLS config when ssl=true or tls=true connection string option set.

### PR DESCRIPTION
**Pull request by cyrus-mc**
fix for #9509 

Merge writeOpts and authOpts after call too ApplyURI.

### CODE REVIEW

**Comment by cyrus-mc** [comment]
Build is failing with error about using internal module. This PR doesn't touch any of that (it is a simple one line change) so not sure how this error is being caused.

**Comment by cyrus-mc** [comment]
@ncabatoff Merged in latest master changes that fixed build. This PR is ready to go. I am using a locally build Vault, containing this fix, without issue.

**Comment by ncabatoff** [comment]
Thanks @cyrus-mc!

**Comment by pbar1** [comment]
Hey, FYI - this change seemed to break our Mongo db engine upon upgrading form 1.5 -> 1.6. When setting up the provider, we use client TLS _as well as_ the username/password authentication via SCRAM-SHA-256. Due to the order in which this change merges config, if client TLS configuration is passed at all, it will always win, making other auth mechanisms unusable.

**Pull request merged**
