### PR TITLE
Docs: API generate-recovery-token - unhide

### PR DESCRIPTION
**Pull request by aphorise**
api_generate-recovery-token

### CODE REVIEW

**Review by ncabatoff — APPROVED** [review]

**Comment by aphorise** [comment]
Hey @taoism4504  / @ncabatoff - I was curious what's the status here - is it pending a particular release / date?

**Comment by aphorise** [comment]
Can this also be updated on the `api` swagger section?

**Comment by aphorise** [comment]
@ncabatoff / @taoism4504 - hey what's pending for this section of the docs to show?

**Comment by aphorise** [comment]
Redone this on the following PR: https://github.com/hashicorp/vault/pull/16213

**Pull request closed without merging**
