### PR TITLE
Add option to set cluster TLS cipher suites.

### LINKED ISSUE #3227: Enforce Cipher suites on cluster port 8201
Related to #1193 

How to enforce those ciphers also for the cluster_address (default port 8201)? If I set the tls_cipher_suites parameter it works only for the main TCP listener (port 8200) and not the cluster one. With the example listener like this:

listener "tcp" {
address = "0.0.0.0:8200"
cluster_address = "0.0.0.0:8201"
tls_min_version = "tls12"
tls_cert_file = "/certs/server.crt"
tls_key_file = "/certs/server.key"
tls_cipher_suites = "TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
tls_prefer_server_cipher_suites = "true"
}

The ciphers are properly configured only on port 8200, and port 8201 still goes with what seems like to be the Go's default for the TLS v1.2. Here's the output from the TLS scan:

$ ./o-saft.pl --no-sslv2 --no-tlsv13 --ignore-output=https_body --no-dns --enabled --no-header +cipherall 172.28.135.239:**8200**
172.28.135.239, 8200, SSLv3 (0x0300), no SNI, , ,

172.28.135.239, 8200, TLSv1 (0x0301), no SNI, , ,

172.28.135.239, 8200, TLSv11 (0x0302), no SNI, , ,

172.28.135.239, 8200, TLSv12 (0x0303), no SNI, Server Order, 0x0300009C, **AES128-GCM-SHA256** , RSA_WITH_AES_128_GCM_SHA256
172.28.135.239, 8200, TLSv12 (0x0303), no SNI, Server Order, 0x0300009D, **AES256-GCM-SHA384** , RSA_WITH_AES_256_GCM_SHA384
172.28.135.239, 8200, TLSv12 (0x0303), no SNI, Server Order, 0x0300C02F, **ECDHE-RSA-AES128-GCM-SHA256** , ECDHE_RSA_WITH_AES_128_GCM_SHA256 , (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)

$ ./o-saft.pl --no-sslv2 --no-tlsv13 --ignore-output=https_body --no-dns --enabled --no-header +cipherall 172.28.135.239:**8201**
172.28.135.239, 8201, SSLv3 (0x0300), no SNI, , ,

172.28.135.239, 8201, TLSv1 (0x0301), no SNI, , ,

172.28.135.239, 8201, TLSv11 (0x0302), no SNI, , ,

172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order , 0x0300C009, **ECDHE-ECDSA-AES128-SHA** , ECDHE_ECDSA_WITH_AES_128_CBC_SHA , (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)
172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order , 0x0300C00A, **ECDHE-ECDSA-AES256-SHA** , ECDHE_ECDSA_WITH_AES_256_CBC_SHA , (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)
172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order , 0x0300C02B, **ECDHE-ECDSA-AES128-GCM-SHA256**, ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)
172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order , 0x0300C02C, **ECDHE-ECDSA-AES256-GCM-SHA384**, ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)
172.28.135.239, 8201, TLSv12 (0x0303), no SNI, No Order , 0x0300CCA9, **ECDHE-ECDSA-CHACHA20-POLY1305-SHA256**, ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, (ecdh, (primary) named_curve: ecdh_x25519, 255 bits)

### PR DESCRIPTION
**Pull request by jefferai**
Fixes #3227

### CODE REVIEW

**Comment by dspit1664** [comment]
Our Nessus scan has identified ports 8000 and 8201 has allowing weak ciphers does Vault allow for us to select only more secure ?
I.e. Remove  the ability to use RC4/3DES and only allow more secure ?

**Comment by jefferai** [comment]
See the options at https://www.vaultproject.io/docs/configuration/listener/tcp.html

**Comment by dspit1664** [comment]
Ah yes thanks

**Comment by dspit1664** [comment]
@jefferai Thanks for above 

- I've added the suite explicitly stating the ciphers to be used however when I use nmap still shows 
1. tls 1.0 and 1.1 
2. 3DES available 

Is there something I'm missing ?
a) what does nmap still show my versions of tls1.0 and 1.1 when I explicitly state 1.2
b) I understand C is not good so why if I explicitly state the ciphers I want to use does it show ones I have not specified ?

## Here is my config
```
- vault.cfg
# backend "file" {
#  path = "/var/lib/vault"
# }

storage "s3" {
  access_key = "blahblah"
  secret_key = "Iamasecret"
  bucket     = "vault-storage-staging"
  endpoint = "<S3 Storage>"
}

##listener "tcp" {
# address = "127.0.0.1:8200"
# tls_disable = 1
#}

disable_mlock=true

# BEGIN ANSIBLE MANAGED BLOCK
listener "tcp" {
# address = "0.0.0.0:8201"
 tls_disable = false
 address = "127.0.0.1:8200"
 tls_cert_file = "/var/lib/vault/pki/root_cert.pem"
 tls_key_file = "/var/lib/vault/pki/root_key.pem"
 tls_min_version = "tls12"
 tls_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA"
}
# END ANSIBLE MANAGED BLOCK
```
and 
- my nmap response:
ran nmap
```
nmap --script ssl-enum-ciphers -p 8000 <IP removed>

Starting Nmap 7.01 ( https://nmap.org ) at 2018-03-08 11:29 UTC
Nmap scan report for <FQDN removed> (<IP removed>)
Host is up (0.000044s latency).
PORT     STATE SERVICE
8000/tcp open  http-alt
| ssl-enum-ciphers:
|   TLSv1.0:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (secp256r1) - C
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors:
|       NULL
|     cipher preference: server
|   TLSv1.1:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (secp256r1) - C
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors:
|       NULL
|     cipher preference: server
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (secp256r1) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (secp256r1) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (secp256r1) - C
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors:
|       NULL
|     cipher preference: server
|_  least strength: C

**Comment by jefferai** [comment]
You aren't connecting to Vault...Vault is on port 8200 and you're nmapping
port 8000.

**Comment by dspit1664** [comment]
Yes you are correct I realised that and is why I removed my post.

To clarify. We use GoldFish UI it is using 8000. I need to raise a enhancement request in GoldFish GHE which is not here :)

The remediation of the Nessus scan result for 8201 was fixed using your docs.

**Comment by petersutty** [comment]
is cluster_cipher_suites available in Vault v0.11.5 ('a59ffa4a0f09bbf198241fe6793a96722789b639') ?
I did not find cluster_cipher_suites in docs either and I can not make it work somehow, using hcl config:
listener "tcp" {
  address          = "0.0.0.0:8200"
  tls_cert_file = "/etc/ssl/local/sy.com.crt"
  tls_key_file  = "/etc/ssl/local/s.com.key"
  tls_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384"
  tls_prefer_server_cipher_suites = "true"
}
storage "etcd" {
  address = "http://127.0.0.1:2379"
  etcd_api = "v3"
  path    = "vault/"
  ha_enabled    = "true"
}
api_addr = "https://10.99.4.62:8200"
cluster_addr = "https://10.99.4.62:8201"
cluster_cipher_suites = "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

any suggestions ?

**Comment by jefferai** [comment]
It's a listener option, not a top level option.

**Comment by jefferai** [comment]
It should work. We have tests that verify it. How are you checking it?

**Comment by petersutty** [comment]
Hi Jeff,

all good here now.
Thanks for support - I did not find it in the docs, that's is why I didn't
put it into listner options.

Regards,
Peter

**Pull request merged**
