### PR TITLE
docs: add vault-plugin-secrets-jenkins to plugin portal page

### PR DESCRIPTION
**Pull request by circa10a**
This PR adds a new entry to the community secrets plugins page for [vault-plugin-secrets-jenkins](https://github.com/circa10a/vault-plugin-secrets-jenkins)

Signed-off-by: circa10a <caleblemoine@gmail.com>

### CODE REVIEW

**Review by acahn — APPROVED** [review]
LGTM!  Thank you for your contribution!

**Comment by circa10a** [comment]
@acahn any reason why this wasn't merged?

**Comment by acahn** [comment]
> @acahn any reason why this wasn't merged?

@circa10a, apologies.  Looks like this got missed out.  We will get it merged shortly.

**Review by taoism4504 — APPROVED** [review]
LG

**Pull request merged**
