### PR TITLE
identity/oidc: adds detailed listing capability for clients and providers

### PR DESCRIPTION
**Pull request by austingebauer**
This PR adds detailed listing capability for OIDC clients and providers by introducing the `detailed` query parameter. The motivation for this is to improve the user experience in the Vault UI.

Example of detailed client list:
```sh
$ vault list -detailed identity/oidc/client

Keys      access_token_ttl    assignments    client_id                           client_type     id_token_ttl    key        redirect_uris
----      ----------------    -----------    ---------                           -----------     ------------    ---        -------------
my-app    24h                 [allow_all]    wGr981oYLJbcr4zrUriYxjxSc80JL7HW    confidential    24h             default    [http://localhost:5555/callback]

```

Example of detailed provider list:
```sh
$ vault list -detailed identity/oidc/provider

Keys       allowed_client_ids    issuer                                                     scopes_supported
----       ------------------    ------                                                     ----------------
default    [*]                   http://127.0.0.1:8200/v1/identity/oidc/provider/default    []
```

### CODE REVIEW

**Review by vinay-gopalan — APPROVED** [review]
LGTM! Looks like we're missing a changelog?

**Comment by calvn** [comment]
Does it support the `vault list ...` subcommand, and if so what does the output look like?

**Comment by austingebauer** [comment]
@calvn - Good question, I thought it might be okay for this to not work with the `vault list` command, but I'm now seeing [`ListResponseWithInfo`](https://github.com/hashicorp/vault/blob/main/sdk/logical/response.go#L147). I think using `ListResponseWithInfo` is a better option, so I'll go with that. That'll remove the need for the query parameter and allow users to execute `vault list ...` and `vault list ... -detailed`.

**Comment by austingebauer** [comment]
The CLI formats the list with `-detailed` into a table:
```
$ vault list identity/oidc/provider
Keys
----
default

$ vault list -detailed identity/oidc/provider

Keys       allowed_client_ids    issuer                                                     scopes_supported
----       ------------------    ------                                                     ----------------
default    [*]                   http://127.0.0.1:8200/v1/identity/oidc/provider/default    []
```

**Comment by austingebauer** [comment]
Changed approach to use `ListResponseWithInfo` in 763b0f3.

**Review by fairclothjm — APPROVED** [review]

**Pull request merged**
