### PR TITLE
sign-verbatim should set use_csr_common_name to true

### PR DESCRIPTION
**Pull request by joemiller**
The generated role used by the pki `/sign-verbatim` endpoint should set use_csr_common_name to true.

Fixes a bug where the sign-verbatim endpoint can only be used if a `common_name` field is added to the request even though the field is ignored.

example:
- csr subj:
```
$ openssl req -subject -noout -in vault-test.csr
subject=/C=US/ST=California/L=San Francisco/OU=vault/CN=vault
```

- request without common_name:
```
$ vault write -field=certificate pki/sign-verbatim/foo csr=@vault-test.csr
Error writing data to pki/sign-verbatim: Error making API request.

URL: PUT https://localhost:8201/v1/pki/sign-verbatim
Code: 400. Errors:

* the common_name field is required, or must be provided in a CSR with "use_csr_common_name" set to true
```

- request with dummy common_name:
```
$ vault write -field=certificate pki/sign-verbatim/foo csr=@vault-test.csr common_name="ignored" | openssl x509 -subject -noout
subject=/C=US/ST=California/L=San Francisco/OU=vault/CN=vault
```

### CODE REVIEW

**Comment by jefferai** [comment]
This should probably only be set when a common name isn't provided in the request. Otherwise there's no way to override it, and it creates backwards compatibility problems.

**Comment by joemiller** [comment]
I also noticed that a role is required to access the `/sign-verbatim` endpoint although that role is not used. I pushed a second commit to cover this case as well. Happy to squash into a single commit, lmk.

**Comment by joemiller** [comment]
@jefferai FWIW, `common_name` is not documented as an accepted parameter to the `/pki/sign-verbatim` endpoint so anyone using it that way was relying on undocumented behavior. Only `csr`, `ttl`, and `format` were documented.

I'll look at making that change, however.

**Comment by joemiller** [comment]
@jefferai It looks like the current logic does not allow for overriding the common_name from the request. Example:

```
# csr, without CN
$ openssl req -subject -noout -in vault-no-cn.csr
subject=/C=US/ST=California/L=San Francisco/OU=vault
```

```
$ vault write -client-cert=vault.crt -client-key=vault.key -field=certificate pki/sign-verbatim/foo csr=@vault-no-cn.csr  common_name=foo | openssl x509 -subject -noout
subject= /C=US/ST=California/L=San Francisco/O=Pantheon Systems, Inc./OU=vault
```

The signed certificate lacks a CN despite `common_name` being set in the request.

Thus there should be no change in behavior here.

There is a potential issue with the path change, however. If any clients were working around this issue by using the path `/sign-verbatim/<role>` (even though role is ignored and it is not documented to be used this way) they will break unless they switch to `/sign-verbatim`. We could keep this backwards compatible by making +/role optional I suppose.

**Comment by jefferai** [comment]
I think making the role param optional to keep backwards compatibility is the right approach.

**Comment by joemiller** [comment]
@jefferai Updated to make the role optional.

**Comment by joemiller** [comment]
`make test testrace` ran fine on my local machine. Possibly a transient failure on travis?

**Comment by jefferai** [comment]
Yeah, we get some transient Travis failures due to Travis varying wildly in timing.

**Comment by jefferai** [comment]
Looks good!

**Comment by jefferai** [comment]
Merged, thanks!

**Pull request merged**
