### PR TITLE
Don't run MSSQL revocations as a transaction

### LINKED ISSUE #5914: Vault cannot revoke RDS+MSSQL when user logged in
**Describe the bug**
https://www.vaultproject.io/docs/secrets/databases/mssql.html#amazon-rds describes a sample custom revocation statement for RDS MSSQL as the built-in default is not compatible. The sample script fails if the user is logged in:

`* failed to revoke entry: resp: (*logical.Response)(nil) err: mssql: Could not drop login 'v-root-my-role-4Hd5tHL0dpI8sjMcDPtC-1544115511' as the user is currently logged in.`

Since the entire custom revocation script is run in a single transaction, the failure of the `DROP LOGIN` also rolls back the `DROP USER`, plus any attempts to add `ALTER USER ... DISABLE`. 

Adding logic to kill any outstanding user sessions fails as the custom revocation statements are run in a transaction, and `KILL` results in

`* failed to revoke entry: resp: (*logical.Response)(nil) err: mssql: KILL command cannot be used inside user transactions.`

There's no mechanism in the plugin to skip transactions for the custom revocation script.  Note that the built-in mechanism skips transactions in order to revoke as much access as possible, so perhaps that should be used in this scenario as well.

**To Reproduce**
1. Create a RDS MSSQL instance, configuring Vault with the master login and password.
2. Configure Vault MSSQL w/the sample custom revocation script
3. Log in with the vault provided credentials
4. Attempt to revoke the lease
5. Observe user retains login and query permissions.

**Expected behavior**
Connected RDS MSSQL users who have their lease expired/revoked have their access revoked and are disconnected from the database.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.0.0
* Vault CLI Version (retrieve with `vault version`): Vault v1.0.0 ('c19cef14891751a23eaa9b41fd456d1f99e7e856')
* Server Operating System/Architecture: AWS RDS SqlServer SE 10.50

### PR DESCRIPTION
**Pull request by tyrannosaurus-becks**
Closes #5914 

Those using MSSQL RDS were unable to revoke users who were logged in. Adding a KILL statement before the revocation _would_ work if all the statements weren't run in the same transaction. So, this changes revocation statements to being executed individually.

### CODE REVIEW

**Comment by briankassouf** [comment]
I think this is the case, but if we fail x% of the way through the revoke a subsequent request will be able to succeed, right? e.g. we use IF EXISTS for everything?

**Comment by tyrannosaurus-becks** [comment]
@briankassouf well, in this case, all the revocation statements here are the ones that the user configured, rather than the default ones. So it depends on whether the user added them that way. I should probably update the examples in the docs to show that.

**Comment by tyrannosaurus-becks** [comment]
@briankassouf actually it looks like they're already that way in the doc examples so should be good.

**Comment by bhvishal9** [comment]
@tyrannosaurus-becks Could you please provide the kill command query that you used?

**Pull request merged**
