### PR TITLE
Add missing word "database" in docs

### PR DESCRIPTION
**Pull request by tvsaru**
SQL is the language and based on second bullet point the author probably intended SQL "database".

### CODE REVIEW

**Comment by tvsaru** [comment]
Will check with employer on respective terms in the CLA.

**Comment by hsimon-hashicorp** [comment]
Hi @tvsaru - were you able to get clarity on whether you'll be able to sign the CLA? Please let me know how we can help. Thanks!

**Review by klaporte — COMMENTED** [review]
This probably should say "a SQL database" versus "an SQL database".

**Review by taoism4504 — APPROVED** [review]
LGTM

**Comment by pmmukh** [comment]
Hey @tvsaru ! Did you maybe end up creating a separate PR for this change ? Was wondering if this one should be closed out.

**Comment by tvsaru** [comment]
Issued PR #13571 via `bloomberg` org to leverage the company-level CLA agreement.

**Pull request closed without merging**
