### PR TITLE
docs/secrets/mysql/index.html.md: add DSN link

### PR DESCRIPTION
**Pull request by glensc**
add DSN as link to go-sql-driver/mysql to know the syntax

### CODE REVIEW

**Comment by jefferai** [comment]
Thanks!

**Comment by glensc** [comment]
pff. that was super fast! i actually added second commit to the PR meanwhile...

**Comment by glensc** [comment]
it doesnt show that second commit here: https://github.com/hashicorp/vault/pull/2191/commits

and if i try to create PR again from same branch, it shows two commits

https://github.com/hashicorp/vault/compare/master...glensc:patch-1?expand=1

**Comment by jefferai** [comment]
You'll have to open a new PR, maybe from a new branch. Next time mark as WIP if you don't want it merged yet :-D

**Comment by glensc** [comment]
i decided i'll add another commit later :)

**Pull request merged**
