### PR TITLE
Add HTTP error 400 for UserError

### PR DESCRIPTION
**Pull request by fool1280**
Issues: https://github.com/hashicorp/vault/issues/20713

### CODE REVIEW

**Comment by fool1280** [comment]
@cipherboy Hi, I hope you are doing well! I'm just checking in :D Thank you!

**Comment by hsimon-hashicorp** [comment]
@fool1280 please check the reply from Alex, and let us know if you have any questions. Thanks!

**Comment by fool1280** [comment]
Yes, let me add the update. Sorry was busy for the last few weeks. :)

**Comment by digivava** [comment]
@ldilalla-HC can you please find a new approver on your team for this one? Changing the milestone to 1.16.1 since today is 1.16.0 code freeze.

**Pull request closed without merging**
