### PR TITLE
Turns the okta groups array into a coma separated string

### PR DESCRIPTION
**Pull request by ntroncos**
Many okta groups have spaces in them causing the output of the debug log to be useless.

### CODE REVIEW

**Comment by jefferai** [comment]
Are you trying to do text parsing on this?

**Comment by ntroncos** [comment]
No, just read it. 
my okta user has 200 groups attached to it, with 80% of them with spaces. It was imposible to tell where a group started and ended.
For example:
Product Development ABC
Product Development NYC
Product Development ABQ
Product Development SFO
Test Commission AQ

If you put them all in a line separated by space you can't really tell where one begins and where one ends.

I did use the coma separated string and some bash to generate a list. That would have been imposible with the space separated list.

**Comment by jefferai** [comment]
How about the output if you use `fmt.Sprintf("%#v", oktaGroups)`?

**Comment by jefferai** [comment]
Is that readable enough for you?

**Comment by ntroncos** [comment]
Yeah, Groups are properly separated.

**Comment by jefferai** [comment]
Sounds good

**Pull request merged**
