### PR TITLE
add allowed_names to cert-responses (cli and API) 

### PR DESCRIPTION
**Pull request by dominikmueller**
Again, since https://github.com/hashicorp/vault/pull/3642 reverted my previous merge request https://github.com/hashicorp/vault/pull/3654 (unfortunately also falsifying the [changelog for 0.9.1](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md)) 

I did *not* test it again in hope that there have not been basic changes in the code base.

### CODE REVIEW

**Comment by jefferai** [comment]
Looks like this misses the website changes.

**Comment by jefferai** [comment]
Looking at the merge it seems like no functionality changed other than this parameter return. Bad merge. Sorry!

**Comment by dominikmueller** [comment]
I know, so sorry for the bad merge request. I'll close it now as it's just a simple additional line. But I wanted to show that the already implemented [Bugfix](https://github.com/hashicorp/vault/blame/master/CHANGELOG.md#L99) broke/reverted when https://github.com/hashicorp/vault/pull/3642 was merged.

**Comment by jefferai** [comment]
The bad merge was on our side, not yours! I was apologizing to you :-)

Any chance you can add the website changes as well to this and then I'll merge this in?

**Pull request merged**
