### PR TITLE
Add allowed_uri_sans_template

### PR DESCRIPTION
**Pull request by pbohman**
Enables identity templating for the allowed_uri_sans field in PKI cert roles.

Implemented as suggested in #8509

### CODE REVIEW

**Comment by harsimranmaan** [comment]
Exactly what I have been looking for. @pbohman Do you want to rebase the PR?

**Comment by harsimranmaan** [comment]
@pbohman hey Pete, thanks for your contribution. Do you want to rebase the PR and resolve the merge conflict?

**Comment by harsimranmaan** [comment]
@hsimon-hashicorp Any chance that this could be prioritized?

**Comment by hsimon-hashicorp** [comment]
@harsimranmaan Thanks for bubbling this up! I'll get a reviewer as soon as I can. Thanks!

**Review by schultz-is — CHANGES_REQUESTED** [review]
Howdy @pbohman, thanks for the contribution! This looks functionally great. In order to get this merged in, can we get a changelog entry (`changelog/10249.txt`)?

**Comment by hsimon-hashicorp** [comment]
> Howdy @pbohman, thanks for the contribution! This looks functionally great. In order to get this merged in, can we get a changelog entry (`changelog/10249.txt`)?

Also, if we can get a documentation update PR (a new PR is fine), if it's needed, that'd be great :)

**Comment by pbohman** [comment]
@schultz-is, @hsimon-hashicorp, @harsimranmaan, thanks for the review and pushing this forward. The changelog and docs have been updated.

**Review by schultz-is — APPROVED** [review]

**Comment by schultz-is** [comment]
Thanks for contributing this, @pbohman!

**Comment by dovys** [comment]
Thanks for adding this ❤️  We just ran into this issue at @monzo trying to template spiffe:// SANs. Any chance we could get this released as a new tag? 🙏

**Pull request merged**
