### PR TITLE
ECDSA secp256k1 Support (for BTC and ETH crypto currency) another proposition

### PR DESCRIPTION
**Pull request by musitdev**
Hello,

### Presentation
I update the PR #11469 from @adastreamer to add these 2 requirements:
 * use full go lib
 * avoid crypto currency specificity to be compatible with more blockchain
 
I use the [btcsuite/btcec](https://pkg.go.dev/github.com/btcsuite/btcd/btcec) lib to generate the key and sign.

I add 3 new hash possibilities:
 * HashTypeKeccak256: for ETH signature (I use `golang.org/x/crypto/sha3`)
 * HashTypeDoubleSHA2256: to do a double SHA256 for BTC signature
 * None: to send the message already hashed. Can be useful when signing transaction because often crypto lib doesn't provide the byte encoding of the tx, only the hash.

I use the SEC uncompressed format for public key and compact uncompressed format for the signature.

It works the same way as @adastreamer explains in its PR #11469 .

### Usage
To create the key see PR #11469

To sign the message "123" for ETH (same way as PR #11469) :
`
curl -H "X-Vault-Token: root" -X POST http://127.0.0.1:8200/v1/transit/sign/eth-test -d '{"input":"MTIz","hash_algorithm":"keccak-256"}'
`

`
{"request_id":"950295c2-da8f-f896-471b-d22a3f5276ec","lease_id":"","renewable":false,"lease_duration":0,"data":{"key_version":1,"public_key":"BOCxfRcUFsbK/6uy1Xy0ZY0dGZhVUK+lJ0piQ64LGT6pA65RPqibvMTS1Cgy5DeOVxiKczmKxQd5Dcs2bpSZf6c=","signature":"vault:v1:1b3a644ab2aa3c51b16f210ed7128fa36a1f3a087ac7ddf2efaef9ac94a633ffcb5de789812233e738e650365859225bfdf66110baaf7b04098d7b49214054e550"},"wrap_info":null,"warnings":null,"auth":null}
`

To sign the message "123" for BTC it's a little more complicated because BTC use a message digest that must be added. For "123" it become in base64: "GEJpdGNvaW4gU2lnbmVkIE1lc3NhZ2U6CgMxMjM="
`
curl -H "X-Vault-Token: root" -X POST http://127.0.0.1:8200/v1/transit/sign/eth-test -d '{"input":"GEJpdGNvaW4gU2lnbmVkIE1lc3NhZ2U6CgMxMjM=","hash_algorithm":"double-sha2-256"}'
`

`
{"request_id":"7483cea7-f27e-c3ec-37de-4b338a74f2b5","lease_id":"","renewable":false,"lease_duration":0,"data":{"key_version":1,"public_key":"BOCxfRcUFsbK/6uy1Xy0ZY0dGZhVUK+lJ0piQ64LGT6pA65RPqibvMTS1Cgy5DeOVxiKczmKxQd5Dcs2bpSZf6c=","signature":"vault:v1:1b1c3fc1d32f14740a283fba9e1f5a8231627333464e9aca68bae365cc908a51af6d738f58dda391d80fd4348a9eaba0cce074b94252d25ae431f21f7379981651"},"wrap_info":null,"warnings":null,"auth":null}
`

To sign the message already hashed for any use, send the hashed message in basae64:
`
curl -H "X-Vault-Token: root" -X POST http://127.0.0.1:8200/v1/transit/sign/eth-test -d '{"input":"ZOYEeHy/GUhB57aNfNKHhvbJoKOrn4sKDofLQ4erAQc=","hash_algorithm":"none"}'
`

### Convert public key to address
I propose some code to get the address from public key:

##### ETH
```go
import (
    "fmt"
    "encoding/hex"
    "golang.org/x/crypto/sha3"
    ethcrypto "github.com/ethereum/go-ethereum/crypto"
    "encoding/base64"
)

    sign_pub_key := "BOCxfRcUFsbK/6uy1Xy0ZY0dGZhVUK+lJ0piQ64LGT6pA65RPqibvMTS1Cgy5DeOVxiKczmKxQd5Dcs2bpSZf6c="

    //Eth address extraction from public key
    publicKey_byte, _ := base64.StdEncoding.DecodeString(sign_pub_key)   
    //hash the public key
    algo_sha3 := sha3.NewLegacyKeccak256()
    algo_sha3.Write(publicKey_byte[1:])
    pubaddr := algo_sha3.Sum(nil)[12:]
    //convert to 0x addr
    enc := make([]byte, len(pubaddr)*2+2)
    copy(enc, "0x")
    hex.Encode(enc[2:], pubaddr)
    eth_address := string(enc)
    fmt.Println("ETH Address fromp pub key:", eth_address)

```
##### BTC
```go
import (
    "fmt"
    "github.com/btcsuite/btcutil"
    "github.com/btcsuite/btcd/chaincfg"
    "encoding/base64"
)
 sign_pub_key := "BOCxfRcUFsbK/6uy1Xy0ZY0dGZhVUK+lJ0piQ64LGT6pA65RPqibvMTS1Cgy5DeOVxiKczmKxQd5Dcs2bpSZf6c="

        //get BTC address
        publicKey_byte, _ := base64.StdEncoding.DecodeString(sign_pub_key)   
        caddr, _ := btcutil.NewAddressPubKey(publicKey_byte, &chaincfg.MainNetParams)
        fmt.Println("BTC Address:", caddr.EncodeAddress())

```

### Convert signature
For the signature to adapt to blockchain

##### ETH
```go
import (
    "fmt"
    "encoding/hex"
)

    sign :=   "1b3a644ab2aa3c51b16f210ed7128fa36a1f3a087ac7ddf2efaef9ac94a633ffcb5de789812233e738e650365859225bfdf66110baaf7b04098d7b49214054e550"

    //generate ETH signature from sign
    signature_byte, _ := hex.DecodeString(sign)
    //Uncompressed signature: first sign byte contains the V value encoded for BTC {27,28}. Convert it to ETH: {0,1}
    var v byte
    if signature_byte[0] == 27 {
        v = 0
    } else {
        v=1
    }
    eth_signature_byte := append(signature_byte[1:],v)
    //add Ox
    enc = make([]byte, len(eth_signature_byte)*2+2)
    copy(enc, "0x")
    hex.Encode(enc[2:], eth_signature_byte)
    eth_signature := string(enc)
    fmt.Println("#### ETH signature:", eth_signature)

```
##### BTC
The signature is already compatible with btc.

### Verify
The message is "123".

For ETH, I use the same site as the PR #11469 .
The code provided generate these address / signature:
```
ETH Address from pub key: 0xcb9748e46681cfd8650ea37de22bfb2230607c88
ETH sign: 0x3a644ab2aa3c51b16f210ed7128fa36a1f3a087ac7ddf2efaef9ac94a633ffcb5de789812233e738e650365859225bfdf66110baaf7b04098d7b49214054e55000
```

For BTC  I use [tools.bitcoin.com](https://tools.bitcoin.com/verify-message/) with the signature encoded in base64
The code provided generate these address / signature:
```
BTC Address from pub key: 17fuDbPKKpAGM4LABFr6XSpyBY2VGKXA8y
BTC sign b64: Gxw/wdMvFHQKKD+6nh9agjFiczNGTprKaLrjZcyQilGvbXOPWN2jkdgP1DSKnqugzOB0uUJS0lrkMfIfc3mYFlE=
```

Any feedback and review are really appreciated.

Best

### CODE REVIEW

**Comment by hsimon-hashicorp** [comment]
Hi @musitdev - can you expand upon what the use case would be for this, and what problem it would solve? Thanks!

**Comment by musitdev** [comment]
Our use case is to sign a message or a transaction for BTC or ETH blockchain using the key store inside Vault. I can detail with 2 scenarios:
 * The wallet private key use in an server application is stored in Vault. I generate a raw transaction and use the Vault to sign it. I send the raw Tx and the signature. It allow to send Tx by a server process.
  * A smart contract process incoming data and validate them to call other contract or do some action. It use data signature to validate the origin. The data are signed using Vault.

For automatic blockchain process that can be restarted and must be keep alive, with this patch Vault can be used to store private key on the cloud for example.

Hope it help to understand our needs.
best

**Comment by hsimon-hashicorp** [comment]
Hello! Vault has no plans to implement this in the foreseeable future, but it is an open source product, so please feel free to fork it to develop for your needs.

**Comment by glehmann** [comment]
@hsimon-hashicorp I'm not sure to understand why this PR is being rejected. In that case the feature is implemented, so I guess it's being rejected for another reason — I can think of a lot that would make sense like maintenance, security review etc.

Could you be more specific on the reasons why this is being rejected, so we can adjust the contributions we are planning to make to vault accordingly?

**Comment by hsimon-hashicorp** [comment]
As mentioned, there are no plans to implement cryptocurrency or blockchain support into Vault at this time, but we encourage people to fork Vault and implement it if they choose. We do continue to encourage PRs that are more generic in scope, ie, implementing cryptographic algorithms, that are not specific to cryptocurrencies or blockchain. Thanks!

**Comment by glehmann** [comment]
Ok, it's kind of sad for us, as we use a lot vault in blockchain use cases, and this was a chance to contribute a feature we think very interesting in that context.

We'll probably do as you suggest and maintain a vault fork with that feature.

If anybody comes here with a non-blockchain use case for that feature in vault, please leave a comment!

Thanks

**Comment by ncabatoff** [comment]
> We'll probably do as you suggest and maintain a vault fork with that feature.

@glehmann FYI a less drastic option would to be to fork transit itself (or just the bits of it that are relevant to your use cases) and maintain it as an external plugin.

**Comment by intech** [comment]
We have closed source plugin (separate from Transit) for Vault with support Ethereum and Bitcoin like networks as a part of our custodial solution. We choice such implementation to not support backward compatibility with original source code of Transit.
We have plan to open source our plugin for community. If you are interested in or have any questions contact at tg: [@GeekHack](https://t.me/GeekHack)

**Pull request closed without merging**
