### PR TITLE
website: catch up stable-website

### PR DESCRIPTION
**Pull request by zchsh**
This PR catches `stable-website` up, as it looks like some recent commits to `main` failed to be cherry-picked automatically

### CODE REVIEW

**Review by jescalan — APPROVED** [review]

**Comment by kalafut** [comment]
@ncabatoff I see we had marked the license docs for cherry picking. Was that deliberate? I don't recall updating public docs for RC content before.

**Comment by ncabatoff** [comment]
> @ncabatoff I see we had marked the license docs for cherry picking. Was that deliberate? I don't recall updating public docs for RC content before.

It was a mistake, which happily failed.

**Comment by kalafut** [comment]
@zchsh Can you un-cherrypick the "Docs for license autoloading" changes?

**Comment by zchsh** [comment]
@kalafut Absolutely, thanks for catching this! Have also pulled in another commit from https://github.com/hashicorp/vault/pull/11930 as cherry-pick failed there as well.

**Review by kalafut — APPROVED** [review]

**Pull request merged**
