### PR TITLE
docs: fix PKI revocation configuration link

### PR DESCRIPTION
**Pull request by jkirschner-hashicorp**

### CODE REVIEW

**Comment by cipherboy** [comment]
@jkirschner-hashicorp I'd rather add an anchor into the HTML and restore the old title that way. See e.g. 

https://github.com/hashicorp/vault/blame/dccc749c31b7ae6c94656f104137cd43231bb1d8/website/content/api-docs/secret/pki.mdx#LL200C4-L200C8

**Comment by jkirschner-hashicorp** [comment]
Makes sense. I just wanted to point out that the current anchor tag doesn't go anywhere, and wasn't sure the history of the changes / what it should be.

**Comment by cipherboy** [comment]
Yeah, originally it had just stuff related to CRLs, but then we added OCSP and some other stuff, so we renamed it and I did so carelessly lol. :D

**Comment by cipherboy** [comment]
Superseded by #17959

**Pull request closed without merging**
