### PR TITLE
Update Go version to 1.16.15

### PR DESCRIPTION
**Pull request by cipherboy**
`Signed-off-by: Alexander Scheel <alex.scheel@hashicorp.com>`

### CODE REVIEW

**Comment by calvn** [comment]
I see that we include changelog entries on go version upgrades. Should we do so in this case as well?

**Comment by cipherboy** [comment]
@calvn This PR has an entry: https://github.com/hashicorp/vault/pull/15064/files#diff-273a5bc507d92c5e8a4d96bfeff603dd0334f7857565689be28cc8168c7207a8 

Just note that the checking helper expects the old format; I haven't backported https://github.com/hashicorp/vault/pull/15060. 

This means it'll err because it expects the `15064.txt` format rather than the new `go-ver-SOMETHING.txt` format.

Hence, the label :-)

**Review by mladlow — APPROVED** [review]
The changelog entry looks right. Everything else looks _probably_ right and I'm assuming you grepped but I did not. There's a ton of places to update.

**Comment by cipherboy** [comment]
Second grep on a fresh date showed nothing new. Will do the OSS->ENT merge now. Thanks @mladlow!

**Pull request merged**
