### PR TITLE
Fix swallowed error in vault package.

### PR DESCRIPTION
**Pull request by alrs**
I found an error in the vault package that was being ignored.

### CODE REVIEW

**Comment by jefferai** [comment]
@vishalnayak do you remember if we left that out on purpose because it was super duper spammy to the return? (so letting it fall through to the te being nil case). If so we should just set it to `te, _` instead of fetching the error and then ignoring it.

**Comment by alrs** [comment]
I'm happy to make that change once @jeffrai and @vishalnayak reach consensus.

**Comment by vishalnayak** [comment]
Not recalling us leaving this out on purpose. I am inclined towards accepting this change as I don't foresee a lot of errors while looking up a token.

**Comment by alrs** [comment]
@jefferai: it looks like @vishalnayak is on board, so I reckon this is ready to be merged.

**Comment by jefferai** [comment]
Thanks!

**Pull request merged**
