### PR TITLE
Support for MongoDB as physical backend

### PR DESCRIPTION
**Pull request by mheese**
Hey guys,

I have been developing support for mongo as physical storage backend. I have been quite happy that it was actually quite easy and straight forward to implement - with the exception of the HA part, unfortunately.

It has one special feature for HA: you can configure vault to step down if a particular mongo primary goes down, and let it participate in Lock() competition only if a certain mongo server of a replica set is the primary.

I also updated the documentation in the repo, and added a unit test file which basically reuses the existing backend tests.

I have two questions so far with regards to the `Lock()` mechanism in the Lock interface (`physical/physical.go`):
1. why is there a special "read" lock? and why has it the same key/path, but this special value? I kind of needed to make a special case for that, and I kind of want to understand what exactly the purpose of this is.
2. my unit test will fail at line 251 (`physical/physical_test.go`) because the lock acquisition attempt is faster than the 50ms that is waited before the `stopCh` is closed. Am I handling it wrong? Or is that just a problem with the unit test?

Let me know what you guys think about everything!

Cheers
Marcus

### CODE REVIEW

**Comment by jefferai** [comment]
I think one important step would be defining what is different about this code vs https://github.com/hashicorp/vault/pull/790. Just HA?

As some initial feedback, I'm not sure we'd add any new HA implementations right now, given that two of the existing implementations don't work well and nobody has stepped up to fix them. I'd need to poll around internally and see what the feeling is.

**Comment by mheese** [comment]
@jefferai , after reading through https://www.consul.io/docs/internals/sessions.html, http://research.google.com/archive/chubby.html and some source code of consul and vault, I finally understand how that locking mechanism is supposed to work + I have an improvement idea on the HA failover with mongo.

I will close this PR and reopen it when I fixed that. If you can give me some feedback from your internal poll in the meantime, I'd appreciate that.

**Comment by jefferai** [comment]
Hi @mheese ,

We're open to merging this but we will have the HA functionality disabled by default, so it's opt-in. That's similar to what we did with Dynamo and we will likely also do that for etcd and ZK at some point in the future.

It just puts an extra check on people relying on functionality for consistency that we at HC are not running ourselves and where we don't actively have a hand in the development of the software providing the locks.

**Comment by mheese** [comment]
Hi @jefferai,

that is awesome news! And I can totally understand the opt-in attitude for HA. That is actually already the default currently.

I made some progress in the meantime as well on the backend and it is now completely passing all the unit tests, as well as the HA functionality is now a lot faster as well.

I still need to fix the issue with the Travis build, and I'll reopen the PR once I have figured that out.

**Comment by jefferai** [comment]
Neat! I can't promise this for 0.6.2, because we have quite a few tasks for that already and limited time before HashiConf but the release after should be good if not.

**Comment by mheese** [comment]
@jefferai I need to create a new PR ... github doesn't allow me to change the source branch.

**Comment by mheese** [comment]
created #1847 as follow up for this

**Pull request closed without merging**
