### PR TITLE
Add tokenGroups and tokenGroupsGlobalAndUniversal

### PR DESCRIPTION
**Pull request by sbutler**
Using tokenGroups* in Active Directory can greatly speed up
nested group membership resolution, but the process is more
complex. Because these are constructed attributes you can
only retrieve them by a ScopeBase search on the UserDN requesting
the attribute explicitely.

Additionally, tokenGroups* values are binary SIDs. You have
to resolve each SID to a group entry.

But in a large directory this is the only working way to get
a nested group membership in reasonable time. The chained
matching rule doesn't already complete before the timeout.

### CODE REVIEW

**Comment by sbutler** [comment]
I don't think tokenGroups is supported in other LDAP server products. And if they were, they'd have to have the same concept/format of SIDs as AD.

**Comment by tyrannosaurus-becks** [comment]
@sbutler ok, that makes sense, that's what I was thinking too but wanted to check. 

What kind of speed gain are you seeing with this code? You mention it greatly speeds up nested group resolution. 

I'm asking because based on that, I'll take it back to the Vault eng team and discuss whether it would make sense to diverge the non-AD vs. AD code to add the speedup.

**Comment by sbutler** [comment]
Our AD currently has over 750,000 group objects. If we try to configure as suggested in the docs using LDAP_MATCHING_RULE_IN_CHAIN then group membership search never completes in the timeout period.  We can try limiting to a special OU with aliases for the various groups we're told we need, but this is unmanageable due to the decentralized nature of IT in our organization.

Using tokenGroups gets the correct result within a second or two.

**Comment by tyrannosaurus-becks** [comment]
@sbutler ah, thank you! Expect to hear more about it tomorrow afternoon Pacific time.

**Comment by tyrannosaurus-becks** [comment]
@sbutler actually it will likely be Friday afternoon.

**Comment by tyrannosaurus-becks** [comment]
@sbutler so we chatted about this and would love to add functionality that brings such a significant speedup. We're thinking the best way to do it would be by putting it behind a feature flag of `use_token_groups` which would be a boolean and would default to false. 

- The flag would be at a config level, so it'd need to originate [here](https://github.com/hashicorp/vault/blob/d150cafbab811f9c2ae25dacdc0382619f4406f3/builtin/credential/ldap/path_config.go#L15). [Here](https://github.com/hashicorp/vault/blob/master/builtin/logical/pki/path_roles.go#L52) is an example of how you add a field. 
- Then it would need to be pulled out and stored on the config.
- Then it would be used [here](https://github.com/hashicorp/vault/blob/d150cafbab811f9c2ae25dacdc0382619f4406f3/builtin/credential/ldap/backend.go#L135) to toggle whether we use the current method, or the new one.

**Comment by sbutler** [comment]
Sounds reasonable. I'll hack on it a bit and see what I can come up with.

**Comment by sbutler** [comment]
Requested changes added.

**Comment by sbutler** [comment]
Looks good! No objections from me.

**Pull request merged**
