### PR TITLE
Creating unique lock key for MySQLHALock in v1.5.0 (#8458/8499)

### PR DESCRIPTION
**Pull request by cjbaar**
This is an update to the ongoing discussions for issue #8458/PR #8499, regarding the locking mechanism when using MySQL as the HA backend. In short, the current lock key is set as a constant ('core/lock'), which means multiple vault installations are not able to share the same MySQL instance.

This is a re-write of the solution proposed by @pandeybk on 8499, and was branched from v1.5.0. It uses the database+table name to create a unique string for the lock. This implementation makes two changes from the previous version.

1) The unique string is generated on the &MySQLHALock struct, instead of the &MySQLLock struct. We found issues running the first version which would lose HA cohesion after 8 hours (the default MySQL session timeout in our environment).

2) The db+table string is hashed, to make sure the string does not overrun the 64-character limit for lock names (starting with 5.7)

### CODE REVIEW

**Comment by jzbruno** [comment]
Can we get someone to look at this? We would like to be able to run current versions of Vault but in our environment we need this fix.

**Comment by llivingstone** [comment]
+1 to this. 

Having one single MySQL instance w/ a database for each vault cluster is a cost effective solution for specific environments.

If i can help in anyway, please let me know.

**Comment by edshelton** [comment]
Same use case as @llivingstone here - would be great to see some traction on this!

**Comment by cjbaar** [comment]
@sgmiller Yes; as noted above, the hash ensures that the key itself will not exceed the limit of 64 characters in v5.7. If a user has long database and table names, it is possible the concatenation would go over 64 characters, which is why we decided to incorporate the hash.

**Comment by nandudheeraj** [comment]
+1

Very Much needed

**Comment by aftershockdan** [comment]
+1 we need this fix as well. Can we get this merged in and released soon please?

**Comment by banks** [comment]
Hi folks. I'm fully aware of how old this PR is but I'm trying to help get some of our backlog of things addressed.

I think I understand it all. I understand the hashing to avoid length issues. One question: is the fact the lock name is now opaque likely to be an issue? Like would it make it harder for a DB admin to work out which lock corresponded to which Vault instance and would that matter? I've not used locks in MySQL like this before so don't have a good intuition for that so any feedback from those of you here that do would be welcome!

If it is an issue, there may be some hybrid where you could do something like first and last 4 chars of both DB and table followed by random hash to avoid collisions and then most folks would get something partially human readable?

But happy to take your expert guidance on if that is a real issue.

I also think Brian's [concern on the original PR](https://github.com/hashicorp/vault/pull/8499#issuecomment-596035936) is still valid and will require more siginficant changes. It's not necessarily a reason to not merge this but I think it will need further work to avoid breaking every Vault+MySQL HA cluster on upgrade!

As far as I can tell there is no safe way to do a standard in-place rolling upgrade of a Vault cluster using MySQL storage if we merge this change. Any new clusters will be fine but upgrades would be very likely to end up split-brain (i.e. two active nodes at the same time) which can corrupt storage and even loose data 😱 . The only way I can see to make that 100% safe would be if we did a much more elaborate thing here where we introduce a new config to say "keep checking the old lock key too" and if that is set then we have to acquire _both_ keys to become active node.

With that it would still require operators to explicitly follow a correct procedure during upgrade:
 1. reconfigure each vault server with the new `also_check_old_lock_key=true` (or whatever we call it) setting.
 2. upgrade binary and restart
 3. complete process on each server in turn
 4. go back and remove `also_check_old_lock_key=true` and then restart each server in turn again.

This ensures that the first server you upgrade doesn't immediately grab the _new_ lock key and become active even though the previous active node is still leader under the old lock key.

The above would still be dangerous in that any users who didn't carefully read the upgrade notes would likely have their cluster split-brain during upgrade which they may or may not notice but could lead to corruption and data loss. For that reason I think it would need to be merged as opt-in behaviour only (i.e. by default we still use the old lock key so no surprises on upgrade) but only if you configure `instance_specific_lock_key=true` do we do the new behaviour in this PR. We'd _still_ need to have the "claim both locks" thing mentioned above to allow folks to migrate an existing cluster safely but at least those who don't need this won't have a nasty surprise. Or a lower-effort option would be to make it opt-in only but not bother with the double-locking thing and then document with huge warnings that it is never safe to change a cluster from opt-out to opt-in without taking it entirely offline (i.e. stopping all instances of Vault before changing the config and restarting)? Then folks with existing clusters would remain opted out and use the current Key safely, while new clusters could opt-in and share the same DB with new keys?

Is anyone here still interested in picking up that extra bit of work to make this safe to merge? If not for now perhaps we can document the requirements in the original issue and close this until there is someone who would like to take that on?

Thanks (belatedly 😢 ) @cjbaar for this great contribution and to all who have commented. I hope we can get it resolved one way or another soon!

**Comment by hsimon-hashicorp** [comment]
@cjbaar it has been several months since we requested more information - are you able to continue this effort? Would you like someone to get it over the finish line? Let me know. Thanks!

**Comment by cjbaar** [comment]
@hsimon-hashicorp  I haven't worked with this for over 3 years now. It was my understanding the PR was closed.

**Comment by hsimon-hashicorp** [comment]
> @hsimon-hashicorp I haven't worked with this for over 3 years now. It was my understanding the PR was closed.

Certainly understood - one of my main goals in my role is to prevent this sort of "PR decay" from occurring. I will check with the team on how they wish to handle this - sometimes we will fork a PR to finish it, while retaining credit for the original contributor. If that's not something you want, please do let me know. And thank you for the fast response!

**Comment by cjbaar** [comment]
Thanks. Whatever is easier for you is fine; I am not necessarily concerned with the credit.

**Comment by hsimon-hashicorp** [comment]
After discussion with engineering, I'm going to go ahead and close this PR out now. If you or another community member is interested in completing this work, please feel free to open a new PR. Thanks!

**Pull request closed without merging**
