### PR TITLE
Website spelling fixes

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Review by raskchanky — APPROVED** [review]

**Comment by raskchanky** [comment]
@scop Can you sign the CLA? Once you do, I think we can get this merged.

**Comment by aphorise** [comment]
@raskchanky - I've checked and half the correction from this PR are still pending while most have since been fixed. Regardless there are no merge conflict and I think this should be merged.

**Comment by hsimon-hashicorp** [comment]
> @raskchanky - I've checked and half the correction from this PR are still pending while most have since been fixed. Regardless there are no merge conflict and I think this should be merged.

Unfortunately the CLA hasn't been signed yet, and we can't merge any changes without that. Once @scop signs the CLA, I can merge this. Thanks!

**Comment by aphorise** [comment]
I think an exception should be made here - irrespective of CLA there are clear mistakes that are still existent in public docs that would require correction nonetheless and it's unlikely that the original author of the PR will ever respond.

@yhyakuna perhaps I can trouble you for a separate PR and we may then close this thereafter?

**Comment by yhyakuna** [comment]
Directory structure has changed since this PR was originally opened, and some of the typos no longer exists.  So, I opened [PR 16749](https://github.com/hashicorp/vault/pull/16749) and closing this.

**Comment by mladlow** [comment]
I got tagged on this PR and wanted to leave a note about the CLA. We **cannot** merge commits where contributors have not signed the CLA. It's a legal requirement.

**Pull request closed without merging**
