### PR TITLE
UI/fix flaky clients current test

### PR DESCRIPTION
**Pull request by hellobontempo**
Adds `waitUntil` to fix flaky test

Screen Shot 2022-03-11 at 12 09 50 PM

### CODE REVIEW

**Review by hashishaw — APPROVED** [review]
👏

**Comment by hashishaw** [comment]
Just one note: why does this need a backport?

**Comment by hellobontempo** [comment]
> Just one note: why does this need a backport?

Oh - I thought to mitigate flakiness in any PR that goes to 1.10? But am I thinking of that wrong?

**Comment by hashishaw** [comment]
> Oh - I thought to mitigate flakiness in any PR that goes to 1.10? But am I thinking of that wrong?

Wrong is a strong word 😄  Our general approach to backports is they're for fixes, and test updates/developer happiness isn't typically considered a fix. I think this a place where we should use discretion, and if the test is failing VERY often before this fix then maybe this is a good exception to our rule!

**Comment by hellobontempo** [comment]
> > Oh - I thought to mitigate flakiness in any PR that goes to 1.10? But am I thinking of that wrong?
> 
> Wrong is a strong word 😄 Our general approach to backports is they're for fixes, and test updates/developer happiness isn't typically considered a fix. I think this a place where we should use discretion, and if the test is failing VERY often before this fix then maybe this is a good exception to our rule!

Aha! Thank you. Now I'm remembering that we only backport fixes. _Completely_ spaced on this and was just in backport mode. Thanks for clarifying!

**Pull request merged**
