### PR TITLE
Typo fix: period rotation -> periodic rotation (in transit docs)

### PR DESCRIPTION
**Pull request by dhermes**

### CODE REVIEW

**Review by hsimon-hashicorp — APPROVED** [review]

**Comment by dhermes** [comment]
Same typo as in #12011.

**Comment by dhermes** [comment]
@hsimon-hashicorp Is this good to merge?

**Comment by hsimon-hashicorp** [comment]
@dhermes I'm working on authorization to merge pull requests. @ncabatoff can you nudge this along?

**Comment by ncabatoff** [comment]
Thanks @dhermes!

@hsimon-hashicorp, note that the `docs-cherrypick` label is only helpful when the PR is using a branch rather than a fork.  It doesn't break anything, but in the fork case, whether the label is present or not, we must manually cherrypick the commit onto the `stable-website` branch before the change will be visible on the web.

**Pull request merged**
