### PR TITLE
Adding HANA DB as a dynamic secret backend

### PR DESCRIPTION
**Pull request by Caiyeon**
This set of commits adds HANA db as a backend, allowing for dynamic database user creation much like other database integrations. 

In addition to the `name` and `password` fields in role configuration, there is also a `valid_until` field. If this field exists in the role SQL, credentials will be created with a SQL statement that sets the credential to be deactivated at `hana_server_time + backend_lease_time`. This allows HANA db to deactivate created accounts on-time, regardless of whether vault is available to attempt to revoke it. More info can be found in the help documents added in this PR.

Vendored dependencies:
* https://github.com/SAP/go-hdb
* https://github.com/golang/text (transitive, a dependency of go-hdb)

When I get a chance, I will take a look into the possibility of migrating this to the new plugin system. Unfortunately, for reasons outside my control, this is the set of changes I can submit for now.

Let me know if there's anything missing (other than plugin integration)

### CODE REVIEW

**Comment by jefferai** [comment]
Thanks for submitting this!

Unfortunately, we will not be merging any new standalone database backends. This will need to be converted to a plugin. It should be pretty straightforward though.

**Comment by Caiyeon** [comment]
Understandable. If the concept looks good, I'll start on migrating it to a plugin. It's just unfortunate that I have to start with a deprecated pull request :)

**Comment by jefferai** [comment]
Hi @Caiyeon ,

The concept looks great :-)

I do recommend, especially when working on major/large functionality, getting in touch ahead of time. That way we can let you know whether anything you'd be working on might be changed under the hood!

**Comment by jefferai** [comment]
Going to close this, but will eagerly wait a plugin-based version in a new PR!

**Comment by Caiyeon** [comment]
I was not allowed to disclose this until yesterday. I actually wrote the code 9 months ago haha

If I change this to plugin based, would you mind if I just added commits on top, and make another pull request?

**Comment by jefferai** [comment]
That is so unfortunate :-(

Yes, that would be fine!

**Pull request closed without merging**
