### PR TITLE
Adding tests to ensure all backends are mountable

### PR DESCRIPTION
**Pull request by chrishoffman**

### CODE REVIEW

**Comment by jefferai** [comment]
I don't think this solves the problem. As defense in depth it's fine, but I think we need something coming from outside to properly do this.

**Comment by chrishoffman** [comment]
@jefferai I just added a check for expected and actual backends.  This does go outside since it checks the known locations for builtin backends and plugins development and would have caught the nomad issue.

**Comment by jefferai** [comment]
It's not outside the repo. I think it's about as easy to miss 2 lines in a 30k line PR as 1. Ideally it'd be part of CI configuration in an outside repo. For defense in depth it's fine but we should try to still remember to set up a test from outside when we can.

**Comment by chrishoffman** [comment]
I think this is going to help a little bit by moving the factory mappings to the top of the file and out of the command definition but I get your point.

**Pull request merged**
