### PR TITLE
Fix DB root rotation replication issue

### PR DESCRIPTION
**Pull request by michelvocks**
Related PR https://github.com/hashicorp/vault/pull/8105

Fixes a bug that allows secondaries/performance standby's to rotate root DB credentials.

### CODE REVIEW

**Comment by briankassouf** [comment]
Maybe we should get this merged so it can be used here and in your other PR? https://github.com/hashicorp/vault/pull/7175

**Comment by kalafut** [comment]
#7175 is now merged.

**Comment by michelvocks** [comment]
Thanks @kalafut & @briankassouf! Done

**Comment by briankassouf** [comment]
I think we should get this in for 1.3.2

**Pull request merged**
