### PR TITLE
Adding the CLI flag placement info

### PR DESCRIPTION
**Pull request by yhyakuna**
This is to resolve the [Asana task](https://app.asana.com/0/157256879238414/959593948077948/f). 

I added the following in the [Vault Commands (CLI)](https://www.vaultproject.io/docs/commands/index.html) doc: 

screenshot

The help text already describes the command usage, but it wouldn't hurt to re-emphasize the order. As far as I know, there is nothing special about the `-namespace` and `-path` flags, so I didn't explicitly call out the two.  

I updated the login doc a little, but again, its help text already explains the command usage. 

@lauradiane @amanoske  Would this be good enough, or is there anything I missed?

### CODE REVIEW

**Comment by yhyakuna** [comment]
@chrishoffman  Does the following definition sound accurate to you?

```
`options` - CLI flags to specify additional settings (e.g. display the command output in JSON format)    

`args` - Request parameters specific to the command operation (equivalent to the parameters you set when invoking Vault API)
```

This would look like:

screenshot

**Comment by sethvargo** [comment]
Could we just call options "flags" since that's really what they are? I don't see the value in adding another name. I think "args" is fine.

**Comment by yhyakuna** [comment]
@sethvargo  For this PR, I'm trying to be consistent with CLI help text.  

```
$ vault operator init -h
Usage: vault operator init [options]
...

$ vault token -h
Usage: vault token <subcommand> [options] [args]
```

**Comment by sethvargo** [comment]
Hmm fair enough. I can't argue much since I wrote that CLI 🤷‍♂️

**Pull request merged**
