### PR TITLE
Add debug flag to dump requests and responses on the CLI

### PR DESCRIPTION
**Pull request by jmcshane**
Adding debug flag and environment variable to output API debug information using the `httputil` library to print the request and response information to the command line.

### CODE REVIEW

**Comment by jefferai** [comment]
We will have to talk internally about whether or not we want this feature, stay tuned.

**Comment by jmcshane** [comment]
@jefferai not a problem, I saw the issue out here and put together this for an initial review. thanks for maintaining this project!

**Comment by jefferai** [comment]
My main concern here is that this doesn't actually print the `curl` command to use but rather prints a dump of the entire request and response; to me it seems like `curl` already does that well so rather than put in dumping into the CLI, printing the alternative `curl` command and letting it do the job is the better way.

However, the reason the other issue wasn't scheduled is that we're not sold yet on whether it's a good idea to have a mode that prints `curl` commands, because it can open up the possibility of someone easily forcing someone else to reveal login info on the command line by setting an env var when they're not looking. Combine that with session recording or shoulder surfing and it's a very easy way to grab credentials.

**Comment by jefferai** [comment]
Closing for now.

**Comment by abstrctn** [comment]
Apologies for commenting on a closed issue, but just to comment on the possible design for this feature, printing out the full http response (as opposed to a curl command) seems like the approach most other CLIs I've used take, and might more closely fit users' expectations about a debug flag.

For reference, I believe this is how debug flags are implemented in `gcloud`, `aws-cli` and `gsutil`. (Though I understand the data transmitted with vault would tend to be more sensitive.)

Plus, the headers or data a user is looking for might only exist in the response, and wouldn't show up in a curl representation of the request.

**Comment by jefferai** [comment]
Yeah, the sensitivity of Vault data is an issue here. I'd be worried about triggering this behavior via env vars for instance where the user may not realize it's set. _Maybe_ if it's limited purely to a CLI flag.

**Pull request closed without merging**
