### PR TITLE
Add a convenience function for copying a client

### PR DESCRIPTION
**Pull request by sethvargo**

### CODE REVIEW

**Comment by jefferai** [comment]
Looks fine, one request: it's a bit more Go-ish (although I don't know about HC-ish) to use `Clone()` instead of `Copy()`

**Comment by sethvargo** [comment]
@jefferai updated

**Comment by jefferai** [comment]
Any reason to ignore the error? I'd just have the Clone function return `(*Client, err)` the way `NewClient` does.

**Comment by sethvargo** [comment]
@jefferai a few reasons:

1. It should never fail. If we already have a client, making a copy of that client should always be successful
1. It makes it much easier to "chain" `client.Clone().Logical()`

I wouldn't be opposed to panicing if the clone fails, but it feels a bit weird to return an error here.

**Comment by jefferai** [comment]
Copying a client requires making calls (for instance to `http2.ConfigureTransport` that can error. So either we'd have to swallow that error, or deal with it somehow.

**Comment by sethvargo** [comment]
@jefferai okay updated

**Comment by jefferai** [comment]
Thanks!

**Pull request merged**
