### PR TITLE
Fixing namespaces create/delete commands

### PR DESCRIPTION
**Pull request by chrishoffman**

### CODE REVIEW

**Comment by jefferai** [comment]
What is the problem this fixes?

**Comment by chrishoffman** [comment]
```
$ vault namespace create -ns=ns1 ns2
Error creating namespace: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/namespaces/ns1/ns2
Code: 400. Errors:

* "/" is not allowed in namespace names
$ vault namespace create -ns=ns1/ ns2
Error creating namespace: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/sys/namespaces/ns1/ns2
Code: 400. Errors:

* "/" is not allowed in namespace names
```

**Comment by vishalnayak** [comment]
@chrishoffman I wasn't able to reproduce the problem and AFAIK we don't need to remove the lines that you have removed. Curious to know if your terminal has any weird thing set that is affecting this.

**Comment by jefferai** [comment]
I was just able to reproduce it, but I wasn't able to reproduce it yesterday when doing all the CG repro scripts.

**Comment by jefferai** [comment]
Closing in favor of backporting

**Pull request closed without merging**
