### PR TITLE
chore: fix deprecated ioutil readall

### PR DESCRIPTION
**Pull request by idnandre**
### Description
After Go 1.16, function ioutil.ReadAll is deprecated and may be removed from future versions of Go. Go recommend to change ioutil.ReadAll into io.ReadAll. 
Also, in another file like this https://github.com/hashicorp/vault/blob/main/api/auth/approle/approle.go#L175  it already use io.ReadAll. So this PR will change deprecated function and make all code use io.ReadAll instead of ioutil.ReadAll.

Ref : https://pkg.go.dev/io/ioutil@go1.22.0#ReadAll

### TODO only if you're a HashiCorp employee
- [ ] **Labels:** If this PR is the CE portion of an ENT change, and that ENT change is
  getting backported to N-2, use the new style `backport/ent/x.x.x+ent` labels
  instead of the old style `backport/x.x.x` labels.
- [ ] **Labels:** If this PR is a CE only change, it can only be backported to N, so use
  the normal `backport/x.x.x` label (there should be only 1).
- [ ] **ENT Breakage:** If this PR either 1) removes a public function OR 2) changes the signature
  of a public function, even if that change is in a CE file, _double check_ that
  applying the patch for this PR to the ENT repo and running tests doesn't
  break any tests. Sometimes ENT only tests rely on public functions in CE
  files.
- [ ] **Jira:** If this change has an associated Jira, it's referenced either
  in the PR description, commit message, or branch name.
- [ ] **RFC:** If this change has an associated RFC, please link it in the description.
- [ ] **ENT PR:** If this change has an associated ENT PR, please link it in the
  description. Also, make sure the changelog is in this PR, _not_ in your ENT PR.

### CODE REVIEW

**Comment by hsimon-hashicorp** [comment]
Hi there! Can you provide more context around this PR, please? Is there a reported issue we can link to? Thanks!

**Comment by idnandre** [comment]
Hi @hsimon-hashicorp 
I'm already add some context in the description.
This PR not have linked issue, should I create an issue for this PR?

Thank you.

**Comment by hsimon-hashicorp** [comment]
> Hi @hsimon-hashicorp I've just added some context in the description. This PR not have linked issue, should I create an issue for this PR?
> 
> Thank you.

Thank you so much for adding the context requested! For PRs we do request that there be an open issue that can be linked where discussion about the problem and solutions can be discussed, however, I can say for sure that we appreciate these efforts to help with the housekeeping, care, and feeding, of Vault. For dependency updates, there's less of an outright need for a linked issue, but I definitely do appreciate the extra context in the PR as it helps me prioritize the PR with our engineers.

Thank you again for your contribution! I'm in contact with our engineers about it now. :)

**Review by stevendpclark — APPROVED** [review]
Thanks for the contribution @idnandre. Looks good to me.

**Pull request merged**
