### PR TITLE
Don't require every test to specify a VaultLicense field

### PR DESCRIPTION
**Pull request by ncabatoff**

### CODE REVIEW

**Review by stevendpclark — APPROVED** [review]
LGTM, I'm assuming we have no real use-case to use docker based tests without a loaded license in our CI?

**Comment by ncabatoff** [comment]
> LGTM, I'm assuming we have no real use-case to use docker based tests without a loaded license in our CI?

I suppose if we wanted to test that they failed without one?  I'm happy to cross that bridge when we come to it, unless you have a suggestion in mind.

**Review by cipherboy — APPROVED** [review]
Many thanks @ncabatoff!

**Comment by stevendpclark** [comment]
> > LGTM, I'm assuming we have no real use-case to use docker based tests without a loaded license in our CI?
> 
> I suppose if we wanted to test that they failed without one? I'm happy to cross that bridge when we come to it, unless you have a suggestion in mind.

Nope no suggestions and more than happy to re-visit this later if we really need it. I'd rather not have to remember setting up the license manually for new tests as you've done here.

**Pull request merged**
