### PR TITLE
Docker build environment support

### PR DESCRIPTION
**Pull request by sthysel**
Adds basic docker container based build and deploy environment.

### CODE REVIEW

**Comment by ekristen** [comment]
Hey @sthysel glad to find another docker user! 

I'm not sure I'd recommend this approach. Instead of just needing docker, you need docker-compose with this too, at the same time, the image you've suggested building is going to be unnecessarily larger because you are adding build-essential and git and cloning this repo into the image, which since you need the source locally anyways, doesn't make a lot of sense. I'd suggest you take a look at how docker-machine does it, and or look at my PR link below. 

I added docker build capabilities in this PR, just good for thought.

PR: https://github.com/hashicorp/vault/pull/460
Docker-Machine: https://github.com/docker/machine

**Comment by sthysel** [comment]
Hi Erik, thanks for the heads-up, did not think to check if someone already did a docker thing. My intention for the image was more a generic "get the ball rolling" start that could be used for both dev and test deploys. I guess I assumed that people would tune the image as they see fit.

Anyway, thanks for the feedback.

**Comment by ekristen** [comment]
I think your idea was great, every project should have a way to build with docker! :)

I just wanted to point out a few things I thought you might want to improve upon. 

It would be nice to see the project get an official docker image to!

**Comment by jefferai** [comment]
Hi,

Thanks for both sending over possible Docker build methods. One of the challenges with Docker is that everyone has their own preferred way of building an image. This includes me  :-)  My preference would be to keep the container as simple and minimal as possible, which reduces any attack surface. A container containing /bin/sh is a container that can run arbitrary code. Among other things, this means that ideally you wouldn't be compiling Go within a container; since Go binaries are statically compiled my preference is to have only the minimal set of things around the binary as is absolutely necessary.

So, my suggestion to you would be to look at https://github.com/CenturyLinkLabs/golang-builder and https://github.com/aerofs/gockerize -- I've used the former quite successfully, but not the latter as the latter is more recent -- and see if you can come to a consensus about which is nicer to use; or, whether you have specific concerns about landing on one of these tools. Be sure to read the part about SSL verification at the bottom of golang-builder, such a comment might apply to both.

Also, bonus points for providing Packer files to build a Vault Docker container with the eventual solution. :-)

**Comment by ekristen** [comment]
As I think we've already determined there are two separate needs. 1) building a docker image that runs vault, and 2) using docker to cross platform build vault.

This PR I suppose address number 1 while https://github.com/hashicorp/vault/pull/497 address number 2.

Honestly building an image to run vault should be simple and should stay away from all the images you suggested mainly because they aren't needed. There is no need to copy the source into the image and compile it when you are looking to run vault, it adds more weight to the image than needed. For example take the following Dockerfile for example. It is based on alpine 5mb image, adds support for 64 bit binaries, copies in the vault binary and it is done.

```
FROM alpine:3.2
RUN apk --update add curl && \
    curl -Ls https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk > /tmp/glibc-2.21-r2.apk && \
    apk add --allow-untrusted /tmp/glibc-2.21-r2.apk && \
    rm -rf /tmp/glibc-2.21-r2.apk /var/cache/apk/*
ADD https://github.com/hashicorp/vault/releases/download/v0.2.0.rc1/linux_amd64.zip /tmp/vault.zip
RUN cd /bin && unzip /tmp/vault.zip && chmod +x /bin/vault && rm /tmp/vault.zip
ENTRYPOINT ["/bin/vault"]
```

This results in roughly a ~32mb image, not going to get much smaller than that. 

The Dockerfile should just be updated to match the latest release and be tagged as latest and as the specific version, if we put that as the Dockerfile in this repo, then it can be a trusted build in the docker registry.

**Comment by jefferai** [comment]
Copying over my comment from #497:

====
I'm not sure those are two separate goals. Any official image provided to the Docker Hub should reflect best practice, and if it is best practice there's not much reason to have official scripts/support for building a Docker container that are divergent.
====

I don't particularly see the need for an Alpine base container, with a full package manager and busybox. Just more binaries that someone can use if they manage to break out of Vault or break into the container. I especially dislike the idea of pulling unofficial, unsigned/untrusted glibc into it -- there's simply no way to justify having that as part of an official Trusted Build for a security-conscious product.

**Comment by ekristen** [comment]
> Any official image provided to the Docker Hub should reflect best practice, and if it is best practice there's not much reason to have official scripts/support for building a Docker container that are divergent.
I'm really not sure what you mean by all this, but back to my previous comments, there are 2 use cases at hand. The first being a need for a Dockerfile to be used as a trusted build to allow someone to download and run vault in docker, the second is a more efficient and clean way to build vault binaries using docker containers. https://github.com/hashicorp/vault/pull/497 satisfies the building of docker binaries, it does not satisfy the trusted build Dockerfile.

My comments earlier with the example alpine base image, glibc, was an example of how the trusted image build could be done, obviously you took issue with the glibc, which I'm sure could be taken care of, but the point of it was that it should not build from source, you'd be unnecessarily bundling go lang compilers and the source and other unnecessary files make the image larger than it needs to be. 

> I don't particularly see the need for an Alpine base container
Alpine is the smallest and most lightweight base image available to date.

> with a full package manager and busybox. Just more binaries that someone can use if they manage to break out of Vault or break into the container. 
Unless you plan to roll your own linux base image container, every one ubuntu, centos, alpine, etc are all going to have a shell and are all going to have a full package manager

>  I especially dislike the idea of pulling unofficial, unsigned/untrusted glibc into it -- there's simply no way to justify having that as part of an official Trusted Build for a security-conscious product.
I understand the hestitation, just because it is unsigned doesn't mean it is a problem, however there is probably another way to handle it. Gliderlabs has a great write up on glibc and alpine (http://gliderlabs.viewdocs.io/docker-alpine/caveats/)

**Comment by jefferai** [comment]
>  the second is a more efficient and clean way to build vault binaries using docker containers

Needing a way to cross-compile Vault binaries in Docker containers isn't a clear need outside of niche circumstances. It is arguable whether this method is cleaner, and it is certainly not more efficient -- the existing build system runs cross builds in parallel without requiring extra time and resources to spin up a Docker container.

> Alpine is the smallest and most lightweight base image available to date.

It isn't. It is probably the smallest and most lightweight base image with a package manager and shell/busybox. It is possibly the smallest base image you can use to _build_ a working Vault _exclusively from within a Dockerfile_. So perhaps in theory it is the smallest base image that can be used to create a Trusted Build without any external tooling to supply the Vault binary.

For many languages this may be the right approach. But Go binaries are statically compiled -- they don't need even what minimal amount Alpine brings to the table, and this is where it creates a problem. The tools I pointed you to before use and/or create images that contain the bare minimum necessary to successfully run a statically compiled binary. (There is also, of course, Packer!) They use the official `scratch` no-op base image and build in only what's needed. The downside to this approach is that Vault must be built externally, but the upside is that there is absolutely nothing in the container that isn't explicitly necessary. The attack surface is basically "Vault", and even if they manage to own Vault they can't really do anything on the filesystem.

A Trusted Build indicates that the project believes that this is the correct way for the Docker container to be built -- but you can probably guess from above that for a project holding security as its top priority it doesn't seem like any pure Dockerfile-based approach is actually the correct way, with the possible exception of a Dockerfile that goes into a known base image and `rm -rf`s huge portions of it -- a process that would be prone to various other problems.

So this gives two choices for the project: have a Trusted Build with security tradeoffs that we don't actually recommend; or, forego providing a Trusted Build in favor of adding extra ways to easily build minimal Docker containers locally (for instance a `make gockerize` target).

I will spark an internal discussion about this, but my personal vote in the matter would be to forego a Trusted Build until we can figure out a way to do it that doesn't have known security problems.

**Comment by ekristen** [comment]
@jefferai great response.

> Needing a way to cross-compile Vault binaries in Docker containers isn't a clear need outside of niche circumstances.

I disagree, but that is ok :) I think its a quick and simple way for anyone with docker to easily hack on code and compile the project. 

> It isn't. It is probably the smallest and most lightweight base image with a package manager and shell/busybox.

You are correct.

You've mentioned it being a security tool and wanting to reduce the surface attack area. I'm a security guy too so I'm all for reducing the surface area for an attack. If that is the case why even provide compiled versions for window, osx, and linux, these operating systems have a much **larger* surface attack area than a container running vault as PID 1 that just happens to have  busybox and a package manager inside the container as well.

I don't think using alpine/ubuntu as a base image is security trade-off, no more than allowing anyone to run vault on any existing operating system to which vault has been released for.

You've also mentioned wanting a standard and a best practices way of building images, that is a Dockerfile. 

Anyways, great discussion @jefferai. This is mainly personal preference at this point.

**Comment by jefferai** [comment]
OK, we've had some internal discussions, and here is what we are going to do; this is the plan for Vault, and likely for other HC products down the road:

1) We're going to create Trusted Builds, but we're going to do it based on the official golang containers. These will not be our recommended way to run our software in containers, but for those that want to run pre-built containers, this gives a very standard base for doing so.

2) Eventually, we will add support for building minimal `scratch`-based containers into the Makefile, so that you can use existing tools (`golang-builder`, `gockerize`, etc.) to create minimal containers built to our recommended specifications.

So for now I'm going to close this merge request. Thanks for submitting though!

**Comment by thalesfsp** [comment]
@jefferai News about the official docker image?

**Comment by jefferai** [comment]
They're coming, but to Consul first.

**Comment by thalesfsp** [comment]
@jefferai Thanks, awesome! Do you have some date?

**Comment by jefferai** [comment]
I don't, unfortunately. I believe, but am not certain, the the next version of Consul will be available in both container and binary form, so I know that work is actively being done. Depending on the timing, that might mean for Vault that 0.5.1 is available in containers, or might mean 0.6.

That said, we aren't necessarily timing a container release with a normal Vault release, so it may appear between releases.

**Pull request closed without merging**
