### PR TITLE
Fix a data race with rollbackPeriod.

### PR DESCRIPTION
**Pull request by ncabatoff**
Example race: https://app.circleci.com/pipelines/github/hashicorp/vault/4864/workflows/83a5e190-2c8b-42e2-9926-cf2c0e4b56a6/jobs/514036/parallel-runs/5
```
WARNING: DATA RACE
Read at 0x0000066d0e78 by goroutine 3793:
  github.com/hashicorp/vault/vault.NewRollbackManager()
      /home/circleci/go/src/github.com/hashicorp/vault/vault/rollback.go:73 +0x2b1
  github.com/hashicorp/vault/vault.(*Core).startRollback()
      /home/circleci/go/src/github.com/hashicorp/vault/vault/rollback.go:305 +0x107
  github.com/hashicorp/vault/vault.standardUnsealStrategy.unseal()
      /home/circleci/go/src/github.com/hashicorp/vault/vault/core.go:2180 +0x891
  github.com/hashicorp/vault/vault.(*standardUnsealStrategy).unseal()
      <autogenerated>:1 +0x78
  github.com/hashicorp/vault/vault.(*Core).postUnseal()
      /home/circleci/go/src/github.com/hashicorp/vault/vault/core.go:2277 +0x423
  github.com/hashicorp/vault/vault.(*Core).waitForLeadership()
      /home/circleci/go/src/github.com/hashicorp/vault/vault/ha.go:575 +0xf77
  github.com/hashicorp/vault/vault.(*Core).runStandby.func7()
      /home/circleci/go/src/github.com/hashicorp/vault/vault/ha.go:397 +0x5d
  github.com/oklog/run.(*Group).Run.func1()
      /home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x41
  github.com/oklog/run.(*Group).Run.func2()
      /home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:39 +0x58

Previous write at 0x0000066d0e78 by goroutine 843:
  github.com/hashicorp/vault/vault.CreateTestClusterWithRollbackPeriod()
      /home/circleci/go/src/github.com/hashicorp/vault/vault/testing.go:2449 +0xdc
  github.com/hashicorp/vault/builtin/logical/pki.TestAutoRebuild()
      /home/circleci/go/src/github.com/hashicorp/vault/builtin/logical/pki/crl_test.go:881 +0x2c4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x47
```

### CODE REVIEW

**Review by cipherboy — COMMENTED** [review]
Ahhh, I only prevented the race in the case where we were modifying the period:

https://github.com/hashicorp/vault/blob/main/vault/testing.go#L2433-L2443

I didn't solve it when we raced between modifying and non-modifying tests.

Perhaps we should just acquire the lock in `NewTestCluster` as well? I don't believe this atomic is sufficient, as we could still start a `NewTestCluster` while `CreateTestClusterWithRollbackPeriod` is executing and holding that lock, giving us a non-default `rollbackPeriod` value. I don't think this atomic is enough to guarantee that we get the default value in `NewTestCluster`. 

Thoughts?

**Comment by ncabatoff** [comment]
> Ahhh, I only prevented the race in the cases where we were modifying the period:
> 
> https://github.com/hashicorp/vault/blob/main/vault/testing.go#L2433-L2443
> 
> I didn't solve it when we raced between modifying and non-modifying tests.
> 
> Perhaps we should just acquire the lock in `NewTestCluster` as well? I don't believe this atomic is sufficient, as we could still start a `NewTestCluster` while `CreateTestClusterWithRollbackPeriod` is executing and holding that lock, giving us a non-default `rollbackPeriod` value. I don't think this atomic is enough to guarantee that we get the default value in `NewTestCluster`.
> 
> Thoughts?

Good point, my fix is insufficient.  I'm guessing the tests using this are slow enough that we want to keep their t.Parallels?

I was originally going to grab the lock in NewTestCluster, but I didn't want to interfere with the parallelization of tests that want to set this.  

How about instead of a global, we add a core field for this?

**Comment by cipherboy** [comment]
Yes, I think a core field makes the most sense. I had wanted to add one originally but didn't quite know how to plumb it through to the point of use in the Rollback manager, hence the current approach...

And yes, I find anything using this are about 2-4 seconds slower than something consuming the backend directly, without the cluster overhead. I think the lock here wouldn't prevent `t.Parallel`, but would mean that test cluster creation becomes serial, which probably would be less than ideal given how long it takes.

Thank you!!

**Comment by ncabatoff** [comment]
@cipherboy Note that at first I forgot to modify NewTestCluster to copy the field from base, and TestAutoTidy didn't fail (though TestAutoRebuild did).  I'm not going to dig into why, but I suspect there's something wrong with that test.

**Comment by cipherboy** [comment]
@ncabatoff I _suspect_ it is because we have a high enough timeout buffer of 120 seconds, which is two full periodic func invocations at the full 1m interval. 

If we were to reduce the timeout, it'll likely pass on non-CI systems just fine (with the shorter rollback period I called for in the test) -- and fail without setting it. 

I think I set it higher because this test was prone to failing on CI for some reason, though it was fast locally.

**Comment by ncabatoff** [comment]
Hey @cipherboy I saw a few more deadlocks on main recently.  Is anything else needed to get this fix approved?

**Review by cipherboy — APPROVED** [review]
Nope, apologies, I just missed the thumbs up w.r.t. comment on timeouts!

Thank you very much for this cleanup, great to avoid these locks and allow direct creation of the cluster.

**Pull request merged**
