### PR TITLE
Added ttl parameter to database creds generation api

### PR DESCRIPTION
**Pull request by andrejvanderzee**
The database secret engine supports `default_ttl` and `max_ttl` for it's role definitions, but the `creds/:role` endpoint does not support `ttl` parameter.

This PR adds `ttl` support for `creds/:role`.

### CODE REVIEW

**Comment by jefferai** [comment]
We don't usually allow clients to set this at generation time. What's the use case for this?

**Comment by andrejvanderzee** [comment]
Are you sure? For PKI you can and we use it happily:
https://www.vaultproject.io/api/secret/pki/index.html#ttl
Or for signing SSK public keys:
https://www.vaultproject.io/api/secret/ssh/index.html#ttl-1

Also, setting a `default_ttl` and `max_ttl` on the role suggests otherwise.

The use case is like for other secret engines: We dont wanna create a different role for different clients and copy all other role parameters. For example, we might issue 2h credentials for production accounts, but 24h on team accounts.

**Comment by jefferai** [comment]
The difference with those two examples is that those credentials have a fixed lifetime embedded in the certificate; they can't be renewed. But the ttl parameter in the database engine controls only the _initial_ ttl. It doesn't affect overall lifetime. A client could immediately renew the generated credential up to the max ttl by specifying an increment. In fact an immediate renew, even without specifying an increment, will use the role's default ttl.

In general the better option is to add a revocation step when your client is done using the credentials.

**Comment by andrejvanderzee** [comment]
@jefferai OK that explains the `max_ttl` it bounds renewals. Still, I don't see any objections in having the `ttl` set when issuing the credentials, and have the revocation done by Vault. I understand clients can renew their secrets, but 99% have no clue how to even do this. 

Besides, if they don't have access to the issuing Vault token clients cant renew. For example, in a setup where we issue secrets _indirectly_ by a Vault root token (or an orphaned token from the root token), the original client wont be able to renew the secret.

**Comment by jefferai** [comment]
> but 99% have no clue how to even do this

This doesn't match our experience, and in fact with recent features like vault agent caching this happens automatically.

If you are issuing secrets indirectly, before giving them to the client, you can just renew it to the desired time. If it's for a prod machine, grab the secret, renew it to 2 hours, then pass it along.

**Comment by andrejvanderzee** [comment]
@jefferai Of course we can work around this, but its unnecessary.

Lets turn it around: What is the reason for _not_ allowing ttl when issuing the secret? Still dont get that from your comments.

**Comment by jefferai** [comment]
Mainly: at a time when we are actively working to reduce inconsistency in our API, this adds more.

If this is a parameter we want to add, I think it potentially needs to be done across the board with all secrets engines via a shared library, similar to tokenutil. But that's a larger discussion and a much larger amount of work and in the meantime there are usable workarounds for your use case.

**Comment by andrejvanderzee** [comment]
Most of the issue API calls I have seen and work with, actually _do_ have a ttl parameter, including SSH, PKI and AWS STS. That is why I was surprised DB creds doesnt have one. The fact that DB credentials are renewable and therefor makes it consistent, does not hold from an outside  viewpoint of you API consumer, it just adds to the chaos. So,  if you talk about incosistencies among your API calls, you should actually _add_ it.

**Comment by andrejvanderzee** [comment]
@jefferai 

Here another inconsistency I would be more worried about. 

In the code:
https://github.com/hashicorp/vault/blob/master/builtin/logical/database/path_config_connection.go#L31

In the documentation:
https://www.vaultproject.io/api/secret/databases/index.html#root_rotation_statements

That makes me wonder how many clients actually rotate their superuser passwords :-) We are going to production with a major banking Fintech and almost all of our security is regulated by Vault, so we have to be compliant by compliance ruling. Vault works great for us, but the API and documentation (for us source code equals documentation) is definitely not always consistent and clear. 

Also, we are missing approvals in secret engines. What I mean is that we require a mechanism for production that enforces approvals to access high-privileged secrets for SRE members: For example, no SRE member can ever get database superuser credentials without another SRE member or security member approving with required audit events. As far as I have seen, Vault does not accommodate for approvals also not in the paid version with sentinels.  We have some ideas solving this by custom plugins that will be implemented soon, but would be nice to have that supported by Vault directly.

Nevertheless, we are happy users of Vault but can definitely identify places for improvement!

**Comment by jefferai** [comment]
```
Here another inconsistency I would be more worried about.

In the code:
https://github.com/hashicorp/vault/blob/master/builtin/logical/database/path_config_connection.go#L31

In the documentation:
https://www.vaultproject.io/api/secret/databases/index.html#root_rotation_statements
```
What do you see as the issue there?

> As far as I have seen, Vault does not accommodate for approvals also not in the paid version with sentinels.

This is Control Groups: https://learn.hashicorp.com/vault/identity-access-management/iam-control-groups

**Comment by jefferai** [comment]
> Most of the issue API calls I have seen and work with, actually do have a ttl parameter, including SSH, PKI and AWS STS. That is why I was surprised DB creds doesnt have one.

All three of these are things that cannot be renewed so cannot be given a short initial lifetime with the ability to extend it. That's why we allow the client to specify further constraints at issue time.

**Comment by andrejvanderzee** [comment]
> > Most of the issue API calls I have seen and work with, actually do have a ttl parameter, including SSH, PKI and AWS STS. That is why I was surprised DB creds doesnt have one.
> 
> All three of these are things that cannot be renewed so cannot be given a short initial lifetime with the ability to extend it. That's why we allow the client to specify further constraints at issue time.

Still, from an outside consumer of the API, I would expect to be able to set the TTL when issuing  secrets, regardless non-renewable or renewable. As a consumer of your API, my first impression is that the option is missing working with many other Vault secret engines. In short, I understand your point between renewable and non-renewable secrets, but from an API consumer point of view, it is still inconsistent (although it is consistent _under renewability conditions_).

As to database and other renewable secrets, are there any other objections apart from uniformity to make it renewable until `max_ttl`?

**Comment by kalafut** [comment]
We just renamed Vault's default branch. The GitHub automation handles retargeting open PRs, but only if the original fork still exists. The fork for this PR had been deleted so it was automatically closed. You can reopen it against Vault's `main` branch if you wish. Thank you!

**Pull request closed without merging**
