### PR TITLE
Fix dynamodb HA lock race

### PR DESCRIPTION
**Pull request by mahmoudm**
Fixes https://github.com/hashicorp/vault/issues/5828

### CODE REVIEW

**Comment by mahmoudm** [comment]
I'm still testing this change, opened to start the discussion. I'll ping back when tested fully.

**Comment by mahmoudm** [comment]
I've tested this and deployed it to production and it works as expected.

**Comment by kalafut** [comment]
@mahmoudm Thanks for digging in to this. I've reviewed it briefly and it looks reasonable. Can you please add a test to `dynambo_test.go` (i.e. another special purpose test like `testDynamoDBLockTTL`) that causes the sequence which should fail without your changes?  To run those tests you'll need Docker installed, and to just run the Dynamo ones you can use `go test ./physical/dynamodb`

**Comment by maartenvanderhoef** [comment]
Hi @mahmoudm would you be able to find time to finish the PR ?

**Comment by kalafut** [comment]
@mahmoudm Thanks for working to help clear the CLA block. It looks like some older commits are under another GitHub ID that's no longer active. Would you mind taking your current code and pushing a new PR, squashed without reference to the old ID? We can then close out this PR and I'll help integrate the new one.

**Comment by kalafut** [comment]
@mahmoudm Despite the force-push and the history only showing the one commit, the CLA checker is still referencing the old email. Could you push the work (i.e the same squashed commit, possible as a new branch in your repo) as a new PR? I think that may be simplest way to appease the CLA checker. Thanks for your patience with this!

**Pull request closed without merging**
