### PR TITLE
Bump cloud.google.com/go to get timeout fix

### PR DESCRIPTION
**Pull request by joshk0**
The commit I'm interested in is
googleapis/google-cloud-go@fbf2f51 ,
which disables an aggressive 2-second timeout for awaiting headers from
the compute metadata service.

This 2-second timeout causes problems when [Workload Identity] is
enabled on a cluster. In this situation, a different endpoint is used
under the hood for compute metadata, and this endpoint can often take
more than 2 seconds to return headers.

[Workload Identity]: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

### CODE REVIEW

**Comment by joshk0** [comment]
@vishalnayak any other steps I have to take to initiate a review on it, or any other testing i can do manually? Looks like the 'race' tests failed but i don't think that was my fault

**Comment by vishalnayak** [comment]
@joshk0 We update the dependencies with every release and 1.4 is right around the corner. I can't say an exact date, but it is going to be released soon. We tend to avoid library updates between releases. Hence the delay in review.

**Comment by vishalnayak** [comment]
Discussed this internally. I think we are good to take it in.

**Comment by ncabatoff** [comment]
I've reverted this change for now because of module problems.  etcd chokes on the new version of  grpc, and we can't upgrade etcd because of https://github.com/etcd-io/etcd/issues/11154.

**Pull request merged**
