### PR TITLE
English Grammar.

### PR DESCRIPTION
**Pull request by tomthetommy**
Simply missing a "to".

### CODE REVIEW

**Review by ccapurso — APPROVED** [review]
Nice catch, thanks for the fix!

**Comment by ccapurso** [comment]
@tomthetommy, I have approved your changes but am unable to merge until you have signed the Contributor License Agreement. Once that is complete and CI checks complete, I'll merge. Thanks again!

**Comment by tomthetommy** [comment]
> @tomthetommy, I have approved your changes but am unable to merge until you have signed the Contributor License Agreement. Once that is complete and CI checks complete, I'll merge. Thanks again!

That has been signed now. Thank you.

**Comment by tomthetommy** [comment]
Oops, incorrectly closed.

**Pull request merged**
