### PR TITLE
Remove two unreliable tests from TestTransit_SignVerify_P256.  

### PR DESCRIPTION
**Pull request by ncabatoff**
These verify that you can't verify something signed using JWS marshaling when claiming
it's ASN1, and vice versa.  The problem is that we rely on unmarshaling
failing, and it doesn't always.  Both encodings use base64, one with
padding, one without, so depending on the data sometimes unmarshaling
will work when we expect it to fail.  It would be nice to preserve
these tests if they could be made reliable, but I didn't see an easy way,
and I don't think they add enough value to warrant greater effort.

### CODE REVIEW

**Comment by tyrannosaurus-becks** [comment]
Hi @ncabatoff , are you still wanting to merge this? If so, I'd be happy to review, just let me know.

**Comment by ncabatoff** [comment]
> Hi @ncabatoff , are you still wanting to merge this? If so, I'd be happy to review, just let me know.

Hi @tyrannosaurus-becks, yes, that'd be great thanks!

**Comment by jefferai** [comment]
I have never seen these tests fail so I don't know what the output looks like, but I would imagine the error due to a b64 unmarshalling error looks different from one that fails due to an asn1 or jws unmarshalling failure. Can't we just skip if we see the wrong error message come back?

**Comment by ncabatoff** [comment]
We don't get an error, that's the problem:

```
Failed
=== RUN   TestTransit_SignVerify_ECDSA/256
    --- FAIL: TestTransit_SignVerify_ECDSA/256 (0.00s)
        path_sign_verify_test.go:251: bad: should have gotten error response: logical.Response{Secret:<nil>, Auth:<nil>, Data:map[string]interface {}{"valid":false}, Redirect:"", Warnings:[]string(nil), WrapInfo:(*wrapping.ResponseWrapInfo)(nil), Headers:map[string][]string(nil)}
```

I'm trying a different approach: update `verifyRequest` such that when an error is expected, it is satisfied provided it either gets an error from `HandleRequest`, or if the response has `valid=false`.

**Pull request merged**
