### PR TITLE
Document the use of inline SSL certificates for PostgreSQL

### PR DESCRIPTION
**Pull request by remilapeyre**
Thanks to the work done by @eirslett in https://github.com/lib/pq/commit/b9bb726ebf154627a21b50f9ffa4b28c6ed3f4d8 it is now possible to specify certificates directly in the PostgreSQL DNS which makes it possible to finally use certificates authentication in PostgreSQL with Vault.

Closes https://github.com/hashicorp/vault/issues/10925

### CODE REVIEW

**Comment by Keramblock** [comment]
Any news on that one? pg certificates are not really usable right now in helm vault because of lack of that feature =(

**Comment by samuel-form3** [comment]
Do we have any idea on when this issue will be analysed ? I would really need this in order to setup mTLS connections to CockroachDB.

**Comment by hsimon-hashicorp** [comment]
Hi there! The tests are currently failing in CircleCI, possibly because of the revert. Can you rebase off of main, and we can run the tests again? Thanks!

**Comment by remilapeyre** [comment]
Hi @hsimon-hashicorp, it should be good now!

**Review by jasonodonnell — APPROVED** [review]

**Review by cipherboy — APPROVED** [review]

**Comment by Keramblock** [comment]
@hsimon-hashicorp working, thx =)

**Pull request merged**
