### PR TITLE
Adding support to build and test in docker

### PR DESCRIPTION
**Pull request by ekristen**
I broke this out into its own PR, to build and test vault in docker.

### CODE REVIEW

**Comment by jefferai** [comment]
@ekristen Let's have a discussion about Dockerizing Vault in #484 since you two are already talking there.

**Comment by ekristen** [comment]
@jefferai I would suggest this is the PR we want for docker build/test support but I am biased.

The other PR takes the wrong approach by using git to pull the source and build.

**Comment by jefferai** [comment]
@ekristen See my comment in the other PR for something altogether different...

**Comment by ekristen** [comment]
Yeah its two separate things.

1) Building vault with docker 

vs 

2) Building a docker image for the docker registry that runs vault :)

**Comment by jefferai** [comment]
I'm not sure those are two separate goals. Any official image provided to the Docker Hub should reflect best practice, and if it is best practice there's not much reason to have official scripts/support for building a Docker container that are divergent.

**Comment by jefferai** [comment]
Let's please migrate all comments to the other thread.

**Comment by ekristen** [comment]
I disagree, they are separate. Any official image provided to the docker hub should be for purely running the application, not building it from source.

I do not think migrating comments is something that should be done. This PR stands on its own and should be merged in, it has no affect nor should it on publishing an official image to the docker hub.

This pull request purely provides a simple way to build vault (cross platform) with the only requirement being docker (no complex gopath, goroot setup).

**Comment by jefferai** [comment]
If the only point of this is simply to build binaries, then it overlaps with the existing scripts, except that this requires Docker and the existing scripts do not. I don't really see a need for this. I can bring it up internally, though.

**Comment by ekristen** [comment]
Correct the point of this pull request is to provide a clean way of building and testing vault inside docker without having to get a golang config all setup on your system.

There are numerous reasons why this is beneficial, but to each their own.

**Comment by jefferai** [comment]
Some comments in the mean time:

1) Don't set the golang-cross version; anyone using the script should use the latest available version of Go

2) Building Docker images should be opt-in, not opt-out. As you've pointed out, using Docker to cross-compile and building an official Docker image are separate concerns. If opting in, the tag name should also be sourced from the environment.

**Comment by jefferai** [comment]
@ekristen So I think what you said in your previous comment is part of my concern. In one place you say that the point of this is to provide a Docker-based way to cross-compile Vault. But then later you say that the point is to provide a way of building and testing Vault inside Docker. Many of the output binaries would be useless for this purpose, however, as currently Docker only supports Linux.

**Comment by ekristen** [comment]
> So I think what you said in your previous comment is part of my concern. In one place you say that the point of this is to provide a Docker-based way to cross-compile Vault.

Yes this https://github.com/ekristen/vault/blob/docker-build-support/scripts/test-docker.sh spins up a tagged image to run the tests. Subsequent runs the tagged image is build, so the new code is just added and the tests are run.

This https://github.com/ekristen/vault/blob/docker-build-support/scripts/build-docker.sh spins up a tagged image to cross compile vault, it can easily be used to target a specific operating system or architecture. The first run will take a little longer to create the image that is used, but after the initial run, the subsequent runs are extremely fast.

If coupled with boot2docker (or using docker-machine) on OSX or Windows (I believe volumes now work on windows too) when you run the build-docker.sh i386 and amd64, for all three operating systems, binaries will appear in a `dist` folder in the vault code root.

**Comment by jefferai** [comment]
Hi, please see the comment here: https://github.com/hashicorp/vault/pull/484#issuecomment-135006759

For now I will close this. Thanks for the submission!

**Pull request closed without merging**
