### PR TITLE
Add omitempty's to MountEntry and MountConfig

### PR DESCRIPTION
**Pull request by jefferai**

### CODE REVIEW

**Comment by catsby** [comment]
Hello - is this still a PR we want, or are we waiting for something? Does this fix a particular issue?

**Comment by jefferai** [comment]
It makes the mount table smaller. There are some pros and cons to merging this.

The pro side is that no matter how it's stored, having smaller mount entries means smaller things to write and read and faster serialization. Even with chunking in Consul/Raft, this can mean less chunks.

The con side is that right now this patch sort of acts as an escape valve for people not using chunking currently that have gotten into a jam by hitting any kind of storage-imposed upper limit.

I'm not sure if we should merge it. It feels like something we want to keep around to be able to pull in as needed to a build, but not necessarily have running all the time. But that's a weird stance in that it's basically specifically not being efficient in service of having workarounds for some problems some users may have.

Possibly this should be deferred until Raft is our default storage and has been proved out, at which point since it supports chunking natively and thus our official storage won't have a size related issue we just merge this in.

**Comment by briankassouf** [comment]
Going to move into 1.5 for now, at that point raft will be somewhat adopted and consul users will hopefully be upgraded to a build that does contain chunking.

**Review by vishalnayak — APPROVED** [review]
Reveived 👍 from @briankassouf offline as well.

**Pull request merged**
