### PR TITLE
UI - Unwrap Wrapping token from Login page. Resolves: #5893.

### PR DESCRIPTION
**Pull request by aphorise**
Provided new feature for unwrapping data on login screen as per the request on GH-Issue: #5893 

Re-used existing unwrap templates which were added to login. Credentials or other pertinent data can be unwrapped by end-users via UI without the need for CLI or API specific access.

PS - advance apologies for missing tests - kindly help with my inadequacies there.

90963669-f5ac1680-e4b9-11ea-82e9-5d55d9050760

### CODE REVIEW

**Comment by aphorise** [comment]
Any chance of getting some input here? - it would be nice to know that this feature would also be offered nearing to 1.10 (only been 15 months 😛)

**Comment by aphorise** [comment]
Hey guys this request is approaching its 2 year mark (in a months time) from the time I've opened it. What is the status here?

Please state alternatives and close if you are not likely to merge it - it's not clear what's holding this back or what may be next.

**Comment by pree** [comment]
I really like this change. The only issue I see is the audibility. It might need an extra flag for wrapped tokens, to allow unauthenticated unwrapping.

**Comment by zofskeez** [comment]
Thanks for opening this @aphorise. This was discussed by the UI team and it was determined that it would be a good feature but one that needs further consideration. The feature has been added to the list of potential projects for future prioritization.

**Pull request closed without merging**
