### PR TITLE
Adding the known issue section

### PR DESCRIPTION
**Pull request by yhyakuna**
This is to resolve the [Asana task](https://app.asana.com/0/112957393038545/1126542013431822/f).

### CODE REVIEW

**Comment by jdfriedma** [comment]
I'd rewrite this, because it reads a bit awkwardly and I think we're missing some key detail: specifically that it really only affects secondaries (specifically perf standbys). Here's a proposed revamp: 

During upgrades to 1.1.0, 1.1.1 or 1.1.2, Vault replication secondaries may require an automatically-triggered reindex, either if upgrading from a pre-0.8 version of Vault or if a previously-issued reindex operation has failed in the past. In these reindex scenarios, the secondary cluster will perform a complete WAL replay, which can take a long time and is a partially blocking operation. This is fixed in [Vault 1.1.3](https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#113-june-5th-2019), and we recommend upgrading to Vault 1.1.3+ rather than any prior 1.1.x version. We also strongly recommend upgrading your Vault cluster to 1.1.3 if you are running Vault Enterprise 1.1.0, 1.1.1 or 1.1.2.

**Comment by lauradiane** [comment]
@yhyakuna Looks good! Can we add this to upgrade guides for all 3 of the problematic versions? (1.1.0, 1.1.1 and 1.1.2)?

**Comment by yhyakuna** [comment]
@lauradiane  I added the note in the `upgrade-to-1.1.1.html.md` as well.  Since there is no upgrade guide for `1.1.2`, I think this is it.

**Comment by lauradiane** [comment]
Copying from Asana: Thanks @yhyakuna ! Can we create an upgrade guide for 1.1.2 to include this? I think the only reason there wasn't an upgrade guide for that version was because there was nothing to point out for it, but I think this is a worthy thing to point out for that version if people are considering upgrading to it.

**Comment by yhyakuna** [comment]
@lauradiane  I [added](https://github.com/hashicorp/vault/pull/7439/commits/7a5b41b0c625075b0d609d0d0f7ebe40a02f2572) an upgrade guide for 1.1.2 as you suggested.

**Pull request merged**
