### PR TITLE
Switch to new container-based build

### PR DESCRIPTION
**Pull request by sethvargo**

### CODE REVIEW

**Comment by jefferai** [comment]
I leave our ruby in your capable hands, maestro.

**Comment by sethvargo** [comment]
❤️

**Comment by joelthompson** [comment]
@sethvargo -- any plans on updating website/Vagrantfile and website/README.md? The former installs ruby 2.0.0 while hashicorp-middleman requires ruby >= 2.3 so it errors out, and the latter tells users to run `make dev` instead of `make website` now. Nothing major, just a few small things I noticed.

**Comment by sethvargo** [comment]
@joelthompson I'll do that. Sorry - we are in the process of switching from a Vagrant-based build to using the Docker-based middleman-hashicorp.

**Comment by joelthompson** [comment]
Thanks! And no big deal, it was easy enough to figure out, just figured I'd make sure that they don't get forgotten.

**Comment by sethvargo** [comment]
README is updated and the Vagrantfile is gone now.

**Pull request merged**
