### PR TITLE
UI - Secrets KV Download Json Button. Resolves: #6364

### PR DESCRIPTION
**Pull request by aphorise**
Provided new feature for JSON download of secrets as per the request on GH-Issue: #6364.

Feature request seems reasonable for workflows where needing to interact with many secrets or larger size ones.

PS - advance apologies for missing tests - kindly help with my inadequacies there.

Screenshot 2020-08-23 at 02 48 17

### CODE REVIEW

**Comment by aphorise** [comment]
I was curious if this request can kindly be picked up for release with 1.10 or thereafter?

**Comment by aphorise** [comment]
Hey guys this request is approaching it's 2 year mark (in a months time) from the time I've opened it. What is the status here?

**Comment by hellobontempo** [comment]
Hi @aphorise - apologies for the delayed response here! I'm not quite sure what happened, but if this is still something you're interested in for an upcoming version of Vault I can bring it up with product + design. Is the goal here to download both the key and value data, or just the value? 

This template is shared across different secret engines in Vault so this change would make secret data downloadable for other engines (i.e. cubbyhole) - something to keep in mind!

**Comment by hashishaw** [comment]
This PR is being closed in favor of #20431 -- Thank you!

**Pull request closed without merging**
