### PR TITLE
bump go to 1.16.7

### PR DESCRIPTION
**Pull request by raskchanky**

### CODE REVIEW

**Review by pmmukh — APPROVED** [review]

**Comment by pmmukh** [comment]
Think the Dockerfile.ui might need to be changed also btw, stephen just noticed that on my pr

**Review by swayne275 — COMMENTED** [review]
I think we also need to update `scripts/docker/Dockerfile.ui`

**Comment by raskchanky** [comment]
@pmmukh @swayne275 Updated with that missing file. Good catch!

**Review by swayne275 — APPROVED** [review]
cool. i'm going to update the comment in the release procedure doc to reference this as a more recent example

**Pull request merged**
