### PR TITLE
Audit: capture emitted errors from nodes

### PR DESCRIPTION
**Pull request by peteski22**
During processing of audit pipelines for logging requests/responses, if we return errors they are send over a channel and gathered as `Warnings` on the `Status` struct.

In the case where the `broker.Send` returns an `error`, we should include these errors (warnings) in the message that is logged to the Vault server. This should make debugging issues easier for the Vault operator.

### CODE REVIEW

**Review by ccapurso — APPROVED** [review]
I'm not certain how the nested `multierror.Append` calls will look so you might want to functionally test that out. Looks good to me though!

**Review by raskchanky — APPROVED** [review]
Like @ccapurso said, I'm not sure how the formatting of the nested multierror appends will look, so probably worth checking that. But the idea makes sense.

**Comment by peteski22** [comment]
For the output of the multierror append, append: https://go.dev/play/p/RlrnaU8l9kx

**Comment by marcboudreau** [comment]
Since I've come back to this PR twice looking for an example of the new error message, I've decided to setup an environment to generate such an error and post it here:

In Vault 1.15.0:
```
2023-11-02T15:22:47.457Z [ERROR] core: failed to audit response: request_path=auth/token/lookup-self
  error=
  | 1 error occurred:
  | \t* event not processed by enough 'sink' nodes
  |
```

After this PR:
```
2023-11-02T15:27:33.732Z [ERROR] core: failed to audit response: request_path=auth/token/lookup-self
  error=
  | 2 errors occurred:
  | \t* event not processed by enough 'sink' nodes
  | \t* event.(FileSink).Process: error writing file for sink: event.(FileSink).log: unable to re-write to file for sink: write /vault/audit/audit.log: no space left on device
  |
```

**Pull request merged**
