### PR TITLE
Remove logical.Initialize() method

### PR DESCRIPTION
**Pull request by vishalnayak**

### CODE REVIEW

**Comment by briankassouf** [comment]
Looks good! I think you can also pull out the framework.Backend's Init variable!

**Comment by briankassouf** [comment]
This one: https://github.com/hashicorp/vault/blob/master/logical/framework/backend.go#L76

**Comment by calvn** [comment]
In the same spirit, IniatilizeFunc can be also removed right?

**Comment by vishalnayak** [comment]
@briankassouf @calvn Address both of your comments and some more fix ups in tests.

**Comment by jefferai** [comment]
Glorious

**Comment by jefferai** [comment]
Dooooo ittttttt

**Pull request merged**
