### PR TITLE
The big one

### PR DESCRIPTION
**Pull request by jefferai**

### CODE REVIEW

**Comment by kohend** [comment]
I noticed this includes a change for the format of tokens (from UUIDs to base62), is this documented somewhere?

**Comment by kohend** [comment]
They can't be when using the /sys/generate-root API, in that case I need to decode and format the output, in addition to sending an OTP with the correct length, that I couldn't find a way to get apart from making a failed attempt.

**Comment by jefferai** [comment]
You don't need to send an OTP; if you don't send one, one of the appropriate length will be returned for you on operation init.

**Comment by kohend** [comment]
On previous versions it's required, how am I supposed to know what to send in the request in advance?
This is undocumented, the documentation still states that the OTP is 16 bytes, and required.

**Comment by jefferai** [comment]
I'll fix the documentation.

**Comment by kohend** [comment]
Thank you.

**Comment by jefferai** [comment]
Updated. Turns out there was also a bug requiring one of the two values to be set in the request body even though in actuality right now it's ideal to simply send nothing. This will be fixed in the next release (and the docs updated accordingly again).

**Comment by kohend** [comment]
Thanks, but when you fixed the bug you deleted most of the documentation you added, was that on purpose?

**Comment by jefferai** [comment]
That won't go live on the website until the new version with the fixed code is available.

**Comment by jefferai** [comment]
I realize that. When that goes live it will be correct. In the meantime, the current website docs (which have the documentation I added) is correct.

**Pull request merged**
