### PR TITLE
*: bump etcd/client and grpc version

### PR DESCRIPTION
**Pull request by xiang90**
for #3772

### CODE REVIEW

**Comment by xiang90** [comment]
@jefferai 

hmm... is there something wrong with the current CI? it seems this PR is blocking forever :P.

**Comment by benpaxton-hf** [comment]
@xiang90 looks like Travis is having issues: https://www.traviscistatus.com/

**Comment by jefferai** [comment]
@xiang90 I'm going to have to schedule this for 0.9.3 -- 0.9.2 is going out very soon and since we use grpc heavily I'm wary of merging updates to it without us having the opportunity to do due diligence.

**Comment by xiang90** [comment]
@jefferai 

ok. that is even better. thanks.

**Comment by xiang90** [comment]
@jefferai 

the stable gRPC go version we are aware of is 1.7.5.

**Comment by raoofm** [comment]
@xiang90 grpc go is v1.9.1 now

**Comment by jefferai** [comment]
Deps have been bumped.

**Pull request closed without merging**
