### PR TITLE
Feature: Allow adding metadata to userpass users #1893

### PR DESCRIPTION
**Pull request by ernestpremkumar**
Updates path_users.go to allow users to add metadata

### CODE REVIEW

**Comment by vishalnayak** [comment]
@ernestpremkumar About the changes in the PR, a couple of things can be improved. But before that, what is the use-case for this change?

**Comment by ernestpremkumar** [comment]
@vishalnayak Hi, (https://github.com/hashicorp/vault/issues/1893) I'm trying to implement this

**Comment by vishalnayak** [comment]
@ernestpremkumar Sounds good about the use-case.

The UX of accepting a single field seems the right way to go. In that regard, I suggest the following:
1) Accept a single field `metadata` of field type `TypeMap` instead of `meta_key` and `meta_value`. This will allow multiple metadata values under a single field.
2) Metadata information should be returned when reading user information.

**Comment by vishalnayak** [comment]
@ernestpremkumar Also, in order to keep things simple, it might also be a good idea to retain the *internal* type of `metadata` as `map[string]string`. This will avoid clients storing endless amount of embedded metadata in that field.

It might be good to have some sanity checks on the number of key/value pairs accepted by the metadata and the characters of the `key` and `value` that gets supplied. But, you don't need to do it in this PR since it might come in as a helper utility as part of a separate on-going work.

What you might need to do in this PR is to check the type of the values in the key/value pairs to be of type `string`. If not, error out.

**Comment by vishalnayak** [comment]
@ernestpremkumar I'm sorry but after discussing on this internally, we decided to not add this feature. Following are the reasons:
1) There is an alternative feature which is under works that might provide similar functionality. That might leave this feature redundant and this might have to be maintained forever regardless of whether we need it or not, for backwards compatibility.
2) Having such a feature on one backend might result in requests/PRs for adding metadata in other authentication backends as well, which are also not needed for the same reason mentioned in 1.

**Comment by Valtena** [comment]
Hi @vishalnayak , can you link the alternative feature ? 

I have found this issues https://github.com/hashicorp/vault/issues/1893 but no more doc/source about meta for authentication.

**Comment by maumercado** [comment]
Hello @vishalnayak, it's being some time that this issue has been revisited, but I have not managed to find the featured described in here. 

Would you be so kind as to reference the documentation or any reference on how to use this feature in vault?

**Pull request closed without merging**
