### PR TITLE
Add an OpenPGP secret backend

### PR DESCRIPTION
**Pull request by LeSuisse**
Hi!

So following some discussions in #1347 I finally took the time to finish the documentation of the OpenPGP secret backend plugin I created to submit this PR.

This first version does not have the ability to manage subkeys but it could be added in the future with new routes `openpgp/subkeys/:name` to list and manage the subkeys of a key and by adding an optional parameter `subkey_id` on the `openpgp/sign/:name` route.

### CODE REVIEW

**Comment by LeSuisse** [comment]
Hi!

Thank you for your prompt response while finishing up the 0.10 release!

 > I think we need a design doc. This is a 10k line PR and PGP has a ton of potential operations and options. Understanding which ones are available, which ones aren't, why, and the whole design would be much better if we can all standardize on a design doc that explains the structure, API, and so on. That way we can evaluate the code against a shared understanding of what it should be doing.

Yep, I agree.
I use this code for a while now as an external plugin. This massive PR was more a way to start a discussion and see what we can do about it than anything else.

Do you have such document available publicly for one of the other backend so that I can write something that match your expectations in term of content? I think I remember seeing such a document for one of the GCP backend but I can not find it anymore.

 > Your code and documentation continually reference GPG. Please use PGP, not GPG. GPG is an implementation of PGP, but the underlying technology is PGP.

Sure, leftovers from the external plugin.

 > Is there a reason you're using x/crypto/openpgp instead of keybase's fork, which Vault currently uses? They've diverged, and I don't know which is "better" at this point (we moved to Keybase's a while back because of bugs in x/crypto), but it feels like we should probably standardize on one or the other.

No, particular reason. Keybase's fork still has some interesting patches when it comes to importing keys.

**Comment by ColinHebert** [comment]
@LeSuisse @jefferai @chrishoffman, any progress on getting openGPG secret backend into Vault?

**Comment by jefferai** [comment]
No progress in particular. It would be _really_ nice to have this functionality but we didn't get a design doc and so didn't really start a discussion. One key question that I was hoping we could discuss via a doc is whether this should be a standalone plugin or enhancements to `transit`. Given the API similarities it seems like the latter is likely the better route, with the caveat that we'd likely then constrain to less than the full set of PGP capabilities. For example, in the original comments the author mentioned subkey support, and I think for `transit` that would head into the realm of "too specific, needs to be external". If the purpose is mainly for simply signing, then it should fit into `transit` nicely; if there is seen a need for things like subkeys, adding signatures on keys, and keyserver support, I think it's too specific.

If the author wants to get back in touch with us and work through these questions that would be great.

**Comment by LeSuisse** [comment]
Hi,

I'm even more convinced than before that constraining the PGP capabilities is the way to go. Maybe just supporting signing in the `transit` backend would be enough for the majority of the use cases (at least it's my use case).
As far as I know nobody as step up to help supporting golang.org/x/crypto/openpgp (https://groups.google.com/forum/#!topic/golang-openpgp/_P6AmeCmD9w) and the efforts are currently split between multiple forks. Exposing too much of the PGP model does not make me confident, bugs/not implemented features are likely to be exposed in the underlying library.

**Comment by jefferai** [comment]
Yep, I totally agree. At the moment because of the large amount of PGP work being done (as it's their business model) I tend to think Keybase is likely still the right fork to use.

Any chance you'd be interested in turning this into a patchset on transit? The key management could go into policy and I think there are not too many API changes. Naming is likely to be the hardest part (e.g. for things like email, is it `email` for the API param or `pgp_email` to make it clear which parameters are specific to pgp types? I would lean towards the latter, but open to persuasion.)

**Comment by jefferai** [comment]
@LeSuisse didn't hear back from you, any comment? Would you be willing to upstream a transit-ified version?

**Comment by binlab** [comment]
@LeSuisse thanks for your work! It will be nice to see your PR in mainstream Vault. I hope you find time for it!

**Comment by malnick** [comment]
Closing due to no response.

**Comment by trishankatdatadog** [comment]
I am thinking of adding a PGP backend to Vault. What would be the way to go?

**Pull request closed without merging**
