### PR TITLE
Cassandra plugin: Support for datacenter aware deployments

### PR DESCRIPTION
**Pull request by andrejvanderzee**
When connecting to Cassandra, the current plugin does not take into account multi-datacenter deployments. This results in Vault connecting to Cassandra hosts in remote clusters. 

This pull requests adds the option `local_datacenter` which enables the `DCAwareRoundRobinPolicy` in the `gocql` client library, ensuring  that local Cassandra hosts are prioritized:
https://github.com/gocql/gocql/blob/master/policies.go#L740

### CODE REVIEW

**Comment by briankassouf** [comment]
Thanks for submitting this! Could you add the parameter to the website docs with an example value? It's hard to know what format ought to be provided

**Comment by andrejvanderzee** [comment]
@briankassouf Thanks, indeed forgot about the website documentation. Just pushed an update.

**Comment by briankassouf** [comment]
@andrejvanderzee thanks for adding that, additionally you made these changes in the deprecated cassandra plugin, there is a newer version here https://github.com/hashicorp/vault/tree/master/plugins/database/cassandra (and in fact you changed the documentation for the newer one)

Could you make this change to the new plugin?

**Comment by andrejvanderzee** [comment]
@briankassouf OK got that twisted. I have pushed the changes to the new `plugin` version. I assume that the database secret engine takes care of the storage of the config, so the changes are reduced to a couple of lines.

Probably better to revert the changes on the deprecated `builtin` version?

**Comment by andrejvanderzee** [comment]
@briankassouf It looks like there is another mixup for another feauture: The option `consistency` is implemented in the new `plugin` version, but only appears in the deprecated documentation. 
https://www.vaultproject.io/api/secret/cassandra/index.html#consistency
While it's missing in the new documentation:
https://www.vaultproject.io/api/secret/databases/cassandra.html
I would suggest to add `deprecated` somewhere in the file path.

Anyway, I have reverted the changed in the deprecated `builtin` Cassandra.

**Pull request merged**
