### PR TITLE
typo on terraform/roles path

### PR DESCRIPTION
**Pull request by tkaburagi**
write terraform/roles may be write terraform/role

### CODE REVIEW

**Review by pmmukh — APPROVED** [review]
Thanks for submitting this PR! lgtm!

Also, could you please rebase this off main ?

**Comment by tkaburagi** [comment]
@hsimon-hashicorp Thanks! it's done.

**Review by taoism4504 — COMMENTED** [review]
LG

**Comment by hsimon-hashicorp** [comment]
Hi @tkaburagi - just wanted to check back in here, as there's conflicts that need resolving. If you can take care of that, we can get this merged. Thanks in advance!

**Pull request merged**
