### PR TITLE
Expose token create errors in the response.  Show devtoken errors to user

### PR DESCRIPTION
**Pull request by ncabatoff**

### CODE REVIEW

**Comment by ncabatoff** [comment]
> maybe a good time to fix them to avoid same issues

Almost everyone else is off today due to MLK.  I thought I'd wait to get feedback on this from other team members before broadening the scope.

**Comment by vvelikodny** [comment]
> > maybe a good time to fix them to avoid same issues
> 
> Almost everyone else is off today due to MLK. I thought I'd wait to get feedback on this from other team members before broadening the scope.

I've tried next command on your PR
`./bin/vault server -dev -dev-root-token-id="S.6w3CpXn5vChbnpLtBlCJCUxs"`

give error:

> Error initializing Dev mode: error creating default K/V store: 1 error occurred:
        * internal error

also not good

**Comment by ncabatoff** [comment]
> also not good. It seems any bad letter like . etc. gives the internal error.

Agreed, not good, but not a regression - same behaviour exists on current master.  Whatever the fix for that is, it probably belongs in its own PR.

**Comment by xntrik** [comment]
I'm wondering if there's any historical reason why we didn't surface those errors up

**Pull request closed without merging**
