### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by naseemkullah**

### CODE REVIEW

**Comment by hsimon-hashicorp** [comment]
Hi @naseemkullah - would you be okay to sign the CLA? Then we can get this reviewed. Thanks! :)

**Comment by naseemkullah** [comment]
@heatherlarsen signed ✅

**Comment by naseemkullah** [comment]
@hsimon-hashicorp signed ✅

**Review by averche — APPROVED** [review]
LGTM 👍 Thank you for contributing!

**Pull request merged**
