### PR TITLE
A few small fixes for tests

### PR DESCRIPTION
**Pull request by briankassouf**

### CODE REVIEW

**Comment by jefferai** [comment]
I'm going to merge only the lock/unlock for now. I actually took out the few places that we were doing nil connection checks in favor of putting connection info into requests.

The reason is that if we are doing a CIDR check and we have _no IP information at all_ then my gut feeling is that we should default-fail. In reality outside of tests we should always have IP information even if it's 127.0.0.1 and if we don't something is likely quite wrong. So I didn't want to potentially allow traffic we shouldn't just to fix tests.

Open to changing this if there's a good reason to but that's the rationale I had for fixing tests rather than these checks.

**Comment by calvn** [comment]
I think it might be still good to check `req.Connection` to prevent panics, perhaps with `req.Connection == nil || ...` instead, in case we somehow forget to populate Connection in the request.

**Comment by jefferai** [comment]
@calvn that's fine but then let's reject if no connection object found but len of bound cidrs  is greater than zero. What I don't think we should do is allow connections when we don't know connection info but bound cidrs is not empty.

**Comment by jefferai** [comment]
Obsoleted by #7163

**Pull request closed without merging**
