### PR TITLE
Vault-6037 making filesystem permissions check opt-in

### PR DESCRIPTION
**Pull request by akshya96**
https://hashicorp.atlassian.net/browse/VAULT-6037
Making this change opt-in, by renaming the environment variable VAULT_DISABLE_FILE_PERMISSIONS_CHECK to VAULT_ENABLE_FILE_PERMISSIONS_CHECK and adjusting the logic

### CODE REVIEW

**Review by HridoyRoy — COMMENTED** [review]
Looks good overall -- just wondering if we are ok with removing the `consts.VaultDisableFilePermissionsCheckEnv` environment variable entirely, as it seems like this change is also going to be backported into minor versions?

**Comment by akshya96** [comment]
> Looks good overall -- just wondering if we are ok with removing the `consts.VaultDisableFilePermissionsCheckEnv` environment variable entirely, as it seems like this change is also going to be backported into minor versions?
Looks like these changes were removed from back ports

**Review by HridoyRoy — APPROVED** [review]
Lgtm!

**Comment by cipherboy** [comment]
@akshya96 As I mentioned in #15438, do you think we can switch this from a literal value to `strconv.ParseBool` [like most of the other server envvars are](https://github.com/hashicorp/vault/blob/main/command/server.go#L1161-L1184)? This'd give us a little more consistency :-)

**Comment by akshya96** [comment]
> @akshya96 As I mentioned in #15438, do you think we can switch this from a literal value to `strconv.ParseBool` [like most of the other server envvars are](https://github.com/hashicorp/vault/blob/main/command/server.go#L1161-L1184)? This'd give us a little more consistency :-)
> 
> I'm happy to open a PR once this lands if you'd prefer.

Sure, It makes sense to be more consistent. Will make this change and update the PR

**Comment by cipherboy** [comment]
Thank you!!

**Review by cipherboy — APPROVED** [review]
Thank you! :100:

**Pull request merged**
