### PR TITLE
Fix: Only render JWT input field for mounts configured for JWT auth

### PR DESCRIPTION
**Pull request by austingebauer**
### Description
This PR inverts the logic that decides when to render the JWT input field of the Vault UI login form.

Currently, the JWT input field is rendered until OIDC auth is configured. This was a source of confusion for Vault users as they were configuring OIDC auth. With this change, the JWT input field will not be rendered until it's known that JWT auth is configured for the mount.

To know when JWT auth is configured for a mount, an error message from [vault-plugin-auth-jwt/path_oidc.go#L346](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/path_oidc.go#L346) is used. This error is a reliable signal that the mount has not been set up for an OIDC flow. An additional change will be made in [vault-plugin-auth-jwt](https://github.com/hashicorp/vault-plugin-auth-jwt) to make the error message a constant with a comment noting that changing it will have consequences in the UI.

Find below a table of `/auth_url` responses at steps of configuring both OIDC and JWT auth that influenced the decision to use the error message:

| Config Step | OIDC Response `/auth_url` | JWT Response `/auth_url` |
|---|-------|-----|
| 0. Not Configured  | missing client token (400) | missing client token (400) |
| 1. Auth Enable     | could not load configuration (400) | could not load configuration (400) |
| 2. Write Config    | role "..." could not be found (400) | **OIDC login is not configured for this mount** (400) |
| 3. Write Role      | .data.auth_url non empty (200) | **OIDC login is not configured for this mount** (400) |

### Testing

I've manually tested that the UI:
- Doesn't show the JWT input field by default
- Shows the JWT input field when a mount has been configured for JWT auth
- Allows for successful OIDC and JWT authentication

Automated UI tests are fixed in this PR.

### CODE REVIEW

**Comment by austingebauer** [comment]
Please see linked gif showing the JWT input field appearing after JWT auth is configured:
- https://gist.github.com/austingebauer/74c067f744f5624348cf09fbf9d4c90d

**Comment by kalafut** [comment]
It would be good to make the error message `const` in https://github.com/hashicorp/vault-plugin-auth-jwt too for stable interop with the UI.

**Comment by austingebauer** [comment]
@kalafut indeed. I've done that in https://github.com/hashicorp/vault-plugin-auth-jwt/pull/112.

**Comment by kalafut** [comment]
👍  I'll let others review the JS 😉

**Comment by austingebauer** [comment]
Thank you, @noelledaley 👍

**Pull request merged**
