### PR TITLE
Add DataStax Astra DB to Partner DBs

### PR DESCRIPTION
**Pull request by johnsmartco**
🔍 [Deploy Preview](https://vault-git-fork-johnsmartco-patch-1-hashicorp.vercel.app/vault/docs/plugins/plugin-portal#partner)

### CODE REVIEW

**Comment by johnsmartco** [comment]
Please note that in the DataStax Astra DB plugin's GH repo, the latest doc updates for dynamic tokens are in this PR, not yet merged:

https://github.com/datastax/vault-plugin-secrets-datastax-astra/pull/10

**Comment by acahn** [comment]
@yhyakuna - This PR is from one of our technologies partners and is good to go. Please let us know if there is anything missing?

Thank you!

**Review by yhyakuna — APPROVED** [review]
Looks good to me.

I guess we need to wait for the https://github.com/datastax/vault-plugin-secrets-datastax-astra/pull/10 to be merged before we can merge this doc PR?

**Comment by johnsmartco** [comment]
@yhyakuna , thanks!  Yes I believe we could wait until my DataStax Astra DB plugin... repo's PR is merged with the doc updates.  But I'll check with our Product Manager and let you know.

**Comment by johnsmartco** [comment]
@yhyakuna , thanks again. I'll let you know here when my Astra DB doc PR is merged.  Might be as late as 10-Nov, but perhaps sooner.

**Comment by yhyakuna** [comment]
@johnsmartco Sounds good 👍

**Comment by johnsmartco** [comment]
@yhyakuna thanks for your patience.  We merged our (DataStax) doc PR with the plugin updates. If you agree you can go ahead and merge this PR. Many thanks!

**Comment by johnsmartco** [comment]
Thank you @yhyakuna.

**Pull request merged**
