### PR TITLE
Added PostgreSQL physical backend

### PR DESCRIPTION
**Pull request by pradeepchhetri**
**Note**: Will work only with postgresql version >= 9.5 since it added the `upsert` feature (insert .. on conflict)

### CODE REVIEW

**Comment by pradeepchhetri** [comment]
I am not sure why the test has failed. Can someone help me in figuring it out.

**Comment by pradeepchhetri** [comment]
Is this useful otherwise maintainers can go ahead and close it.

**Comment by jefferai** [comment]
@pradeepchhetri Sure, it's useful, it will just be a while before we can take a look at it, unfortunately.

**Comment by Gibheer** [comment]
It would be really nice to have this included.

**Comment by jefferai** [comment]
Closing in favor of #945

**Pull request closed without merging**
