### PR TITLE
SSH: Fix response code for ssh/verify

### LINKED ISSUE #962: SSH OTP documentation/behavior inconsistent
If an OTP isn't found, `nil` is returned as the response, leading to a 204 return code. If one is found, a response is returned. This isn't reflected in the documentation. Additionally, perhaps if an otp isn't found, an error should be thrown (e.g. 404).

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #962

### CODE REVIEW

**Comment by jefferai** [comment]
Sorry, put a comment in #962 instead of here  :-/

**Comment by vishalnayak** [comment]
@jefferai no problem. 

I said 400 response code because, I am not setting it anywhere.
logical.ErrorResponse is doing it.

And when we do a cleanup of request-response (your other plan), I though we would then make it 404.

**Comment by jefferai** [comment]
That's true, that doesn't make it super easy.

**Comment by jefferai** [comment]
LGTM! :ship:

**Pull request merged**
