### PR TITLE
Fix #392 by giving a more specific error

### LINKED ISSUE #392: duplicate POST to sys/auth/app-id gives 500
Not sure if this is desired or not, but it seems like a `409 Conflict` (or something else in the 400s) would be more appropriate than a `500`. Below are steps to illustrate the behavior:

    $ curl -i -X POST http://172.20.20.11:8200/v1/sys/auth/app-id -H "X-Vault-Token: `cat root_token`" -d '{"type":"app-id"}'
    HTTP/1.1 204 No Content 
    Content-Type: application/json
    Date: Fri, 03 Jul 2015 23:58:49 GMT

    $ curl -i -X POST http://172.20.20.11:8200/v1/sys/auth/app-id -H "X-Vault-Token: `cat root_token`" -d '{"type":"app-id"}'
    HTTP/1.1 500 Internal Server Error
    Content-Type: application/json
    Date: Fri, 03 Jul 2015 23:58:51 GMT
    Content-Length: 31

    {"errors":["invalid request"]}
    $ curl -i -X DELETE http://172.20.20.11:8200/v1/sys/auth/app-id -H "X-Vault-Token: `cat root_token`"                                           
    HTTP/1.1 204 No Content
    Content-Type: application/json
    Date: Fri, 03 Jul 2015 23:58:54 GMT

    $ curl -i -X POST http://172.20.20.11:8200/v1/sys/auth/app-id -H "X-Vault-Token: `cat root_token`" -d '{"type":"app-id"}'
    HTTP/1.1 204 No Content
    Content-Type: application/json
    Date: Fri, 03 Jul 2015 23:58:56 GMT

### PR DESCRIPTION
**Pull request by ctennis**
Making use of my previous pull req, this fixes #392.

### CODE REVIEW

**Comment by ctennis** [comment]
Strange, the tests don't fail when I run then locally.

**Comment by sethvargo** [comment]
@ctennis are you using godeps to test?

**Comment by ctennis** [comment]
@sethvargo Yeah, even running "make test testrace" which the travis job does runs the same set of tests, but it doesn't fail.

What's odd is the failing job:

--- FAIL: TestLogical_StandbyRedirect-2 (0.03s)
	http_test.go:54: Expected status 307, got 204. Body:

That shouldn't have any impact by this patch.

Also, in https://github.com/hashicorp/vault/pull/522 the same test failed there.  Is something wrong with travis perhaps?

**Comment by ctennis** [comment]
I pushed a trivial change and it didn't fail, so something must have been either funky with travis or we have a data race somewhere.

**Comment by armon** [comment]
Thanks!

**Pull request merged**
