### PR TITLE
cli/api: Update plugin listing to always include version info in the response

### PR DESCRIPTION
**Pull request by tomhjp**
I found an issue where `vault plugin list -detailed auth` returned an empty response. There was also a small bug in the `api` package's JSON tags that stopped `type` getting populated in details.

```shell-session
$ vault plugin list -detailed auth
Name    Type    Version    Deprecation Status
----    ----    -------    ------------------
```

api: Updated the typed call to always use the untyped API so that it can always include the extra details like version etc.
cli: Added `detailed` key to JSON output, and type/version to non-detailed output because a plugin name on its own is not enough to specify a plugin, so it's not very informative to just list the names.

New output:

```shell-session
$ vault plugin list secret
Name             Version
----             -------
kv               v0.13.0+builtin
mongodb          v1.13.0+builtin.vault
...

$ vault plugin list -detailed auth
Name          Type    Version                  Deprecation Status
----          ----    -------                  ------------------
alicloud      auth    v0.13.0+builtin          supported
app-id        auth    v1.13.0+builtin.vault    pending removal
...

$ vault plugin list
Name                                 Type        Version
----                                 ----        -------
alicloud                             auth        v0.13.0+builtin
app-id                               auth        v1.13.0+builtin.vault
...

$ vault plugin list -format=json
{
  "auth": [
    "alicloud",
    ...
  ],
  "database": [
    "cassandra-database-plugin",
    "couchbase-database-plugin",
    ...
  ],
  "details": [
    {
      "type": "auth",
      "name": "alicloud",
      "version": "v0.13.0+builtin",
      "builtin": true,
      "deprecation_status": "supported"
    },
    ...

$ vault plugin list -format=json auth
{
  "auth": [
    "alicloud",
    ...
  ],
  "details": [
    {
      "type": "auth",
      "name": "alicloud",
      "version": "v0.13.0+builtin",
      "builtin": true,
      "deprecation_status": "supported"
    },
    ...
```

### CODE REVIEW

**Review by tvoran — COMMENTED** [review]
This seems to work for me, though I am noticing that `vault plugin list secret` output is not sorted by name, while `vault plugin list auth` is (whether `-detailed` is supplied or not).

**Comment by tomhjp** [comment]
> `vault plugin list secret` output is not sorted by name

Good spot! There was a silly sorting bug which I've fixed in 1c6a3d1

**Review by tvoran — APPROVED** [review]
Looks like this test needs to be updated, but otherwise 👍 

https://github.com/hashicorp/vault/blob/f4b05c490c68d0fe57893583a7340b69ea058075/command/plugin_list_test.go#L36-L42

**Review by mpalmi — APPROVED** [review]
Looks good to me! Should we update the docs to show the new output?

**Comment by tomhjp** [comment]
> Should we update the docs to show the new output?

Thanks for the reminder! Done in bfab936

**Pull request merged**
