### PR TITLE
Fix segfault when seal block is removed

### LINKED ISSUE #8397: Vault segfaults if removing auto-unseal from config
**Describe the bug**
If first configuring vault with Google Cloud KMS for auto-unseal, then removing that from the config and starting up, the server will segfault.

**To Reproduce**
1. Initialize a vault with Google Cloud KMS auto-unseal
2. Remove the `seal` block from the config and restart.
3. See error

**Expected behavior**
Clear error message that some config combination is invalid.

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.3.2
* Vault CLI Version (retrieve with `vault version`): 1.3.2
* Server Operating System/Architecture: Debian 10

Vault server configuration file(s):

```json
{
  "api_addr": "https://<private-ip>:8200",
  "cluster_name": "thusoy-test-vault",
  "listener": {
    "tcp": {
      "address": "0.0.0.0:8200",
      "tls_cert_file": "/etc/vault/cert.pem",
      "tls_cipher_suites": "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "tls_key_file": "/etc/vault/key.pem",
      "tls_prefer_server_ciphers": "true"
    }
  },
  "seal": {
    "gcpckms": {
      "crypto_key": "vault-test-01",
      "key_ring": "vault-test",
      "project": "test-vault-<project-id>",
      "region": "us-west2"
    }
  },
  "storage": {
    "gcs": {
      "bucket": "thusoy-test-vault",
      "ha_enabled": "true"
    }
  },
  "ui": true
}
```
Remove the `seal` block to provoke the crash.

**Additional context**
```
systemd[1]: Started Vault.
vault[2276]: ==> Vault server configuration:
vault[2276]:              Api Address: https://10.168.0.4:8200
vault[2276]:                      Cgo: disabled
vault[2276]:          Cluster Address: https://10.168.0.4:8201
vault[2276]:               Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "enabled")
vault[2276]:                Log Level: info
vault[2276]:                    Mlock: supported: true, enabled: true
vault[2276]:            Recovery Mode: false
vault[2276]:                  Storage: gcs (HA available)
vault[2276]:                  Version: Vault v1.3.2
vault[2276]: panic: runtime error: invalid memory address or nil pointer dereference
vault[2276]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x292e292]
vault[2276]: goroutine 1 [running]:
vault[2276]: github.com/hashicorp/vault/command.adjustCoreForSealMigration(0x3b18640, 0xc00069ff80, 0xc0008bd600, 0x3b1ea80, 0xc0005b22d0, 0x0, 0x0, 0x1, 0xc0007bd020)
vault[2276]: #011/go/src/github.com/hashicorp/vault/command/server_util.go:92 +0x282
vault[2276]: github.com/hashicorp/vault/command.(*ServerCommand).Run(0xc000645900, 0xc00004c0a0, 0x2, 0x2, 0x0)
vault[2276]: #011/go/src/github.com/hashicorp/vault/command/server.go:1437 +0x4547
vault[2276]: github.com/hashicorp/vault/vendor/github.com/mitchellh/cli.(*CLI).Run(0xc0000dda40, 0xc0000dda40, 0xc0001e7ea0, 0xc0001e7da0)
vault[2276]: #011/go/src/github.com/hashicorp/vault/vendor/github.com/mitchellh/cli/cli.go:255 +0x1f1
vault[2276]: github.com/hashicorp/vault/command.RunCustom(0xc00004c090, 0x3, 0x3, 0xc0000a7680, 0xc000090058)
vault[2276]: #011/go/src/github.com/hashicorp/vault/command/main.go:180 +0x862
vault[2276]: github.com/hashicorp/vault/command.Run(...)
vault[2276]: #011/go/src/github.com/hashicorp/vault/command/main.go:88
vault[2276]: main.main()
vault[2276]: #011/go/src/github.com/hashicorp/vault/main.go:10 +0x6c
systemd[1]: vault.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

### PR DESCRIPTION
**Pull request by vishalnayak**
Fixes #8397

### CODE REVIEW

**Comment by vishalnayak** [comment]
In addition to the changes in this PR, I wonder if `migrationSeal` being nil when `newSeal` is non-nil is a good case for erroring out.

**Comment by ncabatoff** [comment]
It looks like newSeal should never be nil because the only non-test caller of adjustCoreForSealMigration errors out if it is.  

> In addition to the changes in this PR, I wonder if migrationSeal being nil when newSeal is non-nil is a good case for erroring out.

I thought that migrationSeal==nil was a valid use case, i.e. we're not migrating?

**Comment by mjarmy** [comment]
Is it possible to test this fix with a unit test?

**Comment by vishalnayak** [comment]
> It looks like newSeal should never be nil because the only non-test caller of adjustCoreForSealMigration errors out if it is.
> 
> > In addition to the changes in this PR, I wonder if migrationSeal being nil when newSeal is non-nil is a good case for erroring out.
> 
> I thought that migrationSeal==nil was a valid use case, i.e. we're not migrating?

You are right. We can't error out.

**Comment by calvn** [comment]
Should this go in for 1.4.1 instead?

**Pull request merged**
