### PR TITLE
Initial CLI autocomplete support

### PR DESCRIPTION
**Pull request by brianshumate**
This enables the initial for-free sub-command autocompletion feature from [mitchellh/cli](https://github.com/mitchellh/cli). More details are in the [feature commit message](https://github.com/mitchellh/cli/pull/58).

I vendored the latest CLI, built `vault`, and verified that `consul -autocomplete-install` and basic sub-command completion was occurring for me in `zsh` with the changes! 🎉

Also added [Name:](https://github.com/mitchellh/cli/blob/master/cli.go#L64-L65) as well because Autocomplete errors without it:

```
./bin/vault
Error executing CLI: internal error: CLI.Name must be specified for autocomplete to work
```

As I understand it, there needs to be additional work done for completion on specific CLI flags and so on to make things more feature complete, but the basics are there as a starting point if we want to use it.

### CODE REVIEW

**Comment by brianshumate** [comment]
Also, is there a better way to refer to the program name than the static string that could be used for the `Name:` value?

**Comment by brianshumate** [comment]
Ooops dupe of 3223. Closing.

**Comment by abdennour** [comment]
Why this is closed ? We have zsh and we want to setup autocompletion

**Comment by calvn** [comment]
This has been addressed by #3287.

**Pull request closed without merging**
