### PR TITLE
UI: bump HDS to 4.7.0

### PR DESCRIPTION
**Pull request by hashishaw**
### Description
This PR bumps our HDS dependency to ~4.7, and replaces a previous custom input using `type="month"` with the updated HDS input which supports `type="month"`. 

Updated inputs in action

I did not update to the latest HDS version (4.9.0), because when I did I saw weird button behavior in the namespace picker: 
Buttons in namespace picker are black background instead of white

### CODE REVIEW

**Review by Monkeychip — APPROVED** [review]
Nice to get this in before we start doing qa on the binary. Thanks for tackling!

**Comment by KristinLBradley** [comment]
@hashishaw I am checking into the button styling within Dropdowns. I will keep you updated.

**Comment by KristinLBradley** [comment]
@hashishaw

**Button style issue update:**
There is an issue with inheritance of dark theme colors for Hds::Button components nested within Hds::Dropdown components which I discovered and am currently working to resolve. However, in investigating the issue which was screen shotted above with buttons within the Vault namespace picker, I found that it does not use HDS components for either the dropdown or the buttons nested inside. So it seems to resolve the styling issues for the buttons, the custom CSS for them within Vault will need to be updated or else (more preferably if feasible) the namespace picker and nested buttons inside could be reworked to use HDS components.

**Comment by KristinLBradley** [comment]
@chelshaw for the issue with button styles within the SideNav, do you think it would be possible for you to use `Hds::Button` components for the buttons within the NamespacePicker even if you aren't able to update the actual dropdown component it is using at this time?

When the bug fix for style inheritance in the SideNav goes out in the next release, if you are able to update to use HDS Buttons then I believe the styling issue will be resolved although I can work with you to help at that time.

Merged bug fix PR: https://github.com/hashicorp/design-system/pull/2359

**Pull request merged**
