### PR TITLE
Add metrics around leadership

### LINKED ISSUE #1544: add master changed telemetry event
when vault flips who the master is, it would be *super* helpful to log a telemetry event (perhaps something like `vault.core.new_leader`). 

The root issue is that I want to know immediately if Vault starts to flutter, as that is usually a strong indication that the vault cluster will, or already has become unavailable.  Now there are secondary indicators galore, such as if the HA backend (consul in my case) is fluttering.  But that isn't always a direct indicator, and neither is host network, CPU, or mem.  Having a direct metric that I can watch like a hawk would be fantastic.

### PR DESCRIPTION
**Pull request by jefferai**
This can be helpful for detecting flapping.

Fixes #1544

### CODE REVIEW

**Comment by vishalnayak** [comment]
LGTM!

**Comment by LLBennett** [comment]
LGTM, I'm glad we're adding this.

**Comment by skippy** [comment]
thanks folks!

**Comment by jefferai** [comment]
@skippy Would you mind taking a look at the code changes and seeing if you think they're good enough for what you need? I think so, but it doesn't hurt if you want to put eyes on it.

**Comment by skippy** [comment]
@jefferai I think this will work for my use-case. I was specifically thinking of a vault-equivalent to `consul.serf.events.consul_new_leader`.  This is the inverse (leader lost vs leader gained) but it is still the same thing as there is only one leader :)

thank you for putting this change in.

**Comment by jefferai** [comment]
Yep -- I was thinking of putting in leader gained, but I realized that there are potential failure conditions on the path to leadership (hence the leadership error metrics), and also that it might be useful to understand how long leadership was held for since the metrics are generally meant to show duration. It would be easy to put in an additional metric with a 0-length duration when leadership is gained, if that's useful.

**Pull request merged**
