### PR TITLE
changelog: updates for 1.13.2, 1.12.6, 1.11.10

### PR DESCRIPTION
**Pull request by cinthiaconti**
Update changelog for 1.13.2, 1.12.6, 1.11.10 releases

### CODE REVIEW

**Review by mladlow — APPROVED** [review]
Looks good! I didn't go through the content line by line (and typically don't for these PRs). I did check out the file on the branch to verify the formatting looks correct.

**Comment by mladlow** [comment]
Note that you can use the `/docs/` prefix on your branch name to skip running some tests, since changing this file shouldn't impact functionality.

**Review by anwittin — APPROVED** [review]
Everything looks good.

**Comment by cinthiaconti** [comment]
> Note that you can use the `/docs/` prefix on your branch name to skip running some tests, since changing this file shouldn't impact functionality.

Thanks! I will add this to the checklist!

**Pull request merged**
