### PR TITLE
Propose fix a typo

### PR DESCRIPTION
**Pull request by jeis2497052**
does it help to update the spelling?

### CODE REVIEW

**Comment by jefferai** [comment]
Updating spelling is always nice, however, the vendored deps need to be updated upstream. The first three are fine though!

**Comment by jeis2497052** [comment]
understood.  Just trying to contribute.

**Comment by jefferai** [comment]
Sure. Pull that one change from the PR and I'll merge the rest!

**Comment by jefferai** [comment]
Thanks! 👍

**Comment by jeis2497052** [comment]
is this revert OK?

**Pull request merged**
