### PR TITLE
Update news section with March 22 webinar video

### PR DESCRIPTION
**Pull request by ryon**
By Amanda MacLeod's request

Also tweaks some of the news section styling to accommodate future updates.

### CODE REVIEW

**Comment by jefferai** [comment]
I don't believe that this news section is used for anything at all, so we probably should not add to it.

**Comment by captainill** [comment]
@jefferai Here's a look at the 'Latest' section with the updated item @ryon added per our marketing folks:

image

**Comment by ryon** [comment]
The news section has been updated with more recent items and is now populated by a YAML data file.

**Comment by briankassouf** [comment]
@ryon Is this ready to be merged now?

**Comment by ryon** [comment]
Yes please @briankassouf

**Comment by jefferai** [comment]
Don't we want 0.7.0 in the news feed? It was a huge release.

**Comment by ryon** [comment]
Hi @jefferai, Vault 0.7.2 will be in the news feed when this PR is merged. Sorry I didn't update the screenshot when I updated the code, but you can see https://github.com/ryon/vault/blob/4831922200c0fe024c2c8cc4eae6296b0d7927ac/website/data/news.yml for a current list of posts.

**Comment by jefferai** [comment]
@ryon 0.7.0 still won't be though...

**Pull request merged**
