### PR TITLE
added an allow_these_domains parameter to the PKI secrets backend

### PR DESCRIPTION
**Pull request by chris-west-travelex**
Our use-case involves app-id-authenticated micro-services fetching their own server certificates and keys from the PKI backend for TLS setup. Each service should only be able to get a server cert for itself, but none of the existing PKI backend options allowed this -- the closest was `allow_token_displayname`, but it prepends "app-id-" to the token, and this would have ended up in all of our service names as a consequence.

This PR adds a comma-delimited whitelist of common names that the client is allowed to request from the backend. It stacks with `allowed_base_domain` and is overridden by `allow_any_name`.

I've tried to update the documentation and add some unit test coverage. The change has also been tested in a local docker-compose setup.

### CODE REVIEW

**Comment by jefferai** [comment]
Hi @chris-west-travelex ,

Thanks for the suggestion, and this is a use-case we'd definitely like to handle, but unfortunately this PR came in just after the merge window for 0.4 closed so this will have to wait until a future release. I will also have to think about whether we want to add another parameter or simply change the existing parameter to handle a multiple-domain string; I'm leaning towards the latter.

**Comment by jefferai** [comment]
Just an update -- we had a product meeting today and decided to try to get this in today and issue a second RC.

**Comment by jefferai** [comment]
@chris-west-travelex If you can, please take a look at the current state of the `pki-csrs` branch, which has changed `allowed_base_domain` to `allow_domains`. I think your case should be supported. The particular commit that went in to address this is https://github.com/hashicorp/vault/commit/bd03d3c422852bb9d4df8240d7d4e487ff878a03

**Comment by chris-west-travelex** [comment]
Will do, thanks!

**Comment by chris-west-travelex** [comment]
@jefferai i've built and tested the latest from the `pki-csrs` branch and it absolutely does what we need it to do, which is great. I'll close this PR; thanks for your help.

**Comment by jefferai** [comment]
Great! Sorry I couldn't use this PR but when we decided to simply change the main parameter the differences got too great. It did provide the nudge that got us thinking "yeah, we really need to support this".

**Pull request closed without merging**
