### PR TITLE
Docs: fix inaccurate claim that audit log contains all requests

### PR DESCRIPTION
**Pull request by maxb**

### CODE REVIEW

**Comment by maxb** [comment]
Please label `pr/no-changelog` - pure docs change.

**Comment by hsimon-hashicorp** [comment]
@yhyakuna Can you take a look at this please? :)

**Comment by hsimon-hashicorp** [comment]
Also @maxb this looks like it needs rebasing. :)

**Review by brianshumate — APPROVED** [review]

**Comment by maxb** [comment]
Hi @brianshumate - thanks for the approval. What is the next step to get this merged?

**Comment by maxb** [comment]
Hi @hsimon-hashicorp , what is the next step for this PR now that it has an approval? Thanks!

**Comment by hsimon-hashicorp** [comment]
> Hi @hsimon-hashicorp , what is the next step for this PR now that it has an approval? Thanks!

Hi there! I'll get it merged and backported. Thanks again for your efforts!

**Pull request merged**
