### PR TITLE
Add "Edit this page" link everywhere except /

### PR DESCRIPTION
**Pull request by handlers**
This PR adds an 'edit this page' link everywhere on the website except the homepage.

Note that I've run `bundle update middleman-hashicorp` to bring in the changes from [this update](https://github.com/hashicorp/middleman-hashicorp/commit/fc131cfce2a1d5c8671812d9844a944ebb4bd92f) to that gem.

Also note I've added a Makefile, following the [pattern in this PR](https://github.com/mitchellh/packer/pull/2396/files).

### CODE REVIEW

**Comment by handlers** [comment]
Currently investigating broken build

**Comment by handlers** [comment]
Hm, @jefferai am I right that Travis freaking out is not cause for concern, given that this PR is limited to the `/website` directory? I see that one other PR has [tripped up Travis before](https://github.com/hashicorp/vault/pull/637/files).

**Comment by jefferai** [comment]
True story, Travis freaking out has absolutely nothing to do with you. It's a race condition with the in-memory high-availability testing backend that causes failures now and again, and I need to fix at some point (basically, there's no mechanism to tell it which of the testing servers should be leader at any given time, so the test cases make assumptions that are sometimes true but not always true). Feel free to merge it if the HTML is looking fine!

**Comment by handlers** [comment]
Cool, thanks for the look! My local dev and build look fine, so I'm merging.

**Pull request merged**
