### PR TITLE
Add Session tags and external id support for AWS Secrets

### LINKED ISSUE #3790: AWS backend stsAssume with "External ID"
**Feature Request:**
Security improvement for AWS backend "External ID" parameter for stsAssume operation.
More about "External ID"
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

**Expected Behavior:**
Possibility to assume role with "External ID" parameter.

### PR DESCRIPTION
**Pull request by harsimranmaan**
It is now possible to set the AWS session tags and external id when assuming an IAM role via STS AssumeRole.

Here's an example setup

AWS Role - Trust relationship needs the `sts:TagSession` permission set as described in https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_permissions-required
```bash
vault secrets enable aws
vault write aws/config/root access_key=<key> secret_key=<secret> region=us-west-2
vault write aws/roles/my-role credential_type=assumed_role max_sts_ttl=1h role_arns="arn:aws:iam::000000000000:role/test" session_tags="department=eng" session_tags="project=p1" external_id=123
```

Read the role definition
```
vault read  aws/roles/my-role
Key                         Value
---                         -----
credential_type             assumed_role
default_sts_ttl             0s
external_id                 123
iam_groups                  <nil>
iam_tags                    <nil>
max_sts_ttl                 1h
permissions_boundary_arn    n/a
policy_arns                 <nil>
policy_document             n/a
role_arns                   [arn:aws:iam::000000000000:role/test]
session_tags                map[department:eng project:p1]
user_path                   n/a
```

```bash
vault read  aws/sts/my-role
Key               Value
---               -----
access_key        XXXX
arn               arn:aws:sts::000000000000:assumed-role/test/vault-token-my-role-1674516375-mBKZQssrwtP6gl3kbmWq
secret_key        XXX
security_token    XXX
ttl               59m59s
```

The cloudtrail for AssumeRole looks like
```
	"userIdentity": {
        "type": "IAMUser",
        "principalId": "XXX",
        "arn": "arn:aws:iam::000000000000:user/vault-user",
        "accountId": "000000000000",
        "accessKeyId": "XXX",
        "userName": "vault-user"
    },
    "eventTime": "2023-01-23T23:31:12Z",
    "eventSource": "sts.amazonaws.com",
    "eventName": "AssumeRole",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "XXX",
    "userAgent": "aws-sdk-go/1.44.128 (go1.19.5; darwin; arm64)",
    "requestParameters": {
        "roleArn": "arn:aws:iam::000000000000:role/test",
        "roleSessionName": "vault-token-my-role-1674516375",
        "durationSeconds": 3600,
        "tags": [
            {
                "key": "department",
                "value": "eng"
            },
            {
                "key": "project",
                "value": "p1"
            }
        ],
        "externalId": "123"
    },
	...
```

When using the creds are used for accessing an S3 resource with Attribute-based Access Control (ABAC), you can now see that only requests with principalTag project=p1 are allowed while requests to path p2 are denied.

```
aws s3 cp a.txt s3://session-tags-test/p1/a.txt
upload: ./a.txt to s3://session-tags-test/p1/a.txt
➜  ~ aws s3 cp a.txt s3://session-tags-test/p2/a.txt
upload failed: ./a.txt to s3://session-tags-test/p2/a.txt An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

The IAM policy had the following block in the above case
```
	{
            "Action": [
                "s3:Describe*",
                "s3:Get*",
                "s3:List*",
                "s3:PutObject*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::session-tags-test/${aws:PrincipalTag/project}/*",
                "arn:aws:s3:::session-tags-test/${aws:PrincipalTag/project}"
            ]
        }
```

Troubleshooting:
Error:
```
 Error assuming role: AccessDenied: User: arn:aws:iam::000000000000:user/vault-user is not authorized to perform: sts:TagSession on resource: arn:aws:iam::000000000000:role/test
	status code: 403, request id: ba8ab60e-2fdf-4668-81ad-5fe83e9b898e
```

Remedy: Assign the `sts:TagSession` permission to the `arn:aws:iam::000000000000:role/test`. See https://docs.aws.amazon.com/IAM/latest/UserGuide/id_session-tags.html#id_session-tags_permissions-required

Error:
```
* Error assuming role: AccessDenied: User: arn:aws:iam::000000000000:user/vault-user is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::000000000000:role/test
	status code: 403, request id: c0117588-9c84-490d-9b36-91135545dec1
```
Remedy: If the external ID is set, follow https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html to ensure that external ID matches the ID set on the role. If you have not added the externalID condition on the role, it would not affect the assume role operation when an external ID is set only in Vault.

This change does not add support for transitive keys but it should be simple to add it in the future.

Closes #3790 #7960

### CODE REVIEW

**Comment by harsimranmaan** [comment]
Hi @hsimon-hashicorp, any chance this could be reviewed by the team? Would like this to make the cut for 1.13

**Comment by snakebyte91** [comment]
Would be very good if you could pass the external id to the aws/sts endpoint:

```shell
vault write aws/sts/my-role ttl=10m external-id=<external-id>
```

So even a Vault admin could not assume the IAM role without the external id.

**Comment by harsimranmaan** [comment]
> Would be very good if you could pass the external id to the aws/sts endpoint:
> 
> ```shell
> vault write aws/sts/my-role ttl=10m external-id=<external-id>
> ```
> 
> So even a Vault admin could not assume the IAM role without the external id.

That could be done as an extension to this.

**Comment by harsimranmaan** [comment]
rebased and resolved merge conflicts.

**Comment by catrielg** [comment]
This feature is super useful and needed. Is there any ETA on when it will be available and documented?

**Comment by catrielg** [comment]
bump @hsimon-hashicorp - any chance this can be implemented ?

**Comment by edenzv** [comment]
I'm join to @catrielg that this feature is needed. @hsimon-hashicorp  any chance this can be implemented soon?

**Comment by asvinours** [comment]
This was released in 1.17.0, I think it covers part of this request? https://github.com/hashicorp/vault/pull/26628

**Comment by leirtac12** [comment]
@asvinours You're correct, this does indeed cover **part** of this request. Unfortunately the feature that is most useful to me is the session tags part as we rely on them for ABAC.

**Comment by robmonte** [comment]
Hi @harsimranmaan 
Thank you for the contribution!

Would you be interested in updating this PR once again to account for recent changes causing merge conflicts? My initial look seems good but I'd like to give it a more thorough test after the conflicts get resolved.

**Review by robmonte — APPROVED** [review]
Looks good to me. Seems like `builtin/logical/aws/backend_test.go` needs to be updated but only to account for the two new fields in the expected output then it's good to go!

**Comment by benashz** [comment]
Hi @harsimranmaan,

Since adding this feature requires more extensive testing, we are going to be taking over the work needed to land it. Thanks again for your contribution to HashiCorp!

-ben

**Pull request closed without merging**
