### PR TITLE
Redis physical backend

### PR DESCRIPTION
**Pull request by certifiedloud**
This is obviously a WIP. I'm hoping to get some guidance on the 'client' idiom. I tried following the logic of the other implemented backends and got stuck on this bit. It seems like 'client' is essentially pointing to the api wrapper that I'm using to connect to redis (gore, in this case). 

I am also very open to comments on any other part of the code so far.

### CODE REVIEW

**Comment by certifiedloud** [comment]
Got the tests passing, however running vault init generates this error:
[ERR] core: failed to decode seal configuration: unexpected end of JSON input

I'll look into it some more soon. If anyone knows the cause let me know.

**Comment by armon** [comment]
@certifiedloud I haven't reviewed this in PR in detail, however I'm pretty firmly against merging in support for Redis as a storage backend. We try our best with Vault to ensure that sane defaults are used for everything, and to minimize the possibility of a user shooting themselves in the foot. With respect to the storage backends, they need to provide a modest level of write throughput, and above all durability. Read performance is rarely a concern as Vault does write-through caching.

With that context, Redis is an incredibly poor choice. By design, it is an in-memory storage engine. It also does not support efficient key listing by prefix. This makes it incredibly easy for a user to lose data and additionally makes list performance quite terrible. The in-memory benefits are largely lost on Vault anyways due to read caching.

**Comment by certifiedloud** [comment]
Noted. Thanks for the feedback. 

I wrote this mainly to get an idea for how Vault is implemented ans because I am interested in contributing to the project. If there are other backends that have been discussed but not yet implemented, I would be happy to get the ball rolling on those.

**Comment by armon** [comment]
@certifiedloud A very useful storage backend that is missing is a MySQL or PostgreSQL provider. That would be very useful if that is something you want to tackle!

**Comment by armon** [comment]
I'm going to close the PR on your suggestion

**Pull request closed without merging**
