### PR TITLE
Bump go version to 1.19.4 for v1.11.7

### PR DESCRIPTION
**Pull request by mpalmi**

### CODE REVIEW

**Comment by swenson** [comment]
Ah, this has to do with the fix only being applied in `main`. I'd recommend adding a:

```go
func init() {
    internal.PatchSha1()
}
```

In the module for any broken test.

**Comment by cipherboy** [comment]
@swenson Do you mind opening a PR? This looks like its in Ecosystem's AWS provider:

> `github.com/hashicorp/vault/builtin/credential/aws/pkcs7`

**Comment by swenson** [comment]
@cipherboy on it

**Comment by swenson** [comment]
It is slightly more complicated sadly: https://github.com/hashicorp/vault/pull/18399

**Review by cipherboy — APPROVED** [review]
Thanks all!

**Pull request merged**
