### PR TITLE
add examples for ECC key sizes in documentation

### PR DESCRIPTION
**Pull request by IPv4v6**
Signed-off-by: Stefan Pietsch <mail.ipv4v6+gh@gmail.com>

### CODE REVIEW

**Comment by jefferai** [comment]
Thanks! I think it's nice to expand this documentation, however, I would prefer not to link to the Go docs since if they add more key sizes and Vault doesn't yet support them people may be confused. It'd be nicer to explicitly call out the supported key sizes, even though they match what Go supports for now.

**Comment by chrishoffman** [comment]
@IPv4v6 Would you mind removing the godoc references from the change?

**Comment by IPv4v6** [comment]
@chrishoffman Have a look at the updated pull request after removing the links to the Go documentation.

**Comment by chrishoffman** [comment]
@IPv4v6 I apologize for the long delay here.  I was reviewing some old issues today and this documentation change seems completely reasonable and is ready to merge.  Since we last spoke, we added a CLA to our process that is needed to continue.  Would you mind checking in here?  https://cla.hashicorp.com/hashicorp/vault?pullRequest=2952.  Thanks!

**Pull request merged**
