### PR TITLE
helper/pgpkeys: add fetch key from keyserver helper function

### PR DESCRIPTION
**Pull request by jessfraz**
No idea if you have any interest in this. I was using it for something and figured why not. :P Of course pgp keyservers are unreliable as eff so the test is flaky but what can ya do haha

### CODE REVIEW

**Comment by jefferai** [comment]
Thanks for sending this in! I think it's a cool idea, however, I think more than just the MIT keyservers needs to be supported. Perhaps the input value could have a selector that selects between known aliases or a specific URL... Thoughts?

**Comment by jfrazelle** [comment]
ya for sure which ones do you want, probably the pool? and any others :)

**Comment by jefferai** [comment]
I'm not really sure which ones people are using (or not) these days, but this seems like a decent list: https://en.wikipedia.org/wiki/Key_server_(cryptographic)#Keyserver_examples

The syntax for Keybase is `keybase:<username>` so probably the syntax for this should be `keyserver:[URL or alias][sep][search criteria]`

`[sep]` above could be `:` but that might make it hard to sort if they've given a URL vs. a known alias. So possibly it should be `;` instead.

**Comment by jessfraz** [comment]
closing sorry

**Pull request closed without merging**
