### PR TITLE
Binary support for s390x

### PR DESCRIPTION
**Pull request by Nayana-ibm**
Adding s390x arch support to Vault to get binary. 
Please review

### CODE REVIEW

**Comment by Nayana-ibm** [comment]
Any update on this?

**Comment by pmmukh** [comment]
Hi @Nayana-ibm ! Thank you for submitting this PR! We are currently not ready to support s390x binaries, but this is something we're discussing internally, and when we do we'd prefer to handle this change internally, due to the testing overhead.
I'm going to go ahead and close out this PR, but I wanted to leave in instructions on creating a custom binary that can be used in the interim. ( I would guess y'all have already figured this out, so this is more for anybody else browsing issues/prs and trying to create custom binaries )
```
-  Create a fork from last vault release ( at this time, it would be 1.8.1 )
- Add this change to the fork
- Run `XC_OSARCH=linux/s390x make dev` and use that binary
```

**Comment by Nayana-ibm** [comment]
@pmmukh This link https://github.com/hashicorp/vault/blob/main/website/content/docs/release-notes/1.9.0.mdx#support-for-ibm-s390x-cpu-architecture mentions about adding support for Vault to run on the IBM s390x architecture. 
However I don't see OSS version binary.  This PR changes needs to re-consider?

**Comment by hsimon-hashicorp** [comment]
@Nayana-ibm Hi there - in 1.9, support for s390x was added to the Enterprise offering. At this time, there's no plans to add OSS support for s390x architecture. Thanks!

**Pull request closed without merging**
