### PR TITLE
Sensible permissions on creating a file

### PR DESCRIPTION
**Pull request by jjshoe**
Open a file, create it if it doesn't exist, and for gods sake don't leave it 0666.

### CODE REVIEW

**Comment by mitchellh** [comment]
0600 probably makes sense? Also, if we use OpenFile do we need to truncate the file before writing? I don't know Go's semantics here.

**Comment by jjshoe** [comment]
I'll test it out and update the PR.

**Comment by jjshoe** [comment]
Updated.

**Comment by mitchellh** [comment]
There we go. Perfect. :)

**Comment by mitchellh** [comment]
Hm, getting a test failure but I'll fix that myself

**Comment by mitchellh** [comment]
@jjshoe Turns out we need to set the write flag too: https://github.com/hashicorp/vault/commit/f676ed4d83eaeccac43a4e061b8d6fa3ed24444d :)

**Comment by jjshoe** [comment]
O:)

**Pull request merged**
