### PR TITLE
update to go 1.19.1

### PR DESCRIPTION
**Pull request by akshya96**
https://hashicorp.atlassian.net/browse/VAULT-8153

### CODE REVIEW

**Review by HridoyRoy — CHANGES_REQUESTED** [review]
I believe we need to update the version in `go.mod` and `build.yaml` as well. 

Edit: after a quick code scan, I can't seem to find build.yaml anymore, so it may have been removed or updated? The test errors are most likely coming from the `go.mod` though.

**Comment by HridoyRoy** [comment]
After doing some testing here https://github.com/hashicorp/vault/pull/17036/files I got the tests to run. I think that we don't have 1.19.1 in our registry service `docker.mirror.hashicorp.services` , but I'm not sure how to reach it so perhaps we should confirm just to be safe. 

Specifying 1.19 seems to do the trick.

**Comment by akshya96** [comment]
> After doing some testing here https://github.com/hashicorp/vault/pull/17036/files I got the tests to run. I think that we don't have 1.19.1 in our registry service `docker.mirror.hashicorp.services` , but I'm not sure how to reach it so perhaps we should confirm just to be safe.
> 
> Specifying 1.19 seems to do the trick.

I updated the PR with 1.19. I was confused because 1.19.1 is the most stable version of go after 1.18.6.

**Comment by akshya96** [comment]
Having some problem resolving these conflicts. The PR without conflicts is here https://github.com/hashicorp/vault/pull/17053.

**Pull request closed without merging**
