### PR TITLE
Allow overriding of the displayname when creating mysql users.

### PR DESCRIPTION
**Pull request by memory**
Tests pass:
`$ make test TEST=./vault
go generate
CGO_ENABLED=0 VAULT_TOKEN= VAULT_ACC= go test -tags='vault' ./vault  -timeout=120s -parallel=4
ok  	github.com/hashicorp/vault/vault	37.757s`

### CODE REVIEW

**Comment by jefferai** [comment]
I don't think we should accept this. Generally we don't allow unprivileged users to set attributes that might be considered canonical. The right approach here is likely to ensure that the token itself has the desired display name.

**Comment by memory** [comment]
So the displayname parameter is canonical but the arbitrary sql query that mutates the user table of a database isn't? :)

My goal here, which I should probably have made explicit from the start, is to make the output of mysql's `show processlist` continue to be useful.  Right now, if a single token has created multiple roles in vault, the generated usernames as visible from mysql's perspective will reflect the displayname of the token rather than the name of the role, which means that while debugging a database issue there is no way to associate a running mysql process with the vault role without consulting the vault audit log unless you create a token for each role, which seems like a great deal of unnecessary administrative overhead.

Would you accept instead a PR that used the _role_ name to create the non-uuid portion of the mysql username rather than the token displayname?

**Comment by jefferai** [comment]
Hi @memory ,

Your PR allows specifying a display name as part of the role, but the actual code adding the display name to a mysql username is a parameter sent in as part of the credential creation operation, which means that the calling user, not the administrator, is the one that decides what they want the display name to be. That easily allows a caller to mimic another caller.

Adding the role name, or adding some value set on the role (although I think there would be a better term than "display name" for that purpose), and then using that value as part of the process seems totally fine.

**Comment by memory** [comment]
Okay, using the role name itself seems like the path of least resistance then; I'll close this PR and offer up another one, probably early next week.  Thanks for the feedback!

**Comment by jefferai** [comment]
@memory Sounds good!

**Pull request closed without merging**
