### PR TITLE
Add memberOf query to ldap auth backend

### PR DESCRIPTION
**Pull request by steve-jansen**
LDAP implementations may include a memberOf attribute on the user object indicating which groups a user belongs to. This change will use the cn of each group referenced by the memberOf attribute on the user object after a successful bind.

The cn of each group will be used as the group name referenced by the memberOf attribute.

This change supports groups that span across multiple base DNs.

This change also supports LDAP servers and/or schemas that will fail to resolve groups using the
`(|(memberUid=%s)(member=%s)(uniqueMember=%s))` filter.

Tasks

- [ ] Add unit tests
- [ ] Run acceptance tests
- [ ] Update website documentation

### CODE REVIEW

**Comment by steve-jansen** [comment]
Not ready for merge, please hold.

**Comment by steve-jansen** [comment]
I have a non-standard LDAP server that does not support querying groups.  When I used the `groupdn` option on the `ldap/auth/config` path, I would see false negatives like this:

```
$ vault auth -method=ldap username=steve@example.com
Password (will be hidden):
Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/ldap/login/steve@example.com
Code: 400. Errors:

* LDAP search failed: LDAP Result Code 49 "Invalid Credentials": Invalid Credentials
```

In this case, my credentials were valid as confirmed by my LDAP event logs.  The LDAP server was returning this error due to an unsupported search.

Fortunately, my LDAP server does return `memberOf` values on the user object.  So, I figured we could just retrieve the user's object after the successful bind.

**Comment by jefferai** [comment]
Very neat idea. One question: when you say that it doesn't support quieting groups, do you mean subtree searches? Otherwise there shouldn't be much of a difference between querying a userdn or groupdn. Or is it something else?

**Comment by steve-jansen** [comment]
@jefferai 

I'm running an IAM product that exposes LDAP as one of many interfaces to authenticate users.  The product pretends to be an LDAP server, but, isn't a true LDAP server like OpenLDAP or Active Directory.

@armon had some funny remarks about LDAP as a protocol at the first [NYC HUG meetup](http://www.meetup.com/New-York-HashiCorp-User-Group/) on Vault (shameless plug!).  I feel the pain after trying to troubleshoot this behavior last night.

I've by no means an LDAP expert.  I did find examples of vendors using memberOf, like this [RedHat doc](https://access.redhat.com/documentation/en-US/JBoss_Operations_Network/3.1/html/Admin_Initial_Setup_Inventory_Groups_and_Users/ex-ldap-authz.html) and [Atlassian Crowd doc](https://confluence.atlassian.com/display/CROWD/Restricting+LDAP+Scope+for+User+and+Group+Search).  So, hopefully, I'm not out in left field, far from "proper" LDAP.

I also confirmed that my internal Active Directory uses `memberOf`.  I don't have access to an OpenLDAP setup, but, this [doc](http://www.openldap.org/doc/admin24/overlays.html) indicates it may apply in at least some OpenLDAP setups.

I could implement my use case against the HTTP API of my IAM product, I'm just being lazy and this PR seemed easier.

If this approach is wrong, don't hold back... it's why I opened this PR early.  I'm painting by numbers with golang, so language pointers/tips on my code will be most appreciated.

**Comment by jefferai** [comment]
You are *definitely* not out in left field with where this is going. I do think `memberOf` is common, but there are so many incompatible LDAP servers out there that we sort of rely on people telling/helping us what needs to change to make it work for more of them. This work is very much appreciated!

I don't have a lot of experience with LDAP at the low level, but I have had to integrate with it from various other applications. It's one of the more sobering lessons I've had to learn around "why open source".

**Comment by jefferai** [comment]
Hi @steve-jansen,

Any chance you can see if you think #1245 addresses your needs? (And ideally, if so, can you test it against your setup?)

**Comment by steve-jansen** [comment]
@jefferai d'oh, somehow missed #1245 before I started hacking!  The two PRs are similar, but, not identical.

It looks like #1245 only supports `memberOf` when you supply the optional `upndomain` config.  LDAP being so varied, I'm not 100% sure when you would need UPNs - my best guess is Active Directory.

My use case is not Active Directory, and we don't have UPNs.  So #1245 wouldn't fit our needs.

I took a more generic approach here that would work with any config.

Thoughts on what to do next?

**Comment by jefferai** [comment]
@steve-jansen I like the way that #1245 handles actually ensuring that it looks through *all* attributes. It feels like it's searching much more properly than things are now. That is assuming, of course, that `CN` is always the right value to look for (as per my comment there).

Assuming that it is, my ideal would be to use that logic but have it be valid for both the `upndomain` case and not.

**Comment by steve-jansen** [comment]
My [group parsing logic](https://github.com/steve-jansen/vault/blob/ldap-memberof-support/builtin/credential/ldap/backend.go#L180-L186) is literally copied from the [current implementation of group search logic](https://github.com/steve-jansen/vault/blob/ldap-memberof-support/builtin/credential/ldap/backend.go#L204-L209):

Compare current implementation:
```go
			dn, err := ldap.ParseDN(e.DN)
			if err != nil || len(dn.RDNs) == 0 || len(dn.RDNs[0].Attributes) == 0 {
				continue
			}
			gname := dn.RDNs[0].Attributes[0].Value
			allgroups = append(allgroups, gname)
```

with new code:
```go
				dn, err := ldap.ParseDN(groupdn)
				if err != nil || len(dn.RDNs) == 0 || len(dn.RDNs[0].Attributes) == 0 {
					continue
				}
				gname := dn.RDNs[0].Attributes[0].Value
				allgroups = append(allgroups, gname)
```

Would you like to see the code in both places refactored to explicitly load the CN?  (Perhaps in a single function called from both places?

**Comment by steve-jansen** [comment]
And yes, the commonName (`cn`) is the right attribute to use for the name of the group.

**Comment by jefferai** [comment]
> Would you like to see the code in both places refactored to explicitly load the CN? (Perhaps in a single function called from both places?

Yes! Exactly this. I think the logic in the other PR is much better so it'd be nice to use it everywhere.

**Comment by LeonDaniel** [comment]
Hello ! I made some modifications in the latest commit for [.](https://github.com/hashicorp/vault/pull/1245) Can you see if that implementation suits your needs?

**Comment by steve-jansen** [comment]
Closing in favor of #1245

**Pull request closed without merging**
