### PR TITLE
Add SHA1 signing/verification support to transit engine

### PR DESCRIPTION
**Pull request by broamski**
This adds support for the SHA1 hash algorithm in the transit engine. While identified as a having weaknesses, this allows several legacy systems to now leverage vault as where they were previously unable to do so.

### CODE REVIEW

**Comment by jefferai** [comment]
Hi there,

Can you sign the CLA and update against the changes in transit/keysutil?

Thanks!

**Comment by broamski** [comment]
Hi @jefferai - I've signed the CLA and have updated against the recent changes. Thanks!

**Comment by jefferai** [comment]
Thanks!

**Comment by briankassouf** [comment]
@broamski thanks for updating! I think everything looks good, but can you also add sha1 to the website docs? https://github.com/hashicorp/vault/blob/master/website/source/api/secret/transit/index.html.md

**Comment by jefferai** [comment]
Optimistically retargeting for 1.0.3

**Comment by broamski** [comment]
I'll update the documents shortly. While I'm thinking about it, does it make sense to be consistent and also support sha1 in the /hash and /hmac endpoints?

**Comment by jefferai** [comment]
I think since we generally want people to avoid SHA1 these days we shouldn't add it unless there is a demonstrated need. You have real legacy use cases but if those don't exist for anyone right now on the HMAC side then let's leave it be.

**Comment by broamski** [comment]
Docs updated!

**Pull request merged**
