### PR TITLE
Update gocql to resolve

### LINKED ISSUE #12878: Cassandra backend: error=gocql: no hosts available in the pool
**Describe the bug**
Vault do not restore connection with Cassandra nodes after there restart.
Then last of Cassandra node in cluster would restart Vault starts return 500 error
```
error="gocql: no hosts available in the pool
```

**To Reproduce**
1.Configure Vault to use Cassandra backend
2. Subsequence stop/start each Cassandra node in cluster based cluster availability
3. After last node stop Vault failed

**Expected behavior**
Vault should return Cassandra nodes to pool after there restore

**Environment:**
* Vault Server Version (retrieve with `vault status`): 1.8.4

Vault server configuration file(s):

```hcl
storage "cassandra" {
   hosts            = "1.cdb.vault.example.com,2.cdb.vault.example.com,3.cdb.vault.example.com"
   consistency      = "QUORUM"
   protocol_version = "2"
   keyspace = "vault"
   username = "admin"
   password = "PASSWORD"
   connection_timeout = "10"
   simple_retry_policy_retries = "3"
}
```

**Additional context**
It's a bug in gocql/gocql#915

### PR DESCRIPTION
**Pull request by qk4l**
Resolve #12878

### CODE REVIEW

**Review by HridoyRoy — COMMENTED** [review]
Can we resolve the go.mod conflicts and re-run the `go get`? I'm happy to approve the PR after that.

**Comment by qk4l** [comment]
It's kind of trick thing =(

At first I make the commit to fix resolve but it did not help. 
So I decided to rebase branch from main and seems make it worse =)

I'll close this PR and make a fresh one.

**Comment by qk4l** [comment]
Hi,

@HridoyRoy I've updated PR to resolve merge conflict.

**Comment by hghaf099** [comment]
@qk4l Would you please add a change log indicating the update on those go packages?

**Comment by conradkleinespel** [comment]
@HridoyRoy @hghaf099 I have re-created this Pull Request here, with the changelog entry added: https://github.com/hashicorp/vault/pull/14973

Let me know if this helps or what else I can do to help get this fix merged.

**Comment by swenson** [comment]
Closing in favor of #14973, which was just merged.

Thanks everyone!

**Pull request closed without merging**
