### PR TITLE
OpenAPI: Define default response structure for ListOperations

### PR DESCRIPTION
**Pull request by maxb**
Almost all Vault ListOperation responses have an identical response
schema. Update the OpenAPI generator to know this, and remove a few
instances where that standard response schema had been manually
copy/pasted into place in individual endpoints.

### CODE REVIEW

**Comment by maxb** [comment]
See above two auto-referenced PRs:

* Some cleanup in KV plugin repo too

* Draft PR exhibiting preview of affect on vault-client-go code generation

**Review by cipherboy — COMMENTED** [review]
General commentary, but you could define the standard `ListResponseWithInfo(...)`: 

https://github.com/hashicorp/vault/blob/96bb63442204a1c8981947f3182640d04f29ff85/sdk/logical/response.go#L151-L169

This should get you a standard schema for a few other list endpoints, such as in SSH, PKI, and apparently some Core stuff too. :-)

**Comment by maxb** [comment]
> General commentary, but you could define the standard `ListResponseWithInfo(...)`

However, each user of `ListResponseWithInfo(...)` gets to define their own schema on a case-by-case basis for the info payload values in the `key_info` map, therefore there is no standard schema I can apply generally - unlike the base `keys` field, which is standardized to be a slice of string in every case.

In this PR, I'd like to just cover what can be done centrally from `sdk/framework/openapi.go`.

I do see that it would be nice in future to add a helper function to abstract away the common parts of the structure created in `ListResponseWithInfo(...)` but it would need to have a parameter to allow each individual caller to specify their variant of the nested info structure.

**Comment by cipherboy** [comment]
@maxb said:

> therefore there is no standard schema I can apply generally

I don't disagree, but many of the interfaces simply use, e.g.:

https://github.com/hashicorp/vault/blob/96bb63442204a1c8981947f3182640d04f29ff85/builtin/logical/pki/path_fetch_issuers.go#L41-L45

which seems to be a generic schema? Or is what this endpoint is doing incorrect, and there shouldn't be a generic `TypeMap` in the response info, and instead every inner field of `key_info` also defined?

**Comment by maxb** [comment]
> Or is what this endpoint is doing incorrect, and there shouldn't be a generic `TypeMap` in the response info, and instead every inner field of `key_info` also defined?

Yes, this is exactly what we need to happen, if generated client libraries are to be able to render responses into endpoint specific data structures, consistent with the rest of the initiative of documenting response structures.

An additional consideration, is that there is currently no declarative specification of which endpoints actually return `key_info` on list - so there's no way to handle this other than adding individual configuration to each endpoint that does that.

**Review by averche — DISMISSED** [review]
LGTM, thanks for the contribution!

**Comment by averche** [comment]
Actually, I just noticed there are some OpenAPI related test failures, e.g. (`TestSystemBackend_OpenAPI`). Could you please take a look, @maxb.

**Comment by maxb** [comment]
> I just noticed there are some OpenAPI related test failures

Sorry about that... there are three PR checks which always fail on community PRs in this repo so I'm habituated to ignoring the red Xs :-(

Fixed.

**Review by averche — APPROVED** [review]
Thanks for fixing the tests! 🎉

**Pull request merged**
