### PR TITLE
website: add missing `@` to example

### PR DESCRIPTION
**Pull request by mathstuf**

### CODE REVIEW

**Comment by chrishoffman** [comment]
The policy write command automatically reads from a file.  The `@` parameter matters for key value parameters.

**Comment by mathstuf** [comment]
@chrishoffman Ping. Does the paragraph following that block then need to be changed?

**Comment by chrishoffman** [comment]
Yes, it can be removed.  It looks like there are a few other inconsistencies with the following blocks such as the interchanging of `policy-name` and `my-policy`.  If you could make those changes, that would be great.

**Comment by mathstuf** [comment]
Updated.

**Pull request merged**
