### PR TITLE
Add Cryptr to related tools

### PR DESCRIPTION
**Pull request by jcrowthe**
Cryptr is a newly open sourced GUI for Vault, targeting the users of vault rather than the administrators.

This is provided to the community under Adobe's open sourcing initiatives.

### CODE REVIEW

**Comment by jefferai** [comment]
> a GUI made for _consumers_ of vault secrets, rather than admins

I don't understand what this is trying to get across, but it's out of character with the rest of the descriptions

**Comment by jcrowthe** [comment]
@jefferai It is intended to say that other GUI's available are focused on the administrator of vault. In a typical organization, this would be only a few people. Cryptr is intended to be used by the rest of the organization -- individuals who interact with the secrets, but don't manage the vault infrastructure.

I am open to suggestions. If it is acceptable to still mention this distinction, how might I communicate it?

**Comment by jefferai** [comment]
I don't have advice as I don't understand the distinction. A normal GUI would expose Vault functionality. Some of that would be targeted towards admins, some of it towards users, depending on what specific functionality we're talking about.

**Comment by jcrowthe** [comment]
@jefferai It is a matter of intended audience. My bank exposes a web interface to me that is feature-complete for what I need. However, the bank manager has a completely different interface allowing him to do the same functions, plus more. Regardless if these interfaces use the the same code or not, they are very different -- with parts not even exposed to my view. It would be a fairly poor banking UI if I had lots of buttons and options for managerial functions, which I would likely never be enabled to use.

Even with this understanding, I am happy to change this to something simple, such as `Cryptr - a desktop Vault UI for Mac, Windows and Linux`. Just let me know.

**Comment by jefferai** [comment]
That suggestion sounds fine.

**Comment by jcrowthe** [comment]
Done

**Comment by jefferai** [comment]
👍

**Pull request merged**
